### ISSUE TITLE
微博频繁报错

### ISSUE THREAD

**Issue by dabo-t** [DIYgod/RSSHub#10027]
### 路由地址

```routes
weibo/user/
```

### 完整路由地址

```fullroutes
weibo/user/1618051664
```

### 相关文档

https://docs.rsshub.app/social-media.html#wei-bo

### 预期是什么？

不报错

### 实际发生了什么？

使用pm2 手动部署
pm2 monit 频繁显示Error: This path is currently fetching, please come back later!
ifttt抓取显示503错误

### 部署

自建

### 额外信息

```shell
Error in /rss/1618051664: Error: This path is currently fetching, please come back later!
at /root/rw/lib/middleware/cache/index.js:91:19
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async /root/rw/node_modules/koa-mount/index.js:52:26
at async module.exports (/root/rw/lib/middleware/parameter.js:27:5)
at async module.exports (/root/rw/lib/middleware/anti-hotlink.js:99:5) 
at async module.exports (/root/rw/lib/middleware/template.js:15:5) 
at async /root/rw/lib/middleware/api-response-handler.js:143:9 
at async module.exports (/root/rw/lib/middleware/api-template.js:2:5)
at async module.exports (/root/rw/lib/middleware/utf8.js:4:5)
at async module.exports (/root/rw/lib/middleware/header.js:21:5)
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/weibo/user/1618051664
```

**Comment by dabo-t** [comment]
![iShot2022-06-25 07 52 57](https://user-images.githubusercontent.com/9606042/175749481-5524f57d-4116-4305-b009-c2a3b05db674.png)
并不是每次都报503的错误，是不是因为ifttt抓取太频繁了，并发稍微高了点导致的？

**Comment by TonyRL** [comment]
> This path is currently fetching, please come back later!
