### ISSUE TITLE
Instagram 429

### ISSUE THREAD

**Issue by Andiedie** [DIYgod/RSSHub#1069]
### 路由地址
https://rsshub.app/instagram/user/gini_s2_

### 预期是什么？
正常获取订阅内容

### 实际发生了什么？
```
RSSHub 发生了一些意外:
Error: Request failed with status code 429
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)
    at IncomingMessage.wrappedResponseEmit (/app/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:198:24)
    at endReadableNT (_stream_readable.js:1094:12)
    at Shim.applySegment (/app/node_modules/newrelic/lib/shim/shim.js:1390:20)
    at wrapper (/app/node_modules/newrelic/lib/shim/shim.js:2014:17)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

### 额外信息
同一时间，其他 Instagram 的订阅都是正常的，只有这个路由有问题

**Comment by DerekTso** [comment]
i think it's a secret account so that it failed to fetch the data

**Comment by Andiedie** [comment]
I'm afraid it's not a secret account actually. Try [this](https://www.instagram.com/gini_s2_/).

**Comment by Andiedie** [comment]
![image](https://user-images.githubusercontent.com/21376471/47966473-ce3e4c80-e08d-11e8-84f3-722bc86add6a.png)
It seems that GitHub has a problem recognizing the URL. It missed the last "_" so you think I have given two different URLs.

Back to the problem.
**429** means "Too many requests". So waiting maybe the best way to solve this issue.

**Comment by DerekTso** [comment]
@DIYgod recently, it always hit this 429 issue when trying to add instagram feeds
