### ISSUE TITLE
【知乎】Error message: Error: Failed to extract `d_c0` from cookies

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#10907]
### 路由地址

```routes
/zhihu/people/activities/:id
```

### 完整路由地址

```fullroutes
/zhihu/people/activities/wang-tian-tian-91-22
```

### 相关文档

https://docs.rsshub.app/social-media.html#zhi-hu-yong-hu-dong-tai

### 预期是什么？

成功拉取用户动态

### 实际发生了什么？

报错

Error message: Error: Failed to extract `d_c0` from cookies

### 部署

自建

### 额外信息

```shell
Error message: Error: Failed to extract `d_c0` from cookies
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by KwToPA** [comment]
自建继续报错,官方生效
```
/zhihu/people/activities/diygod

Error message: Error: wrong path
    at module.exports (/RSSHub/lib/middleware/parameter.js:41:15)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/RSSHub/lib/middleware/anti-hotlink.js:99:5)
    at async module.exports (/RSSHub/lib/middleware/template.js:15:5)
    at async /RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/RSSHub/lib/middleware/header.js:21:5)
    at async module.exports (/RSSHub/lib/middleware/debug.js:9:5)
```
