### ISSUE TITLE
【知乎】自建报错TypeError: __g._encrypt is not a function

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#10986]
### 路由地址

```routes
/zhihu/people/activities/:id
```

### 完整路由地址

```fullroutes
/zhihu/people/activities/wang-tian-tian-91-22
```

### 相关文档

https://docs.rsshub.app/social-media.html#zhi-hu-yong-hu-dong-tai

### 预期是什么？

正常运转

### 实际发生了什么？

更新 glibc-2.18.tar.gz 后，报错变成
```
Error message: TypeError: __g._encrypt is not a function
    at D (/RSSHub/lib/v2/zhihu/execlib/g_encrypt_3.js:428:16)
    at module.exports (/RSSHub/lib/v2/zhihu/activities.js:41:29)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /RSSHub/node_modules/koa-mount/index.js:58:5
    at async  /RSSHub/node_modules/koa-mount/index.js:52:26
    at async  /RSSHub/node_modules/koa-mount/index.js:52:26
    at async /RSSHub/lib/middleware/load-on-demand.js:29:9
    at async /RSSHub/lib/middleware/cache/index.js:122:13
    at async /RSSHub/node_modules/koa-mount/index.js:52:26
```

### 部署

自建

### 部署相关信息

cenos 7 node 14.18 yarn 1.22.19 docker 20.20.11

### 额外信息

找到一篇文章

[python爬虫破解知乎登入加密信息(不使用Selenium模块)](w3xue.com/exp/article/201910/60003.html)

三.调试时候发生的错误

2.错误信息二(肯定会报错的哦)
```
execjs._exceptions.ProgramError: TypeError: __g._encrypt is not a function

```
我们execjs除了nodejs我们还需要浏览器环境,我们浏览器上还需要document以及window对象所有呢我们要安装环境

移动至项目目录

执行npm install jsdom

代码.py中我们要修改内容

```
#js_obj = execjs.compile(js_codex)修改成
js_obj = execjs.compile(js_code,cwd='node_modules'),
#也就是导入我们下载完成后的node_modules的文件
```
然后呢我们在Js_encryption.js

开头添加代码

```
const jsdom = require("jsdom");
const { JSDOM } = jsdom;
const dom = new JSDOM(`<!DOCTYPE html><p>Hello world</p>`);
window = dom.window;
document = window.document;
XMLHttpRequest = window.XMLHttpRequest;
```

固定写法别想那么多

下面有 四.修正后的完整代码

---

不知道对解决问题有没有帮助

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by KwToPA** [comment]
https://github.com/DIYgod/RSSHub/issues/10960

**Comment by KwToPA** [comment]
https://github.com/DIYgod/RSSHub/issues/10960#issuecomment-1264274085
