### ISSUE TITLE
在Heroku上部署失败

### ISSUE THREAD

**Issue by aaro-n** [DIYgod/RSSHub#10982]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
无
```

### 相关文档

无

### 预期是什么？

在Heroku上部署成功

### 实际发生了什么？

在构建时部署失败。
这是最后一次部署成功，https://github.com/DIYgod/RSSHub/compare/1dffb190...b96e7932
GitHub已经同步最新版。

### 部署

自建

### 额外信息

```shell
-----> Building on the Heroku-22 stack
-----> Using buildpack: heroku/nodejs
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       USE_YARN_CACHE=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=false
       
-----> Installing binaries
       engines.node (package.json):  >=14
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version >=14...
       Downloading and installing node 18.10.0...
       Using default npm version: 8.19.2
       Resolving yarn version 1.22.x...
       Downloading and installing yarn (1.22.19)
       Installed yarn 1.22.19
       
-----> Restoring cache
       Caching has been disabled because NODE_MODULES_CACHE=false
       
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.22.19
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       warning url-loader@1.1.2: Invalid bin field for "url-loader".
       [3/4] Linking dependencies...
       warning "request-promise-native > request-promise-core@1.1.4" has unmet peer dependency "request@^2.34".
       warning "torrent-search-api > cloudscraper@4.6.0" has unmet peer dependency "brotli@^1.3.2".
       warning " > request-promise-native@1.0.9" has unmet peer dependency "request@^2.34".
       warning " > vuepress-plugin-sitemap@2.3.1" has unmet peer dependency "chalk@^2.0.0".
       warning " > vuepress-plugin-sitemap@2.3.1" has unmet peer dependency "commander@^2.0.0".
       warning " > vuepress-plugin-sitemap@2.3.1" has unmet peer dependency "esm@^3.0.0".
       warning "@postlight/parser@2.2.2" is missing a bundled dependency "jquery". This should be reported to the package maintainer.
       warning "@postlight/parser@2.2.2" is missing a bundled dependency "moment-timezone". This should be reported to the package maintainer.
       warning "@postlight/parser@2.2.2" is missing a bundled dependency "browser-request". This should be reported to the package maintainer.
       [4/4] Building fresh packages...
       error /tmp/build_d6d139c5/node_modules/canvas: Command failed.
       Exit code: 1
       Command: node-pre-gyp install --fallback-to-build --update-binary
       Arguments: 
       Directory: /tmp/build_d6d139c5/node_modules/canvas
       Output:
       node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v108-linux-glibc-x64.tar.gz 
       Package pangocairo was not found in the pkg-config search path.
       Perhaps you should add the directory containing `pangocairo.pc'
       to the PKG_CONFIG_PATH environment variable
       No package 'pangocairo' found
       gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
       gyp ERR! configure error 
       gyp ERR! stack Error: `gyp` failed with exit code: 1
       gyp ERR! stack     at ChildProcess.onCpExit (/tmp/build_d6d139c5/node_modules/node-gyp/lib/configure.js:284:16)
       gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
       gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
       gyp ERR! System Linux 4.4.0-1104-aws
       gyp ERR! command "/tmp/build_d6d139c5/.heroku/node/bin/node" "/tmp/build_d6d139c5/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/tmp/build_d6d139c5/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/tmp/build_d6d139c5/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
       gyp ERR! cwd /tmp/build_d6d139c5/node_modules/canvas
       gyp ERR! node -v v18.10.0
       gyp ERR! node-gyp -v v9.1.0
       gyp ERR! not ok 
       node-pre-gyp ERR! build error 
       node-pre-gyp ERR! stack Error: Failed to execute '/tmp/build_d6d139c5/.heroku/node/bin/node /tmp/build_d6d139c5/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/tmp/build_d6d139c5/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/tmp/build_d6d139c5/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
       node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/build_d6d139c5/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
       node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
       node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
       node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
       node-pre-gyp ERR! System Linux 4.4.0-1104-aws
       node-pre-gyp ERR! command "/tmp/build_d6d139c5/.heroku/node/bin/node" "/tmp/build_d6d139c5/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
       node-pre-gyp ERR! cwd /tmp/build_d6d139c5/node_modules/canvas
       node-pre-gyp ERR! node -v v18.10.0
       node-pre-gyp ERR! node-pre-gyp -v v1.0.10
       node-pre-gyp ERR! not ok 
       Failed to execute '/tmp/build_d6d139c5/.heroku/node/bin/node /tmp/build_d6d139c5/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/tmp/build_d6d139c5/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/tmp/build_d6d139c5/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Can you try again in `Heroku-20` stack?

**Comment by aaro-n** [comment]
Heroku-20 
```
-----> Building on the Heroku-20 stack
-----> Using buildpack: heroku/nodejs
-----> Node.js app detected
       
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       USE_YARN_CACHE=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=false
       
-----> Installing binaries
       engines.node (package.json):  >=14
       engines.npm (package.json):   unspecified (use default)
       engines.yarn (package.json):  unspecified (use default)
       
       Resolving node version >=14...
       Downloading and installing node 18.10.0...
       Using default npm version: 8.19.2
       Resolving yarn version 1.22.x...
       Downloading and installing yarn (1.22.19)
       Installed yarn 1.22.19
       
-----> Restoring cache
       Caching has been disabled because NODE_MODULES_CACHE=false
       
-----> Installing dependencies
       Installing node modules (yarn.lock)
       yarn install v1.22.19
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       warning url-loader@1.1.2: Invalid bin field for "url-loader".
       [3/4] Linking dependencies...
       warning "request-promise-native > request-promise-core@1.1.4" has unmet peer dependency "request@^2.34".
       warning "torrent-search-api > cloudscraper@4.6.0" has unmet peer dependency "brotli@^1.3.2".
       warning " > request-promise-native@1.0.9" has unmet peer dependency "request@^2.34".
       warning " > vuepress-plugin-sitemap@2.3.1" has unmet peer dependency "chalk@^2.0.0".
       warning " > vuepress-plugin-sitemap@2.3.1" has unmet peer dependency "commander@^2.0.0".
       warning " > vuepress-plugin-sitemap@2.3.1" has unmet peer dependency "esm@^3.0.0".
       warning "@postlight/parser@2.2.2" is missing a bundled dependency "jquery". This should be reported to the package maintainer.
       warning "@postlight/parser@2.2.2" is missing a bundled dependency "moment-timezone". This should be reported to the package maintainer.
       warning "@postlight/parser@2.2.2" is missing a bundled dependency "browser-request". This should be reported to the package maintainer.
       [4/4] Building fresh packages...
       error /tmp/build_b7eb69bd/node_modules/canvas: Command failed.
       Exit code: 1
       Command: node-pre-gyp install --fallback-to-build --update-binary
       Arguments: 
       Directory: /tmp/build_b7eb69bd/node_modules/canvas
       Output:
       node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.10.1/canvas-v2.10.1-node-v108-linux-glibc-x64.tar.gz 
       Package pangocairo was not found in the pkg-config search path.
       Perhaps you should add the directory containing `pangocairo.pc'
       to the PKG_CONFIG_PATH environment variable
       No package 'pangocairo' found
       gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
       gyp ERR! configure error 
       gyp ERR! stack Error: `gyp` failed with exit code: 1
       gyp ERR! stack     at ChildProcess.onCpExit (/tmp/build_b7eb69bd/node_modules/node-gyp/lib/configure.js:284:16)
       gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
       gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
       gyp ERR! System Linux 4.4.0-1104-aws
       gyp ERR! command "/tmp/build_b7eb69bd/.heroku/node/bin/node" "/tmp/build_b7eb69bd/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/tmp/build_b7eb69bd/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/tmp/build_b7eb69bd/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
       gyp ERR! cwd /tmp/build_b7eb69bd/node_modules/canvas
       gyp ERR! node -v v18.10.0
       gyp ERR! node-gyp -v v9.1.0
       gyp ERR! not ok 
       node-pre-gyp ERR! build error 
       node-pre-gyp ERR! stack Error: Failed to execute '/tmp/build_b7eb69bd/.heroku/node/bin/node /tmp/build_b7eb69bd/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/tmp/build_b7eb69bd/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/tmp/build_b7eb69bd/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
       node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/tmp/build_b7eb69bd/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
       node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
       node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
       node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
       node-pre-gyp ERR! System Linux 4.4.0-1104-aws
       node-pre-gyp ERR! command "/tmp/build_b7eb69bd/.heroku/node/bin/node" "/tmp/build_b7eb69bd/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
       node-pre-gyp ERR! cwd /tmp/build_b7eb69bd/node_modules/canvas
       node-pre-gyp ERR! node -v v18.10.0
       node-pre-gyp ERR! node-pre-gyp -v v1.0.10
       node-pre-gyp ERR! not ok 
       Failed to execute '/tmp/build_b7eb69bd/.heroku/node/bin/node /tmp/build_b7eb69bd/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/tmp/build_b7eb69bd/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/tmp/build_b7eb69bd/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Dangerous semver range (>) in engines.node
         https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by liyuweiying** [comment]
Same problem here.
