### ISSUE TITLE
36kr 路由出现 dom 解析错误 （已查明原因）

### ISSUE THREAD

**Issue by sakurayang** [DIYgod/RSSHub#11183]
### 路由地址

```routes
/36kr/information/:category
/36kr/user/:id
/36kr/motif/:id
/36kr/topics/:id
/36kr/search/articles/:keyword
/36kr/search/newsflashes/:keyword
```

### 完整路由地址

```fullroutes
/36kr/news/latest
/36kr/information/web_news
/36kr/newsflashes
/36kr/user/747305693
/36kr/motif/452
/36kr/topics/1818512662032001
/36kr/search/articles/ofo
/36kr/search/newsflashes/ofo
```

### 相关文档

https://docs.rsshub.app/new-media.html#_36kr

### 预期是什么？

得到正常的 xml

### 实际发生了什么？

```
Route requested: /information/web_news
Error message: TypeError: Cannot read properties of null (reading '1')
    at D:\git\RSSHub\lib\v2\36kr\index.js:51:102
    at runMicrotasks ()
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.tryGet (D:\git\RSSHub\lib\middleware\cache\index.js:64:21)
    at async Promise.all (index 15)
    at async module.exports (D:\git\RSSHub\lib\v2\36kr\index.js:42:17)
    at async D:\git\RSSHub\node_modules\koa-mount\index.js:58:5
    at async D:\git\RSSHub\node_modules\koa-mount\index.js:52:26
    at async D:\git\RSSHub\lib\middleware\load-on-demand.js:29:9
    at async D:\git\RSSHub\lib\middleware\cache\index.js:122:13
Helpful Information to provide when opening issue:
Path: /information/web_news
Node version: v16.15.0
Git Hash: 47f97d9
```

### 部署

自建

### 部署相关信息

OS: Linux/Windows10 Node: v16.15.0

### 额外信息

```shell
TypeError: Cannot read properties of null (reading '1')
    at D:\git\RSSHub\lib\v2\36kr\index.js:51:102
    at runMicrotasks ()
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.tryGet (D:\git\RSSHub\lib\middleware\cache\index.js:64:21)
    at async Promise.all (index 15)
    at async module.exports (D:\git\RSSHub\lib\v2\36kr\index.js:42:17)
    at async D:\git\RSSHub\node_modules\koa-mount\index.js:58:5
    at async D:\git\RSSHub\node_modules\koa-mount\index.js:52:26
    at async D:\git\RSSHub\lib\middleware\load-on-demand.js:29:9
    at async D:\git\RSSHub\lib\middleware\cache\index.js:122:13
```
```


### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by sakurayang** [comment]
经过查阅 [/lib/v2/36kr/index.js:51:102](https://github.com/DIYgod/RSSHub/blob/47f97d9dde043e78fe58a523ce4c5f324eb03301/lib/v2/36kr/index.js#L51)

可发现其中首先查找了一个符合 `{"state":"(.*)","isEncrypt":true}` 的字符串，然后对其进行了解密。
但是经过调试后发现，`detailResponse.data` 里面完全没有符合的字符串。

![image](https://user-images.githubusercontent.com/11017232/198865240-2d8732f8-bcfb-413c-97e3-a1399bb8f7c3.png)

故 `match` 的返回为 `null` ，出现 `Cannot read properties of null (reading '1')`

![image](https://user-images.githubusercontent.com/11017232/198865308-13a6f05e-b8eb-4283-9f87-47e8117a04dd.png)

---
### 解决方法

```js diff
 items.map((item) =>
    ctx.cache.tryGet(item.link, async () => {
        const detailResponse = await got({
            method: 'get',
            url: item.link,
        });

-        const key = CryptoJS.enc.Utf8.parse('efabccee-b754-4c');
-        const cipherText = detailResponse.data.match(/{"state":"(.*)","isEncrypt":true}/)[1];

-        const content = JSON.parse(
-            CryptoJS.AES.decrypt(cipherText, key, {
-                mode: CryptoJS.mode.ECB,
-                padding: CryptoJS.pad.Pkcs7,
-            })
-                .toString(CryptoJS.enc.Utf8)
-                .toString()
-        ).articleDetail.articleDetailData.data;

-        item.description = content.widgetContent;

+        let $ = cheerio.load(detailResponse.body);
+        let c = $("div.articleDetailContent")
+
+        item.description = c.html();

        return item;
    })
)
```

此处由于不知道对原来的 issues#10175 有无影响，故不提pr

**Comment by sakurayang** [comment]
经过五天的使用，该变更对订阅源无影响。也许是 36kr 目前的全文不加密了？此处可以做个判断免得以后又变回去了

```diff js
 items.map((item) =>
    ctx.cache.tryGet(item.link, async () => {
        const detailResponse = await got({
            method: 'get',
            url: item.link,
        });


-        const key = CryptoJS.enc.Utf8.parse('efabccee-b754-4c');
         const cipherTextList = detailResponse.data.match(/{"state":"(.*)","isEncrypt":true}/);
+       if (cipherTextList) {
+           const key = CryptoJS.enc.Utf8.parse('efabccee-b754-4c');
             const content = JSON.parse(
                 CryptoJS.AES.decrypt(cipherText, key, {
                     mode: CryptoJS.mode.ECB,
                     padding: CryptoJS.pad.Pkcs7,
                 })
                     .toString(CryptoJS.enc.Utf8)
                    .toString()
             ).articleDetail.articleDetailData.data;
             item.description = content.widgetContent;
+       } else {
+           let $ = cheerio.load(detailResponse.body);
+           let c = $("div.articleDetailContent")
+           item.description = c.html();
+       }
        return item;
    })
)
```
