### ISSUE TITLE
youtube user 路由不可用

### ISSUE THREAD

**Issue by CHN-beta** [DIYgod/RSSHub#11576]
### 路由地址

```routes
/youtube/user/:username/:disableEmbed?
```

### 完整路由地址

```fullroutes
/youtube/user/:username/:disableEmbed?
```

### 相关文档

https://docs.rsshub.app/social-media.html#youtube-yong-hu

### 预期是什么？

正常获得用户的视频列表

### 实际发生了什么？

无论是自建（rsshub.chn.moe）还是演示站点，均得到相似的错误：
```
Error message: TypeError: Cannot read properties of undefined (reading '0')
```

### 部署

自建

### 部署相关信息

OS: Gentoo Linux, Node: v18.10.0

### 额外信息

```shell
以下是自建站点的错误内容，比演示站点略微详细一些。

Route requested: /user/user-nc9xp1tb1u/

Error message: TypeError: Cannot read properties of undefined (reading '0')
    at module.exports (/home/chn/www/rsshub.chn.moe/lib/v2/youtube/user.js:12:110)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/chn/www/rsshub.chn.moe/node_modules/koa-mount/index.js:58:5
    at async /home/chn/www/rsshub.chn.moe/node_modules/koa-mount/index.js:52:26
    at async /home/chn/www/rsshub.chn.moe/lib/middleware/load-on-demand.js:29:9
    at async /home/chn/www/rsshub.chn.moe/lib/middleware/cache/index.js:122:13
    at async /home/chn/www/rsshub.chn.moe/node_modules/koa-mount/index.js:52:26
    at async module.exports (/home/chn/www/rsshub.chn.moe/lib/middleware/parameter.js:27:5)
    at async module.exports (/home/chn/www/rsshub.chn.moe/lib/middleware/anti-hotlink.js:99:5)
    at async module.exports (/home/chn/www/rsshub.chn.moe/lib/middleware/template.js:15:5)
```
```


### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by CHN-beta** [comment]
`/youtube/user/:username/:disableEmbed?`这个路由是存在的啊，为什么会报不存在？

**Comment by TonyRL** [comment]
Closed in #11739
