### ISSUE TITLE
澎湃新闻 报错

### ISSUE THREAD

**Issue by Elypha** [DIYgod/RSSHub#11620]
### 路由地址

```routes
/thepaper/list/:id
```

### 完整路由地址

```fullroutes
thepaper/list/25483
```

### 相关文档

https://docs.rsshub.app/traditional-media.html#peng-pai-xin-wen-lan-mu

### 预期是什么？

返回xml

### 实际发生了什么？

Looks like something went wrong
Route requested: /list/25483
Error message: Cannot read properties of undefined (reading 'list')
Helpful Information to provide when opening issue:
Path: /list/25483
Node version: v16.19.0
Git Hash: ef5275c

### 部署

自建

### 部署相关信息

Docker

### 额外信息

```shell
Jan 15 00:11:47 debian bash[5308]: info: /thepaper/list/25483?key=.elf, user IP: 137.220.76.51
Jan 15 00:11:48 debian bash[5308]: error: Error in /list/25483: TypeError: Cannot read properties of undefined (reading 'list')
Jan 15 00:11:48 debian bash[5308]:     at module.exports (/elypha/project/RSSHub/lib/v2/thepaper/list.js:11:32)
Jan 15 00:11:48 debian bash[5308]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Jan 15 00:11:48 debian bash[5308]:     at async /elypha/project/RSSHub/node_modules/koa-mount/index.js:58:5
Jan 15 00:11:48 debian bash[5308]:     at async /elypha/project/RSSHub/node_modules/koa-mount/index.js:52:26
Jan 15 00:11:48 debian bash[5308]:     at async /elypha/project/RSSHub/lib/middleware/load-on-demand.js:29:9
Jan 15 00:11:48 debian bash[5308]:     at async /elypha/project/RSSHub/lib/middleware/cache/index.js:122:13
Jan 15 00:11:48 debian bash[5308]:     at async /elypha/project/RSSHub/node_modules/koa-mount/index.js:52:26
Jan 15 00:11:48 debian bash[5308]:     at async module.exports (/elypha/project/RSSHub/lib/middleware/parameter.js:27:5)
Jan 15 00:11:48 debian bash[5308]:     at async module.exports (/elypha/project/RSSHub/lib/middleware/anti-hotlink.js:99:5)
Jan 15 00:11:48 debian bash[5308]:     at async module.exports (/elypha/project/RSSHub/lib/middleware/template.js:15:5)
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Elypha** [comment]
从master安装的话也有同样问题，log：
```
Looks like something went wrong
Route requested: /list/25483
Error message: TypeError: Cannot read properties of undefined (reading 'list')
    at module.exports (/elypha/project/RSSHub/lib/v2/thepaper/list.js:11:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /elypha/project/RSSHub/node_modules/koa-mount/index.js:58:5
    at async /elypha/project/RSSHub/node_modules/koa-mount/index.js:52:26
    at async /elypha/project/RSSHub/lib/middleware/load-on-demand.js:29:9
    at async /elypha/project/RSSHub/lib/middleware/cache/index.js:122:13
    at async /elypha/project/RSSHub/node_modules/koa-mount/index.js:52:26
    at async module.exports (/elypha/project/RSSHub/lib/middleware/parameter.js:27:5)
    at async module.exports (/elypha/project/RSSHub/lib/middleware/anti-hotlink.js:99:5)
    at async module.exports (/elypha/project/RSSHub/lib/middleware/template.js:15:5)
Helpful Information to provide when opening issue:
Path: /list/25483
Node version: v18.13.0
Git Hash: b404cc6
```
