### ISSUE TITLE
vercel部署失败，提示Error: ENOENT: no such file or directory, stat '/vercel/path0/src'

### ISSUE THREAD

**Issue by ylsmt** [DIYgod/RSSHub#11647]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NORUTE
```

### 相关文档

无

### 预期是什么？

vercel成功部署

### 实际发生了什么？

vercel building中断

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
[21:49:14.591] Cloning github.com/ylsmt/rsshub (Branch: dependabot/npm_and_yarn/entities-4.4.0, Commit: e1728b6)
[21:49:15.200] Previous build caches not available
[21:49:15.703] Cloning completed: 1.111s
[21:49:16.849] Running "vercel build"
[21:49:17.451] Vercel CLI 28.12.6
[21:49:19.427] Warning: Detected "engines": { "node": ">=14" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[21:49:19.431] Installing dependencies...
[21:49:19.882] yarn install v1.22.17
[21:49:20.020] [1/5] Validating package.json...
[21:49:20.024] [2/5] Resolving packages...
[21:49:20.816] [3/5] Fetching packages...
[21:49:42.907] warning url-loader@1.1.2: Invalid bin field for "url-loader".
[21:49:52.205] [4/5] Linking dependencies...
[21:49:52.211] warning "request-promise-native > request-promise-core@1.1.4" has unmet peer dependency "request@^2.34".
[21:49:52.212] warning "torrent-search-api > cloudscraper@4.6.0" has unmet peer dependency "brotli@^1.3.2".
[21:49:52.216] warning " > request-promise-native@1.0.9" has unmet peer dependency "request@^2.34".
[21:49:52.225] warning " > vuepress-plugin-sitemap@2.3.1" has unmet peer dependency "chalk@^2.0.0".
[21:49:52.225] warning " > vuepress-plugin-sitemap@2.3.1" has unmet peer dependency "commander@^2.0.0".
[21:49:52.225] warning " > vuepress-plugin-sitemap@2.3.1" has unmet peer dependency "esm@^3.0.0".
[21:50:11.760] [5/5] Building fresh packages...
[21:50:20.756] Done in 60.88s.
[21:50:22.162] wait Extracting site metadata...
[21:50:22.163] warning Source directory doesn't exist: /vercel/path0/src
[21:50:22.168] tip Apply theme @vuepress/theme-default ...
[21:50:22.196] tip Apply plugin container (i.e. "vuepress-plugin-container") ...
[21:50:22.196] tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
[21:50:22.197] tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
[21:50:22.197] tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
[21:50:22.198] tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
[21:50:22.245] Error: ENOENT: no such file or directory, stat '/vercel/path0/src'
[21:50:22.245]     at Object.statSync (node:fs:1596:3)
[21:50:22.246]     at checkCwdOption (/vercel/path0/node_modules/globby/index.js:20:36)
[21:50:22.246]     at generateGlobTasks (/vercel/path0/node_modules/globby/index.js:28:2)
[21:50:22.246]     at App.resolvePages (/vercel/path0/node_modules/@vuepress/core/lib/node/App.js:335:34)
[21:50:22.246]     at App.process (/vercel/path0/node_modules/@vuepress/core/lib/node/App.js:115:16)
[21:50:22.246]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[21:50:22.246]     at async build (/vercel/path0/node_modules/@vuepress/core/lib/index.js:26:3)
[21:50:22.270] Error: Command "vuepress build src" exited with 1
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by ylsmt** [comment]
> 
Thanks for your answer，how do i install it correctly in vercel?

**Comment by ylsmt** [comment]
I have solved this problem by changing framework preset.

**Comment by ylsmt** [comment]
Thanks again.

**Comment by ifency** [comment]
How solve this problem? I have same problem.

**Comment by Annihilatexv** [comment]
> How solve this problem? I have same problem.

change the framework preset "vuepress" to "other", when you deploy.

**Comment by ifency** [comment]
> > How solve this problem? I have same problem.
> 
> change the framework preset "vuepress" to "other", when you deploy.

Thank you.

**Comment by styfle** [comment]
I created PR https://github.com/DIYgod/RSSHub/pull/11980 with the fix
