### ISSUE TITLE
知乎用户动态activities路由失效

### ISSUE THREAD

**Issue by Liu-Guang** [DIYgod/RSSHub#11882]
### 路由地址

```routes
/zhihu/people/activities/:id
```

### 完整路由地址

```fullroutes
/zhihu/people/activities/diygod
```

### 相关文档

https://docs.rsshub.app/social-media.html#zhi-hu-yong-hu-dong-tai

### 预期是什么？

正常抓取知乎用户动态

### 实际发生了什么？

Response code 403 (Forbidden): target website might be blocking our access

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

Ubuntu 20.04.5 LTS

### 额外信息

```shell
尝试更换了几次服务器的ip，依然是403 Forbidden
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by bigfei** [comment]
standalone rsshub instance also get blocked with 
```
Route requested: /people/activities/bopengbopeng
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /people/activities/bopengbopeng
Node version: v16.19.0
Git Hash: ae3bccd

```

**Comment by YukiSou** [comment]
happened also on self host instance

```
Error message: Error: Failed to extract `d_c0` from cookies
    at /root/RSSHub/lib/v2/zhihu/activities.js:27:19
    at runMicrotasks ()
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.tryGet (/root/RSSHub/lib/middleware/cache/index.js:64:21)
    at async module.exports (/root/RSSHub/lib/v2/zhihu/activities.js:15:24)
    at async /root/RSSHub/node_modules/koa-mount/index.js:58:5
    at async /root/RSSHub/node_modules/koa-mount/index.js:52:26
    at async /root/RSSHub/lib/middleware/load-on-demand.js:29:9
    at async /root/RSSHub/lib/middleware/cache/index.js:122:13
    at async /root/RSSHub/node_modules/koa-mount/index.js:52:26

Helpful Information to provide when opening issue:
Path: /people/activities/diygod
Node version: v16.15.1
Git Hash: fbccaec
        
```

**Comment by TonyRL** [comment]
/test
```routes
/zhihu/people/activities/diygod
```

**Comment by KwToPA** [comment]
https://github.com/DIYgod/RSSHub/issues/11868

自建和官方都被封IP

**Comment by KwToPA** [comment]
这个问题应该是一周或者两周前出现的

确切日期记不清了

**Comment by UniSpaceX** [comment]
在国内VPS上运行 docker image id 74d8a76af600，提示报错：

> Route requested: /people/activities/nogirlnotalk
Error message: Failed to extract `d_c0` from cookies
Helpful Information to provide when opening issue:
Path: /people/activities/nogirlnotalk
Node version: v16.19.0
Git Hash: fbccaec

宽带公网IP 手动部署最新master，第一次运行时 RSS拉取成功，后续报错：

> Route requested: /people/activities/nogirlnotalk
Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
Helpful Information to provide when opening issue:
Path: /people/activities/nogirlnotalk
Node version: v18.12.1
Git Hash: unknown

浏览器登录知乎官网提示：
> 系统监测到您的网络环境存在异常，为保证您的正常访问，请点击下方验证按钮进行验证。在您验证完成前，该提示将多次出现

手动验证通过之后，又可以成功进行一至两次 RSS拉取，后续重复报错。
应该是知乎的反爬限制提高了。

**Comment by abolast** [comment]
> 在国内VPS上运行 docker image id 74d8a76af600，提示报错：
> 
> > Route requested: /people/activities/nogirlnotalk
> > Error message: Failed to extract `d_c0` from cookies
> > Helpful Information to provide when opening issue:
> > Path: /people/activities/nogirlnotalk
> > Node version: v16.19.0
> > Git Hash: fbccaec
> 
> 宽带公网IP 手动部署最新master，第一次运行时 RSS拉取成功，后续报错：
> 
> > Route requested: /people/activities/nogirlnotalk
> > Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.
> > Helpful Information to provide when opening issue:
> > Path: /people/activities/nogirlnotalk
> > Node version: v18.12.1
> > Git Hash: unknown
> 
> 浏览器登录知乎官网提示：
> 
> > 系统监测到您的网络环境存在异常，为保证您的正常访问，请点击下方验证按钮进行验证。在您验证完成前，该提示将多次出现
> 
> 手动验证通过之后，又可以成功进行一至两次 RSS拉取，后续重复报错。 应该是知乎的反爬限制提高了。

看了你的反馈，我换了服务器ip，然后把请求频率从55min改成9h/次

**Comment by KwToPA** [comment]
@abolast  我停了两天再抓 依然封号  不过不是全封

全部N条，其中偶尔若干条解封，会抓一部分  之后又封，感觉这个解封是随机的

我抓取频率没改，15分钟一次

**Comment by abolast** [comment]
> 



> @abolast 我停了两天再抓 依然封号 不过不是全封
> 
> 全部N条，其中偶尔若干条解封，会抓一部分 之后又封，感觉这个解封是随机的
> 
> 我抓取频率没改，15分钟一次

知乎不干人事。我刚才又换了一个ip，抓一次然后马上失效。是不是知乎已经识别rsshub了。

**Comment by KwToPA** [comment]
@abolast  现在我关注的所有知乎路由都封了

**Comment by Spartanmans** [comment]
> @abolast 现在我关注的所有知乎路由都封了

我也是，大概一周前

**Comment by Reborn404** [comment]
知乎的都失效了

**Comment by woodgear** [comment]
+1

**Comment by zhaojames0707** [comment]
+1

**Comment by KwToPA** [comment]
https://github.com/DIYgod/RSSHub/issues/11984

rsshub的tg群里有用户反馈 知乎路由复活了

我自建的机器报错从 Response code 403 (Forbidden): target website might be blocking our access

 变成 Error: Failed to extract `d_c0` from cookies

**Comment by JamYiz** [comment]
动态和专栏都失效了

**Comment by jy324** [comment]
大佬们，会不会是因为知乎API从v3升级到了v4，所以按之前的爬很快就失效了？
https://github.com/DIYgod/RSSHub/blob/b1400b97f41b4e442fc26cf1dafd78feb8b00e6c/lib/v2/zhihu/activities.js#L34
![image](https://user-images.githubusercontent.com/74438973/225282877-93fc9f5b-b007-4590-9831-2e2ffd7ffe7d.png)

**Comment by KwToPA** [comment]
https://github.com/DIYgod/RSSHub/issues/11984#issuecomment-1474692455

我这边恢复了

**Comment by KwToPA** [comment]
我这边 一个半月没抓 每条知乎用户更新的内容只有7个

**Comment by jy324** [comment]
你订阅了多少用户🤔

**Comment by KwToPA** [comment]
@jy324  我吗？  2K多

**Comment by jy324** [comment]
不是😂rss里订阅了多少知乎用户

**Comment by jy324** [comment]
我订阅了20个，怕到时量大给封了

**Comment by KwToPA** [comment]
800-1000这个级别

**Comment by KwToPA** [comment]
又变回 报错  Failed to extract `d_c0` from cookies  

/RSSHub/lib/v2/zhihu/activities.js:27:19

**Comment by JamYiz** [comment]
> 又变回 报错 Failed to extract `d_c0` from cookies
> 
> /RSSHub/lib/v2/zhihu/activities.js:27:19

是不是你爬取的太多了？我昨天恢复之后就没有出错了

**Comment by KwToPA** [comment]
@JamYiz  现在的状态又变成 最初的 时而能抓几个，时而全报错  最新的报错 

Response code 403 (Forbidden)

**Comment by JamYiz** [comment]
> @JamYiz 现在的状态又变成 最初的 时而能抓几个，时而全报错 最新的报错
> 
> Response code 403 (Forbidden)

我只抓了个位数的源，没有出错了。大概率你是抓太多被办了。

**Comment by jy324** [comment]
我也正常

**Comment by TonyRL** [comment]
/test
```routes
/zhihu/people/activities/diygod
```

**Comment by TonyRL** [comment]
/test
```routes
/zhihu/people/activities/diygod
/zhihu/people/activities/bopengbopeng
```

**Comment by KwToPA** [comment]
我自建的又被封了

还是报错  Error message: Failed to extract `d_c0` from cookies

官方的也是403

最初被封时，我停了1天，之后解封过1次，几天后再次被封锁IP，到如今都没解封

**Comment by KwToPA** [comment]
> 我自建的又被封了
> 
> 还是报错 Error message: Failed to extract `d_c0` from cookies
> 
> 官方的也是403
> 
> 最初被封时，我停了1天，之后解封过1次，几天后再次被封锁IP，到如今都没解封

知乎网页版是不是改版了？ 界面有些不一样
