### ISSUE TITLE
nHentai 高级搜索无法正常生成 RSS

### ISSUE THREAD

**Issue by ElderDoge** [DIYgod/RSSHub#1190]
### 路由地址
/nhentai/search/:keyword
### 预期是什么？
正常生成RSS
### 实际发生了什么？
仅仅在连续请求2-3次之后才能正常生成RSS，一旦过几分钟重新请求，得到错误信息（见底部）。这导致了inoreader RSS服务无法正常使用，每次请求都会返回错误！
### 部署相关信息
演示部署与私人部署都无法使用
### 额外信息（日志、报错等）
从浏览器打开地址后显示：
```
RSSHub 发生了一些意外:
Error: Request failed with status code 503
    at createError (/opt/RSSHub/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/RSSHub/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/opt/RSSHub/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1098:12)
    at args.(anonymous function) (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

```

**Comment by MegrezZhu** [comment]
应该是ip被限流的缘故…可以搞个不请求每个页面内容的/nhentai/simple/search路由替代

**Comment by ElderDoge** [comment]
发现不论是关键词还是高级搜索都一样的错误，而且并不能通过多次重新请求解决(演示)。
只能不请求页面内容了吗？我的私人部署在连续刷新两次之后就能正常获取了，有没有其他更好的解决办法呢……

**Comment by ElderDoge** [comment]
> 应该是ip被限流的缘故…可以搞个不请求每个页面内容的/nhentai/simple/search路由替代

不过现在的路由部分新文章也只能获取一个cover，可能搞个simple再自己跳转到原网址确实更好一些吧，起码能获取到封面，观看体验也统一了，哈哈

**Comment by MegrezZhu** [comment]
要靠连续刷新才能正常获取是因为没办法在一个请求的超时时间内把每个页面的内容都加载完，这还挺看网络条件的（而且也不能被限流，限流就503），就这个问题来说我没想到很好的解决方法。要么增加litmit参数，要么提高缓存时间（我写的时候是默认缓存时长）——不过都不治本，503就GG

**Comment by ElderDoge** [comment]
多谢大佬，那就只有期待simple版尽快上线了！
但是其他网站如果也有相应限制，应该也会有这种问题吧，是不是超时时间太短了？超时时间是RSS服务自己决定的吗？

**Comment by ElderDoge** [comment]
谢谢大佬
