### ISSUE TITLE
色花堂路由无法使用

### ISSUE THREAD

**Issue by ly012** [DIYgod/RSSHub#12109]
### 路由地址

```routes
/sehuatang/:subforumid?/:type?
```

### 完整路由地址

```fullroutes
/sehuatang/gqzwzm
```

### 相关文档

https://docs.rsshub.app/multimedia.html#se-hua-tang

### 预期是什么？

正常使用。

### 实际发生了什么？

![Snipaste_2023-03-15_19-53-01](https://user-images.githubusercontent.com/30511978/225302149-5b1bd4f5-d4bc-40e6-9128-5ace8fa95fbf.png)
色花堂现在第一次访问必须手动点击满18岁，导致rsshub抓不了内容了。

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Looks like something went wrong
Route requested: /sehuatang/gqzwzm
Error message: Error: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)
    at module.exports (/opt/rsshub/lib/middleware/parameter.js:46:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (/opt/rsshub/lib/middleware/anti-hotlink.js:99:5)
    at async module.exports (/opt/rsshub/lib/middleware/template.js:15:5)
    at async /opt/rsshub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/opt/rsshub/lib/middleware/api-template.js:2:5)
    at async module.exports (/opt/rsshub/lib/middleware/utf8.js:4:5)
    at async module.exports (/opt/rsshub/lib/middleware/header.js:21:5)
    at async module.exports (/opt/rsshub/lib/middleware/debug.js:9:5)
    at async grant (/opt/rsshub/lib/middleware/access-control.js:24:13)
Helpful Information to provide when opening issue:
Path: /sehuatang/gqzwzm
Node version: v18.15.0
Git Hash: unknown
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by ly012** [comment]
虽然现在色花堂的路由不行了，但是通过在.env 增加discuz cookie 后手动部署。通过discuz路由可以正常抓取。
