### ISSUE TITLE
tiktok

### ISSUE THREAD

**Issue by wedcf120** [DIYgod/RSSHub#12406]
### 路由地址

```routes
https://docs.rsshub.app/en/social-media.html#tiktok
```

### 完整路由地址

```fullroutes
http://127.0.0.1:1200/tiktok/user/@enola.bedard
```

### 相关文档

https://docs.rsshub.app/en/social-media.html#tiktok

### 预期是什么？

网站改版

### 实际发生了什么？

路由报错

![20230428203701](https://user-images.githubusercontent.com/21985575/235149324-76590c2d-623e-4986-b3c0-a6958c1815f2.png)

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

http://127.0.0.1:1200/tiktok/user/@enola.bedard

### 额外信息

```shell
curl http://127.0.0.1:1200/tiktok/user/@enola.bedard

<!DOCTYPE html><html><head><title>Error in RSSHub!</title><style>body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Oxygen,Ubuntu,Cantarell,Fira Sans,Droid Sans,Helvetica Neue,sans-serif;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;font-size:16px;color:#2c3e50}.content{width:800px;margin:100px auto 0;text-align:center}.message{white-space:pre-wrap;text-align:left}a{color:#f5712c}</style></head><body><div class="content"><p><img src="https://i.loli.net/2019/09/04/lmBbNQoLzrKGgiM.jpg" alt="RSSHub" width="120"></p><h1>Looks like something went wrong</h1><pre class="message">Route requested: /user/@enola.bedard</pre><pre class="message">Error message: Execution context was destroyed, most likely because of a navigation.</pre><pre class="message">
Helpful Information to provide when opening issue:
Path: /user/@enola.bedard
Node version: v16.19.0
Git Hash: ab2f618
        </pre><pre class="message">
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行<a href="https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_zh.yml" target="_blank">汇报</a>
If you believe this is an error caused by RSSHub, please <a href="https://github.com/DIYgod/RSSHub/issues/new?assignees=&labels=RSS+bug&template=bug_report_en.yml" target="_blank">report on github</a>
        </pre><div style="margin:50px 0"><p>在线文档与支持，请访问<a href="https://docs.rsshub.app/" target="_blank">docs.rsshub.app</a>。</p><p>For online documentation and support please refer to <a href="https://docs.rsshub.app/" target="_blank">docs.rsshub.app</a>.</p></div></div></body></html>
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by wedcf120** [comment]
@TonyRL

**Comment by wedcf120** [comment]
https://docs.rsshub.app/en/social-media.html#tiktok

tiktok的路由在英文版

**Comment by wedcf120** [comment]
Route requested: /user/@enola.bedard
Error message: TypeError: Cannot read properties of undefined (reading 'value')
    at module.exports (/root/RSSHub/lib/v2/tiktok/user.js:49:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /root/RSSHub/node_modules/koa-mount/index.js:58:5
    at async /root/RSSHub/node_modules/koa-mount/index.js:52:26
    at async /root/RSSHub/lib/middleware/load-on-demand.js:29:9
    at async /root/RSSHub/lib/middleware/cache/index.js:122:13
    at async /root/RSSHub/node_modules/koa-mount/index.js:52:26
    at async module.exports (/root/RSSHub/lib/middleware/parameter.js:27:5)
    at async module.exports (/root/RSSHub/lib/middleware/anti-hotlink.js:99:5)
    at async module.exports (/root/RSSHub/lib/middleware/template.js:15:5)
Helpful Information to provide when opening issue:
Path: /user/@enola.bedard
Node version: v16.18.1
Git Hash: 1d7f3bf

**Comment by wedcf120** [comment]
@TonyRL 
fix please, it's down :)
