### ISSUE TITLE
npm安装依赖失败

### ISSUE THREAD

**Issue by cooper1x** [DIYgod/RSSHub#1253]
### 路由地址
没运行成功，暂无。
### 预期是什么？
项目正常运行。
### 实际发生了什么？
由于npm安装依赖出现报错，导致npm start报错。
### 部署相关信息
Centos 6 x86_64 bbr

### 额外信息（日志、报错等）
```
npm ERR!  npm ERR! Additional logging details can be found in: npm ERR!     /root/RSSHub/npm-debug.log npm ERR! not ok code 0
```
运行时候报错这个，本地windows环境下跑是好的。
```
# npm start

> rsshub@0.0.1 start /root/RSSHub
> node index.js


/root/RSSHub/index.js:27
process.on('uncaughtException', (e) => {
                                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by SettingDust** [comment]
@cooper1x 请提供Node版本

**Comment by cooper1x** [comment]
@SettingDust 
v0.10.48

**Comment by SettingDust** [comment]
@cooper1x 你去更新下node试试

**Comment by cooper1x** [comment]
@SettingDust 好的，这个问题我刚刚解决了，centos的源比较旧。
另外想问下，npm安装的依赖文件夹在哪呢，没有看到node_modules这个目录。
