### ISSUE TITLE
容器化运行报错 Error: Cannot find module './build/Release/re2'

### ISSUE THREAD

**Issue by bmcswrdd5977** [DIYgod/RSSHub#12531]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

NOROUTE

### 预期是什么？

正常运行

### 实际发生了什么？

在k8s中运行报错，Error: Cannot find module './build/Release/re2'
在此之前都正常，从昨天下午开始（在此期间未更新任何配置）

### 部署

自建

### 额外信息

```shell
Error: Cannot find module './build/Release/re2'
Require stack:
- /app/node_modules/re2/re2.js
- /app/lib/middleware/parameter.js
- /app/lib/app.js
- /app/lib/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._resolveFilename (/app/node_modules/module-alias/index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/node_modules/re2/re2.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/re2/re2.js',
    '/app/lib/middleware/parameter.js',
    '/app/lib/app.js',
    '/app/lib/index.js'
  ]
}
Node.js v18.16.0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Docker image version?
