### ISSUE TITLE
Docker Compose 部署访问 502

### ISSUE THREAD

**Issue by Sliots-SZU** [DIYgod/RSSHub#12679]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/install/#docker-compose-bu-shu

### 预期是什么？

200 OK

### 实际发生了什么？

502

### 部署

自建

### 部署相关信息

OS: Linux, Node:v18.16.0 Docker: v24.0.2

### 额外信息

使用的配置文件为 [RSSHub/docker-compose.yml at master · DIYgod/RSSHub · GitHub](https://github.com/DIYgod/RSSHub/blob/master/docker-compose.yml)
此前部署正常，更新至最新镜像后报错

```shell
Node.js v18.16.0
> rsshub@1.0.0 start
> node lib/index.js
node:internal/fs/utils:347
    throw err;
    ^
Error: ENOENT: no such file or directory, open '/app/node_modules/.pnpm/@tonyrl+rand-user-agent@2.0.17/node_modules/@tonyrl/rand-user-agent/data/user-agents.json'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at Object.<anonymous> (/app/node_modules/.pnpm/@tonyrl+rand-user-agent@2.0.17/node_modules/@tonyrl/rand-user-agent/dist/index.cjs:92:6)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/app/lib/utils/rand-user-agent.js:1:27) {
      
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/app/node_modules/.pnpm/@tonyrl+rand-user-agent@2.0.17/node_modules/@tonyrl/rand-user-agent/data/user-agents.json'
}
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Please update the docker image again. 
```bash
docker compose down
docker pull diygod/rsshub
docker-compose up -d
```
