### ISSUE TITLE
twitter 自建在老板限制阅览条数后一直报错 TypeError: Cannot read properties of undefined (reading 'user')

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#12855]
### 路由地址

```routes
/twitter/user/:id/:routeParams?
```

### 完整路由地址

```fullroutes
twitter/user/Liyu0109.json
```

### 相关文档

https://docs.rsshub.app/social-media.html#twitter

### 预期是什么？

正常返回结果

### 实际发生了什么？

Error message: TypeError: Cannot read properties of undefined (reading 'user')
    at getUser (/RSSHub/lib/v2/twitter/web-api/twitter-api.js:247:74)
    at runMicrotasks ()
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/RSSHub/lib/v2/twitter/web-api/user.js:12:22)
    at async module.exports (/RSSHub/lib/v2/twitter/api_fallback_common.js:16:5)
    at async /RSSHub/node_modules/koa-mount/index.js:58:5
    at async /RSSHub/node_modules/koa-mount/index.js:52:26
    at async /RSSHub/node_modules/koa-mount/index.js:52:26
    at async /RSSHub/lib/middleware/load-on-demand.js:29:9
    at async /RSSHub/lib/middleware/cache/index.js:122:13
Helpful Information to provide when opening issue:
Path: /user/Liyu0109.json
Node version: v16.20.1

### 部署

自建

### 部署相关信息

Node version: v16.20.1  npm 8.19.4

### 额外信息

```shell
Error message: TypeError: Cannot read properties of undefined (reading 'user')
    at getUser (/RSSHub/lib/v2/twitter/web-api/twitter-api.js:247:74)
    at runMicrotasks ()
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/RSSHub/lib/v2/twitter/web-api/user.js:12:22)
    at async module.exports (/RSSHub/lib/v2/twitter/api_fallback_common.js:16:5)
    at async /RSSHub/node_modules/koa-mount/index.js:58:5
    at async /RSSHub/node_modules/koa-mount/index.js:52:26
    at async /RSSHub/node_modules/koa-mount/index.js:52:26
    at async /RSSHub/lib/middleware/load-on-demand.js:29:9
    at async /RSSHub/lib/middleware/cache/index.js:122:13
Helpful Information to provide when opening issue:
Path: /user/Liyu0109.json
Node version: v16.20.1
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by KwToPA** [comment]
rsshub 已经更新到最新版

是不是推特的网页api 变更？

**Comment by Rongronggg9** [comment]
/test

```
/twitter/user/Liyu0109.json
```

**Comment by Rongronggg9** [comment]
/test
```routes
/twitter/user/Liyu0109.json
```

**Comment by DIYgod** [comment]
Unable to reproduce, the issue will be closed.
