### ISSUE TITLE
🔴「哔哩哔哩 UP 投稿」报错：This route is empty

### ISSUE THREAD

**Issue by Thomas-Harrell** [DIYgod/RSSHub#12918]
### 路由地址

```routes
/bilibili/user/video/:uid/:disableEmbed?
```

### 完整路由地址

```fullroutes
/bilibili/user/video/25876945
```

### 相关文档

https://docs.rsshub.app/social-media.html#bilibili-up-zhu-tou-gao

### 预期是什么？

- 能够正常抓取

### 实际发生了什么？

- [https://rsshub.app/bilibili/user/video/2267573](https://rsshub.app/bilibili/user/video/2267573)

- 官方和自建均出现报错

- Error message: this route is empty

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Looks like something went wrong

Route requested: /bilibili/user/video/2267573
Error message: this route is empty, please check the original site or [create an issue](https://github.com/DIYgod/RSSHub/issues/new/choose)

Helpful Information to provide when opening issue:
Path: /bilibili/user/video/2267573
Node version: v18.17.0
Git Hash: 31a59fd
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by bigcoder84** [comment]
本地测试已通过，已提交PR，#12920

**Comment by bigcoder84** [comment]
报错信息如下：
```txt
For help, see: https://nodejs.org/en/docs/inspector
info: Listening Port 1200
info: 🎉 RSSHub start! Cheers!
info: 💖 Can you help keep this open source project alive? Please sponsor 👉 https://docs.rsshub.app/en/support
info: /bilibili/user/video/521249172, user IP: ::ffff:127.0.0.1
error: Error in /user/video/521249172: TypeError: Cannot read properties of undefined (reading 'map')
    at E:\open-source\RSSHub\lib\v2\bilibili\cache.js:16:51
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.tryGet (E:\open-source\RSSHub\lib\middleware\cache\index.js:64:21)
    at async module.exports (E:\open-source\RSSHub\lib\v2\bilibili\video.js:8:20)
    at async E:\open-source\RSSHub\node_modules\koa-mount\index.js:58:5
    at async E:\open-source\RSSHub\node_modules\koa-mount\index.js:52:26
    at async E:\open-source\RSSHub\lib\middleware\load-on-demand.js:29:9
    at async E:\open-source\RSSHub\lib\middleware\cache\index.js:122:13
    at async E:\open-source\RSSHub\node_modules\koa-mount\index.js:52:26
    at async module.exports (E:\open-source\RSSHub\lib\middleware\parameter.js:27:5)
```
```
