### ISSUE TITLE
Vercel Deployment failed

### ISSUE THREAD

**Issue by haroldrandom** [DIYgod/RSSHub#12954]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://rssh-ub-git-dependabot-npmandyarnprettier-301-haroldrandom.vercel.app

### 预期是什么？

Vercel deployment success.

### 实际发生了什么？

Failed to auto build a deployment on Vercel while bumping prettier-3.0.1.

### 部署

自建

### 部署相关信息

https://rssh-ub-git-dependabot-npmandyarnprettier-301-haroldrandom.vercel.app

### 额外信息

```shell
[05:24:38.330] Running build in Cleveland, USA (East) – cle1
[05:24:38.388] Cloning github.com/haroldrandom/RSSHub (Branch: dependabot/npm_and_yarn/prettier-3.0.1, Commit: 9aa154f)
[05:24:39.404] Cloning completed: 1.015s
[05:24:45.189] Restored build cache
[05:24:45.253] Running "vercel build"
[05:24:45.724] Vercel CLI 31.2.2
[05:24:46.876] Warning: Detected "engines": { "node": ">=16" } in your `package.json` that will automatically upgrade when a new major Node.js Version is released. Learn More: http://vercel.link/node-version
[05:24:46.900] Installing dependencies...
[05:24:46.901] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8...
[05:24:47.483] Lockfile is up to date, resolution step is skipped
[05:24:47.545] Progress: resolved 1, reused 0, downloaded 0, added 0
[05:24:47.624] Packages: +7 -6
[05:24:47.624] +++++++------
[05:24:47.706]  ERROR  Command failed with exit code 128: /usr/bin/git clone git@github.com:postlight/difflib.js.git /vercel/.local/share/pnpm/store/v3/tmp/_tmp_134_e8aed355d4e292933c7320082d94ede5
[05:24:47.706] Cloning into '/vercel/.local/share/pnpm/store/v3/tmp/_tmp_134_e8aed355d4e292933c7320082d94ede5'...
[05:24:47.706] Host key verification failed.
[05:24:47.706] fatal: Could not read from remote repository.
[05:24:47.706] 
[05:24:47.706] Please make sure you have the correct access rights
[05:24:47.706] and the repository exists.
[05:24:47.706] 
[05:24:47.707] pnpm: Command failed with exit code 128: /usr/bin/git clone git@github.com:postlight/difflib.js.git /vercel/.local/share/pnpm/store/v3/tmp/_tmp_134_e8aed355d4e292933c7320082d94ede5
[05:24:47.707] Cloning into '/vercel/.local/share/pnpm/store/v3/tmp/_tmp_134_e8aed355d4e292933c7320082d94ede5'...
[05:24:47.707] Host key verification failed.
[05:24:47.707] fatal: Could not read from remote repository.
[05:24:47.707] 
[05:24:47.707] Please make sure you have the correct access rights
[05:24:47.707] and the repository exists.
[05:24:47.707]     at makeError (/pnpm8/node_modules/pnpm/dist/pnpm.cjs:24890:17)
[05:24:47.707]     at handlePromise (/pnpm8/node_modules/pnpm/dist/pnpm.cjs:25461:33)
[05:24:47.707]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[05:24:47.707]     at async gitFetcher (/pnpm8/node_modules/pnpm/dist/pnpm.cjs:113578:11)
[05:24:47.707]     at async fetcher (/pnpm8/node_modules/pnpm/dist/pnpm.cjs:126087:16)
[05:24:47.707]     at async run (/pnpm8/node_modules/pnpm/dist/pnpm.cjs:125494:23)
[05:24:47.750] Error: Command "pnpm install" exited with 1


https://rssh-ub-git-dependabot-npmandyarnprettier-301-haroldrandom.vercel.app
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
It looks like there was an issue on the GitHub/Vercel side. The log only shows that Vercel's builder failed to clone https://github.com/postlight/difflib.js. There's nothing wrong with Prettier.

You can try building it again
