### ISSUE TITLE
东南大学两个源失效

### ISSUE THREAD

**Issue by Sciroccogti** [DIYgod/RSSHub#1316]
### `/universities/seu/radio/academic` and `/universities/seu/cse/:type?`
[信息科学与工程学院学术活动](https://rsshub.app/seu/radio/academic)

[东南大学计算机技术与工程学院](https://rsshub.app/seu/cse/xyxw)

### Additional info (logs errors etc)
```
TypeError: Cannot read property 'replace' of null
    at Promise.all.list.map (/app/routes/universities/seu/radio/academic.js:37:21)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

```
Error: getaddrinfo EAI_AGAIN cse.seu.edu.cn cse.seu.edu.cn:80
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
```

### Possible Causes
东南大学最近进行了一系列服务器和网站的更新

**Comment by LogicJake** [comment]
计算机学院那个看报错应该是DNS问题，我本地run没问题。

**Comment by lengthmin** [comment]
请问dns问题是如何解决的？
