### ISSUE TITLE
路由正则匹配错误

### ISSUE THREAD

**Issue by Joeycz** [DIYgod/RSSHub#1326]
ERROR in ./docs/.vuepress/components/RouteEn.vue?vue&type=template&id=520d49d3& (./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/vuepress/node_modules/.cache/vuepress","cacheIdentifier":"18759c20-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./docs/.vuepress/components/RouteEn.vue?vue&type=template&id=520d49d3&)
Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
SyntaxError: Error parsing regular expression: Invalid regular expression: /(?<=:).*?(?=\/|$)/: Invalid group (1:591)
    at Parser.pp$4.raise (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:2610:13)
    at tryCreateRegexp (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:3269:46)
    at Parser.pp$8.readRegexp (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:3330:5)
    at Parser.pp$8.readToken_slash (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:3103:51)
    at Parser.pp$8.getTokenFromCode (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:3228:17)
    at Parser.pp$8.readToken (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:2975:15)
    at Parser.readToken (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:4398:22)
    at Parser.pp$8.nextToken (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:2966:15)
    at Parser.pp$8.next (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:2923:8)
    at Parser.pp.eat (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:569:10)
    at Parser.pp$3.parseSubscripts (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:1979:35)
    at Parser.pp$3.parseExprSubscripts (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:1958:21)
    at Parser.pp$3.parseMaybeUnary (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:1932:17)
    at Parser.pp$3.parseExprOps (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:1874:19)
    at Parser.pp$3.parseMaybeConditional (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:1857:19)
    at Parser.pp$3.parseMaybeAssign (/Users/chengzheng/chengzheng/czhub/node_modules/vue-template-es2015-compiler/buble.js:1832:19)
 @ ./docs/.vuepress/components/RouteEn.vue?vue&type=template&id=520d49d3& 1:0-410 1:0-410
 @ ./docs/.vuepress/components/RouteEn.vue
 @ ./node_modules/vuepress/lib/app/.temp/routes.js
 @ ./node_modules/vuepress/lib/app/app.js
 @ ./node_modules/vuepress/lib/app/clientEntry.js
 @ multi ./node_modules/vuepress/lib/app/clientEntry.js

**Comment by DIYgod** [comment]
不知道你在说什么，issue 将被关闭
