### ISSUE TITLE
Picuki

### ISSUE THREAD

**Issue by bl4ckswat** [DIYgod/RSSHub#13643]
### Routes

```routes
/picuki/profile/:id/:functionalFlag?
```

### Full routes

```fullroutes
/picuki/profile/stefaniejoosten
```

### Related documentation

https://docs.rsshub.app/routes/social-media#picuki-user-profile

### What is expected?

working fetch data

### What is actually happening?

Error message: this route is empty

### Deployment information

RSSHub demo (https://rsshub.app)

### Additional info

```shell
Helpful Information to provide when opening issue:
Path: /picuki/profile/stefaniejoosten
Node version: v18.18.2
Git Hash: b4ad158
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
/test
```routes
/picuki/profile/stefaniejoosten
```

**Comment by bl4ckswat** [comment]
> Successfully [generated](https://github.com/DIYgod/RSSHub/actions/runs/6666293822) as following:
> 
> http://localhost:1200/picuki/profile/stefaniejoosten - Success ✔️

Error message: Error: Cannot find module 'cosmiconfig'

**Comment by bl4ckswat** [comment]
> /test
> 
> ```
> /picuki/profile/stefaniejoosten
> ```

Route requested: /profile/stefaniejoosten
Error message: Error: Cannot find module 'cosmiconfig'
Require stack:
- C:\Users\uSeR\RSSHub\node_modules\puppeteer\lib\cjs\puppeteer\getConfiguration.js
- C:\Users\uSeR\RSSHub\node_modules\puppeteer\lib\cjs\puppeteer\puppeteer.js
- C:\Users\uSeR\RSSHub\lib\utils\puppeteer.js
- C:\Users\uSeR\RSSHub\lib\v2\picuki\profile.js
- C:\Users\uSeR\RSSHub\lib\v2\picuki\router.js
- C:\Users\uSeR\RSSHub\node_modules\require-all\index.js
- C:\Users\uSeR\RSSHub\lib\v2router.js
- C:\Users\uSeR\RSSHub\lib\middleware\load-on-demand.js
- C:\Users\uSeR\RSSHub\lib\app.js
- C:\Users\uSeR\RSSHub\lib\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._resolveFilename (C:\Users\uSeR\RSSHub\node_modules\module-alias\index.js:49:29)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object. (C:\Users\uSeR\RSSHub\node_modules\puppeteer\lib\cjs\puppeteer\getConfiguration.js:21:23)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
Helpful Information to provide when opening issue:
Path: /profile/stefaniejoosten
Node version: v18.12.1
Git Hash: 257973a
