### ISSUE TITLE
微博热搜榜报错

### ISSUE THREAD

**Issue by conanjunn** [DIYgod/RSSHub#1380]
### 路由地址
/weibo/search/hot

### 预期是什么？
返回weibo热搜

### 实际发生了什么？
大部分情况是报错（报错信息见下文）

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
```
RSSHub 发生了一些意外:
Error: Request failed with status code 418
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:193:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by qwe7002** [comment]
返回了418，看起来像是服务器拒绝了这个请求（418的意思是我是一个茶壶）

**Comment by DIYgod** [comment]
@qwe7002 微博反爬，建议自建

**Comment by conanjunn** [comment]
ok！3q
