### ISSUE TITLE
Reuters无法获取全文

### ISSUE THREAD

**Issue by dzx-dzx** [DIYgod/RSSHub#14034]
### 路由地址

```routes
/reuters/:category/:topic?
```

### 完整路由地址

```fullroutes
/reuters/world
```

### 相关文档

https://docs.rsshub.app/routes/traditional-media#reuters-lu-tou-she-category-topic-author

### 预期是什么？

正常获取

### 实际发生了什么？

无法获取

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error message: Error: this route is empty, please check the original site or create an issue
    at module.exports (***RSSHub\lib\middleware\parameter.js:59:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (***RSSHub\lib\middleware\anti-hotlink.js:99:5)
    at async module.exports (***RSSHub\lib\middleware\template.js:15:5)
    at async ***RSSHub\lib\middleware\api-response-handler.js:143:9
    at async module.exports (***RSSHub\lib\middleware\api-template.js:2:5)
    at async module.exports (***RSSHub\lib\middleware\utf8.js:4:5)
    at async module.exports (***RSSHub\lib\middleware\header.js:21:5)
    at async module.exports (***RSSHub\lib\middleware\debug.js:9:5)
    at async grant (***RSSHub\lib\middleware\access-control.js:24:13)

Helpful Information to provide when opening issue:
Path: /reuters/reuters/world
Node version: v18.17.0
Git Hash: c12a265
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by 1amfine2333** [comment]
能否参考下这个https://github.com/RSS-Bridge/rss-bridge/blob/master/bridges/ReutersBridge.php ，我看RSS-Bridge是可以获得到包含全文的
> https://rss-bridge.org/bridge01/?action=display&bridge=ReutersBridge&feed=china&format=Html
<img width="1365" alt="image" src="https://github.com/DIYgod/RSSHub/assets/24676292/2a4d22d5-dc23-41e2-a7f4-61183ea66084">
