### ISSUE TITLE
Failed to run `npm run format`

### ISSUE THREAD

**Issue by CoderSherlock** [DIYgod/RSSHub#14157]
### Routes

```routes
N/A
```

### Full routes

```fullroutes
N/A
```

### Related documentation

https://docs.rsshub.app/zh/joinus/new-rss/add-docs#%E5%85%B6%E4%BB%96%E4%BA%8B%E9%A1%B9

### What is expected?

Format should success

### What is actually happening?

Failed on both `npm run format` and `node website/docs/.format/format.mjs --staged`

```
$ node website/docs/.format/format.mjs --staged
file:///home/coder/share/RSSHub/website/node_modules/mdast-util-mdx-jsx/lib/index.js:162
    if (!this.data.mdxJsxTagStack) this.data.mdxJsxTagStack = []
                   ^

TypeError: Cannot read properties of undefined (reading 'mdxJsxTagStack')
    at Object.enterMdxJsxTag (file:///home/coder/share/RSSHub/website/node_modules/mdast-util-mdx-jsx/lib/index.js:162:20)
    at compile (file:///home/coder/share/RSSHub/node_modules/remark/node_modules/mdast-util-from-markdown/lib/index.js:352:40)
    at fromMarkdown (file:///home/coder/share/RSSHub/node_modules/remark/node_modules/mdast-util-from-markdown/lib/index.js:187:29)
    at parser (file:///home/coder/share/RSSHub/node_modules/remark/node_modules/remark-parse/lib/index.js:18:12)
    at Function.parse (file:///home/coder/share/RSSHub/node_modules/remark/node_modules/unified/lib/index.js:273:12)
    at executor (file:///home/coder/share/RSSHub/node_modules/remark/node_modules/unified/lib/index.js:393:31)
    at new Promise (<anonymous>)
    at Function.process (file:///home/coder/share/RSSHub/node_modules/remark/node_modules/unified/lib/index.js:380:14)
    at Object.handler (file:///home/coder/share/RSSHub/website/docs/.format/routeFormat.mjs:46:14)
    at async file:///home/coder/share/RSSHub/website/docs/.format/format.mjs:126:25

Node.js v20.10.0
```

### Deployment information

Self-hosted

### Additional info

```shell
This also happened to a clean HEAD of the master (66844b055e686814635ab67b8aee4c0b35550acd).
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by TonyRL** [comment]
Please remove `node_module` folder and  rerun `pnpm i` inside `website` directory.

**Comment by CoderSherlock** [comment]
Using pnpm works. Stange that npm doesn't work.

```
$ npm -v        
10.2.3
$ pnpm -v     
8.14.0
```
