### ISSUE TITLE
RSSHub 微博接口报错

### ISSUE THREAD

**Issue by chaselen** [DIYgod/RSSHub#1427]
### 路由地址
/weibo/user/:uid
### 预期是什么？
正常返回微博列表

### 实际发生了什么？
发生异常
```
Error: Request failed with status code 418
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:193:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
RSSHub 发生了一些意外: 
```

**Comment by imlonghao** [comment]
微博反爬，建议自建

**Comment by hnliyuan** [comment]
你好，自建的意思是自己部署吗？ 我部署在腾讯云，前段时间可以，但是今天又爆418了。
