### ISSUE TITLE
本地添加路由，显示路由为空

### ISSUE THREAD

**Issue by MuenYu** [DIYgod/RSSHub#14338]
### 路由地址

```routes
/:lang?/about
```

### 完整路由地址

```fullroutes
/zh-cn/about
```

### 相关文档

https://docs.rsshub.app/joinus/new-rss/before-start
https://docs.rsshub.app/joinus/new-radar#source

### 预期是什么？

显示自定义的 state 信息，并控制台打印 ctx.params.lang。

/lib/v2/mashiro/router.js
```js
module.exports = (router) => {
    router.get('/:lang?/about', require('./about'));
};
```

/lib/v2/mashiro/about.js
```js
const got = require('@/utils/got'); // a customised got
const cheerio = require('cheerio'); // an HTML parser with a jQuery-like API
const { parseDate } = require('@/utils/parse-date');

module.exports = async (ctx) => {
    const baseUrl = 'https://mashiro.best';
    const lang = ctx.params.lang;

    console.log(lang); // 期望被打印的字符串

    ctx.state.data = {
        // Your RSS output here
        title: `mashiro about me`,
        link: `${baseUrl}/${lang}/about`,
        item: null,
    };
};
```

/lib/v2/mashiro/radar.js
```js
module.exports = {
    'mashiro.best': {
        _name: 'Mashiro',
        '.': [
            {
                title: '仓库 Issues',
                docs: 'https://docs.rsshub.app/routes/programming#github',
                source: ['/:lang?/about', '/about'],
                target: (params) => `/mashiro/${params.lang}/about`,
            },
        ],
    },
};
```

### 实际发生了什么？

![image](https://github.com/DIYgod/RSSHub/assets/22992947/af8e13be-d51b-44ec-bed9-212d227ffadb)

### 部署

自建

### 部署相关信息

OS: Windows 10, Node version: v20.11.0, Git Hash: 7412e9e

### 额外信息

```shell
info: /mashiro/about, user IP: ::ffff:127.0.0.1
error: Error in /mashiro/about: Error: this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create 
an issue</a>                                                                                                                                                      an issue</a>
    at module.exports (D:\projects\RSSHub\lib\middleware\parameter.js:60:19)
    at async module.exports (D:\projects\RSSHub\lib\middleware\anti-hotlink.js:99:5)
    at async module.exports (D:\projects\RSSHub\lib\middleware\template.js:15:5)
    at async D:\projects\RSSHub\lib\middleware\api-response-handler.js:143:9
    at async module.exports (D:\projects\RSSHub\lib\middleware\api-template.js:2:5)
    at async module.exports (D:\projects\RSSHub\lib\middleware\utf8.js:4:5)
    at async module.exports (D:\projects\RSSHub\lib\middleware\header.js:21:5)
    at async module.exports (D:\projects\RSSHub\lib\middleware\debug.js:9:5)
    at async grant (D:\projects\RSSHub\lib\middleware\access-control.js:45:13)
    at async module.exports (D:\projects\RSSHub\lib\middleware\onerror.js:30:9)
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by MuenYu** [comment]
说明：仅本地测试，发现向 v2 文件夹添加路由后，本地无法加载相关路由。

**Comment by MuenYu** [comment]
问题本身就是路由无法匹配，所以为避免问题被 close，使用 `NOROUTE`

**Comment by JimenezLi** [comment]
ctx.state.data 的 item 为 null，所以会报 this route is empty 错误
另外为什么要在控制台输出字符串
