### ISSUE TITLE
lofter tag 失效，重定向到登录页

### ISSUE THREAD

**Issue by JimenezLi** [DIYgod/RSSHub#14438]
### 路由地址

```routes
/lofter/tag/:name?/:type?
```

### 完整路由地址

```fullroutes
/lofter/tag/neuro
```

### 相关文档

https://docs.rsshub.app/zh/routes/social-media#lofter

### 预期是什么？

返回 tag 内容

### 实际发生了什么？

提示 this route is empty，看日志是重定向到了登录页面

经过测试，lofter tag 页面在未登录时用浏览器直接访问也会重定向到登录页面，可能需要 Cookie

### 部署

自建

### 部署相关信息

OS: Windows, Node: v18.16.1

### 额外信息

```shell
[2024-02-09 22:32:07.589] info: /lofter/tag/neuro, user IP: ::1
[2024-02-09 22:32:07.614] http: Proxy for https://www.lofter.com/tag/neuro/new
[2024-02-09 22:32:08.141] http: Redirecting to https://www.lofter.com/front/login for https://www.lofter.com/tag/neuro/new
[2024-02-09 22:32:08.142] http: Proxy for https://www.lofter.com/front/login
[2024-02-09 22:32:09.501] error: Error in /lofter/lofter/tag/neuro: Error: this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create an issue</a>
    at module.exports (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\parameter.js:60:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\anti-hotlink.js:99:5)
    at async module.exports (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\template.js:15:5)
    at async D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\api-response-handler.js:143:9
    at async module.exports (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\api-template.js:2:5)
    at async module.exports (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\utf8.js:4:5)
    at async module.exports (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\header.js:21:5)
    at async module.exports (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\debug.js:9:5)
    at async grant (D:\SystemDefault\Documents\code\GitProjects\RSSHub\lib\middleware\access-control.js:45:13)
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by LucunJi** [comment]
简单测了一下发现需要 LOFTER_SESS 这个 cookie
