### ISSUE TITLE
手动部署报错

### ISSUE THREAD

**Issue by cnkmmk** [DIYgod/RSSHub#14561]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

NO

### 预期是什么？

手动部署完成

### 实际发生了什么？

手动在debian 下进行部署，无法按照部署文档完成。

```
root@Rsshub:/opt/RSSHub-master# node -v
v21.6.2
root@Rsshub:/opt/RSSHub-master# npm -v
10.2.4
root@Rsshub:/opt/RSSHub-master# yarn -v
1.22.21
root@Rsshub:/opt/RSSHub-master# yarn install
yarn install v1.22.21
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
⠁ (node:1174) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
warning @postlight/parser > @babel/runtime-corejs2 > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
warning @postlight/parser > postman-request > har-validator@5.1.5: this library is no longer supported
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### 部署

自建

### 额外信息

```shell
root@Rsshub:/opt/RSSHub-master# yarn install
yarn install v1.22.21
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
⠁ (node:1174) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
warning @postlight/parser > @babel/runtime-corejs2 > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
warning @postlight/parser > postman-request > har-validator@5.1.5: this library is no longer supported
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by cnkmmk** [comment]
使用 pnpm 也无法安装

```
root@Rsshub:/opt/RSSHub-master# node -v
v20.11.1
root@Rsshub:/opt/RSSHub-master# pnpm -v
8.15.4
root@Rsshub:/opt/RSSHub-master# pnpm install
Lockfile is up to date, resolution step is skipped
Packages: +1305
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1305, reused 1305, downloaded 0, added 1305, done
node_modules/.pnpm/core-js@2.6.12/node_modules/core-js: Running postinstall script, done in 573ms
node_modules/.pnpm/puppeteer@22.2.0/node_modules/puppeteer: Running postinstall script, failed in 7.1s
.../node_modules/puppeteer postinstall$ node install.mjs
│ Error: ERROR: Failed to set up Chrome v122.0.6261.57! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
│     at file:///opt/RSSHub-master/node_modules/.pnpm/puppeteer@22.2.0/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:58:23
│     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
│     at async Promise.all (index 0)
│     at async downloadBrowser (file:///opt/RSSHub-master/node_modules/.pnpm/puppeteer@22.2.0/node_modules/puppeteer/lib/esm/puppeteer/node/install.js:90:9) {
│   [cause]: Error: connect ECONNREFUSED 0.0.0.0:443
│       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1595:16) {
│     errno: -111,
│     code: 'ECONNREFUSED',
│     syscall: 'connect',
│     address: '0.0.0.0',
│     port: 443
│   }
│ }
└─ Failed in 7.1s at /opt/RSSHub-master/node_modules/.pnpm/puppeteer@22.2.0/node_modules/puppeteer
 ELIFECYCLE  Command failed with exit code 1.
root@Rsshub:/opt/RSSHub-master#
```
