### ISSUE TITLE
Vercel部署失败，主页500错误

### ISSUE THREAD

**Issue by mapxn** [DIYgod/RSSHub#14622]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/install#deploy-to-vercel-zeit-now

### 预期是什么？

在Vercel 正常部署

### 实际发生了什么？

按照说明文档在Vercel部署RSSHub，不管是一键部署还是先fork后手动部署，均报500错误。

<img width="808" alt="image" src="https://github.com/DIYgod/RSSHub/assets/16299874/63db4b08-e0fa-4e87-af6a-2e2961194cfc">

### 部署

RSSHub 演示 (https://rsshub.app)

### 部署相关信息

platform:Vercel，Node.js 18.x

### 额外信息

```shell
/var/task/lib/config.js:1
import 'dotenv/config';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1274:20)
    at Module._compile (node:internal/modules/cjs/loader:1320:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.exports.b (/opt/node-bridge/chunk-5UAC7W5H.js:1:1142)
    at /opt/node-bridge/bridge-server-BGIDXK2J.js:1:1443
    at Function.Re (/opt/node-bridge/bridge-server-BGIDXK2J.js:1:1809)
    at Function.e.<computed>.L._load (/opt/node-bridge/bridge-server-BGIDXK2J.js:1:1413)
INIT_REPORT Init Duration: 342.28 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Error: Runtime exited with error: exit status 1
Runtime.ExitError

```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by maxhuangping** [comment]
同样报错

**Comment by nanvon** [comment]
昨天拉取最新代码后同样报错

**Comment by clacknya** [comment]
回退旧版本吧

**Comment by Vinfall** [comment]
似乎不是 `import 'dotenv/config';`的问题，git blame显示这个commit已经是一月份的事了 https://github.com/DIYgod/RSSHub/blame/master/lib/config.ts#L1 ，而 Vercel 部署失败应该就最近一星期。

测试下来 Vercel 上确定能正常使用的是 29276d8。

**Comment by cnkmmk** [comment]
更新到最新的commit，还是报 500: INTERNAL_SERVER_ERROR

**Comment by chejg** [comment]
除了回退旧版本，有没有其他什么方法？我已经重新部署了，回退不了了。

**Comment by clacknya** [comment]
> 除了回退旧版本，有没有其他什么方法？我已经重新部署了，回退不了了。

可以回退。把你的 repo 重新 checkout 或者 reset

**Comment by chejg** [comment]
> > 除了回退旧版本，有没有其他什么方法？我已经重新部署了，回退不了了。
> 
> 可以回退。把你的 repo 重新 checkout 或者 reset

我是把vercel里的project删了，然后重新部署了一下，其他的信息都没了。

**Comment by clacknya** [comment]
> > > 除了回退旧版本，有没有其他什么方法？我已经重新部署了，回退不了了。
> > 
> > 
> > 可以回退。把你的 repo 重新 checkout 或者 reset
> 
> 我是把vercel里的project删了，然后重新部署了一下，其他的信息都没了。

建议先学习下 git 使用，可以自定义部署。（作者搞更新也不新建个分支……）

**Comment by liyishuai** [comment]
在 Deployments 页面，展开右上角“…”菜单，点击“Create Deployment”，输入自己分叉中的commit链接，例如
`https://github.com/DIYgod/RSSHub/commit/29276d8399ae626d4220e718b3ec7dbe9d22ef90`（将`DIYGod`改为自己的用户名），可创建新的部署。

**Comment by chejg** [comment]
回滚成功了，不过一同步到最新的就又出错了，只能先用着，过段时间再同步试试。多谢。

**Comment by zhenlohuang** [comment]
遇到了一样的错误

**Comment by liyishuai** [comment]
根据DIYgod的文章《[一个六岁开源项目的崩溃与新生](https://diygod.cc/6-year-of-rsshub)》，本项目正在大刀阔斧地重构，期间保持Vercel支援不在最高优先级。
预计Vercel用户得在 29276d8399ae626d4220e718b3ec7dbe9d22ef90 版本停留一阵子（又不是不能用

**Comment by runchard** [comment]
> 预计Vercel用户得在 [29276d8](https://github.com/DIYgod/RSSHub/commit/29276d8399ae626d4220e718b3ec7dbe9d22ef90) 版本停留一阵子（又不是不能用

推荐在 [RSSHub/legacy](https://github.com/DIYgod/RSSHub/tree/legacy) 分支。。

当然更希望赶紧修了，让用户当小白测。

**Comment by la3rence** [comment]
[Hono 框架支持的平台](https://hono.dev/getting-started/vercel)很多，等 Vercel 跑通了，将来 Cloudflare Workers / Deno Deploy 等平台上跑 RSSHub 也大有可能了。

**Comment by maxhuangping** [comment]
![image](https://github.com/DIYgod/RSSHub/assets/34203062/7d84b5f4-baf7-4042-ad49-d2b360eab7fd)

**Comment by People-11** [comment]
<img width="195" alt="Snipaste_2024-03-17_23-32-23" src="https://github.com/DIYgod/RSSHub/assets/41558215/1c60b4f0-53ee-4ab7-892d-c2dbfc931736">

**Comment by jacob2826** [comment]
> > 预计Vercel用户得在 [29276d8](https://github.com/DIYgod/RSSHub/commit/29276d8399ae626d4220e718b3ec7dbe9d22ef90) 版本停留一阵子（又不是不能用
> 
> 推荐在 [RSSHub/legacy](https://github.com/DIYgod/RSSHub/tree/legacy) 分支。。
> 
> 当然更希望赶紧修了，让用户当小白测。

感谢各位的方法，整理了一下操作步骤。

具体操作步骤：
1. 在自己的repo下，查看所有分支，并新建一个分支，如"legacy"（或其他你喜欢的名字），数据源选择[RSSHub/legacy](https://github.com/DIYgod/RSSHub/tree/legacy) 分支。
2. 在vercel中，新建一个"Deployment"，新建方法见 @liyishuai 的回复。此时在新建页面上，就会出现你刚才建好的分支，并选择。
3. 取消勾选"Use project's Ignore Build Step"，否则本次部署会被跳过。
4. 部署完成后，默认是preview环境，需要操作"Promote to Production"，推到生产环境。

**Comment by dzx-dzx** [comment]
现在的最新commit……会自动重定向到官方文档站？

**Comment by Vinfall** [comment]
修复进度可以看关联 PR：https://github.com/DIYgod/RSSHub/pull/14918 
或者 Cloudflare Workers 支持，都差不多：https://github.com/DIYgod/RSSHub/issues/14901 / https://github.com/DIYgod/RSSHub/pull/14917
现在就卡在 `got` 和 NextJS 不兼容这点，需要等待 `got` 依赖被移除。

**Comment by jacob2826** [comment]
> 修复进度可以看关联 PR：#14918 或者 Cloudflare Workers 支持，都差不多：#14901 / #14917 现在就卡在 `got` 和 NextJS 不兼容这点，需要等待 `got` 依赖被移除。

看起来没什么有效进展，全在低优跟进。估计短期很难有变化。

**Comment by machsix** [comment]
为什么我这没有Create Deployment的button。。
![image](https://github.com/DIYgod/RSSHub/assets/28209092/2e5e3021-deef-43d8-9c27-3da3957087dd)

**Comment by Whichbfj28** [comment]
其他人我不知道怎么弄的。但是各位大佬 半中半英 半缩写 半专业的名词。实在没看懂。希望我接下来的方法更适合小白。
【全部修改在github完成】不需要修改vercel！！
1、fork下rsshub。在fork界面中把【Copy the main branch only】这个勾勾取消掉
2、在自己fork后的rsshub中把默认的master修改为【legacy】
3、vercel中正常部署rsshub即可。
![image](https://github.com/user-attachments/assets/a71f44a2-9c0c-4839-bc88-43753b1eaded)

**Comment by cnkmmk** [comment]
> 其他人我不知道怎么弄的。但是各位大佬 半中半英 半缩写 半专业的名词。实在没看懂。希望我接下来的方法更适合小白。 【全部修改在github完成】不需要修改vercel！！ 1、fork下rsshub。在fork界面中把【Copy the main branch only】这个勾勾取消掉 2、在自己fork后的rsshub中把默认的master修改为【legacy】 3、vercel中正常部署rsshub即可。 ![image](https://private-user-images.githubusercontent.com/47915665/348199007-a71f44a2-9c0c-4839-bc88-43753b1eaded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzYyMDAsIm5iZiI6MTcyMDc3NTkwMCwicGF0aCI6Ii80NzkxNTY2NS8zNDgxOTkwMDctYTcxZjQ0YTItOWMwYy00ODM5LWJjODgtNDM3NTNiMWVhZGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA5MTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ODc2ZTE2MzliYzMzYTRkNmM2ZDk2ZmI1ZWI4YTdjYjhjMjk2NmZiYWUzMWYyMGQyMzk5MDJjY2U0OTdiNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aSpo6nxsgkgzWwtSlmglNr_fEh_ROYIWaqujMF5p1oI)

不能部署指的是无法使用新版本部署，老版本一直都可以的。

**Comment by Shiguang-coding** [comment]
亲测有用

**Comment by Deja-vuuu** [comment]
目前解决了么 我看issue被关闭了

**Comment by FireBEAR12138** [comment]
legacy 版本不支持 Twitter 了。现在获取 Twitter 需要 TWITTER_AUTH_TOKEN，这个版本没有。

**Comment by AzureMaples** [comment]
> 其他人我不知道怎么弄的。但是各位大佬 半中半英 半缩写 半专业的名词。实在没看懂。希望我接下来的方法更适合小白。 【全部修改在github完成】不需要修改vercel！！ 1、fork下rsshub。在fork界面中把【Copy the main branch only】这个勾勾取消掉 2、在自己fork后的rsshub中把默认的master修改为【legacy】 3、vercel中正常部署rsshub即可。 ![image](https://private-user-images.githubusercontent.com/47915665/348199007-a71f44a2-9c0c-4839-bc88-43753b1eaded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MjQyOTQsIm5iZiI6MTczMTgyMzk5NCwicGF0aCI6Ii80NzkxNTY2NS8zNDgxOTkwMDctYTcxZjQ0YTItOWMwYy00ODM5LWJjODgtNDM3NTNiMWVhZGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDA2MTMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzODk1NjY3MjM4NTcyMjQ5MDU0MmEwYmJkMjhiYmExNTcyNjk5MzU2Y2FjNmI4MWYzNTEzNzMyYjc0N2UzMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SpZpe1lSflENoi4-UDDxgLqrxH60c5UmiA0VxHKFa04)

亲测可行~

**Comment by 006lp** [comment]
我刚刚vercel(node22.x)部署master分支，报错没有输出目录
```
[EVAL] Warning: Use of `eval` function is strongly discouraged as it poses security risks and may cause issues with minification.
    ╭─[ lib/utils/common-config.ts:10:18 ]
    │
 10 │         result = eval(result);
    │                  ──┬─  
    │                    ╰─── Use of `eval` function here.
────╯
Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.
Learn More: https://vercel.link/missing-public-directory

```

**Comment by WaferToca** [comment]
> 我刚刚vercel(node22.x)部署master分支，报错没有输出目录
> 
> ```
> [EVAL] Warning: Use of `eval` function is strongly discouraged as it poses security risks and may cause issues with minification.
>     ╭─[ lib/utils/common-config.ts:10:18 ]
>     │
>  10 │         result = eval(result);
>     │                  ──┬─  
>     │                    ╰─── Use of `eval` function here.
> ────╯
> Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.
> Learn More: https://vercel.link/missing-public-directory
> ```

是这样的

**Comment by kjasn** [comment]
> 我刚刚vercel(node22.x)部署master分支，报错没有输出目录
> 
> ```
> [EVAL] Warning: Use of `eval` function is strongly discouraged as it poses security risks and may cause issues with minification.
>     ╭─[ lib/utils/common-config.ts:10:18 ]
>     │
>  10 │         result = eval(result);
>     │                  ──┬─  
>     │                    ╰─── Use of `eval` function here.
> ────╯
> Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.
> Learn More: https://vercel.link/missing-public-directory
> ```

在部署的时候，设置 Output Directory 为 `dist` 就可以了
但是部署完还是 `500: INTERNAL_SERVER_ERROR`

**Comment by rxrv** [comment]
> > 我刚刚vercel(node22.x)部署master分支，报错没有输出目录
> > ```
> > [EVAL] Warning: Use of `eval` function is strongly discouraged as it poses security risks and may cause issues with minification.
> >     ╭─[ lib/utils/common-config.ts:10:18 ]
> >     │
> >  10 │         result = eval(result);
> >     │                  ──┬─  
> >     │                    ╰─── Use of `eval` function here.
> > ────╯
> > Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.
> > Learn More: https://vercel.link/missing-public-directory
> > ```
> 
> 在部署的时候，设置 Output Directory 为 `dist` 就可以了 但是部署完还是 `500: INTERNAL_SERVER_ERROR`

same issue here

```
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/var/task/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at <anonymous> (/vercel/path0/api/vercel.ts:1:14)
    at ModuleJob.run (node:internal/modules/esm/module_job:274:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:644:26)
    at async d (/opt/rust/nodejs.js:16:21147)
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
```

**Comment by la3rence** [comment]
用这个：https://github.com/RSSNext/rsshub-vercel

art template 的部分路由目前还有问题（原因未知），我尝试用 jsx 取代 art，感觉是可行的。将来可以把 art template 全部换掉。

~~2025/9/1  Vercel 对 hono 支持发生了变动，短期又不行了(fixed)~~

**Comment by Vinfall** [comment]
提醒：如果之前一直使用legacy分支，迁移到 rsshub-vercel 之后部分订阅始终返回 503，可能是路由失效，但也有可能是路由的路径有变化，需要检查文档。

e.g. [新闻联播](https://docs.rsshub.app/zh/routes/cctv#cctv-site-category-name)：`/xinwenlianbo/index` -> `/cctv/tv/lm/xwlb`

**Comment by Vinfall** [comment]
友情提醒：Vercel 支持已经修复，直接在 master branch 部署即可。

除了上面说的路由路径问题，你可能需要修改这些 Vercel 项目设置才能正常构建：
- Build and Deployment: framework 选 Hono，删除之前设置的 build command/output directory，更新 Node.js 版本到 24.x
- Environment Variables: 在所有环境添加 [corepack](https://vercel.com/docs/builds/configure-a-build#corepack) 相关变量 `ENABLE_EXPERIMENTAL_COREPACK=1`
- Git: 修改 Ignore Build Step

**Comment by maxhuangping** [comment]
> 友情提醒：Vercel 支持已经修复，直接在 master branch 部署即可。
> 
> 除了上面说的路由路径问题，你可能需要修改这些 Vercel 项目设置才能正常构建：
> 
> * Build and Deployment: framework 选 Hono，删除之前设置的 build command/output directory，更新 Node.js 版本到 24.x
> * Environment Variables: 在所有环境添加 [corepack](https://vercel.com/docs/builds/configure-a-build#corepack) 相关变量 `ENABLE_EXPERIMENTAL_COREPACK=1`
> * Git: 修改 Ignore Build Step

老哥~ 这几天更新以后Vercel部署又开始报错了，似乎与ellipsize 在更新到 0.7.0有关，这有报错的log帮忙看一下：
2026-03-25 02:39:21.240 [error] Error [ERR_REQUIRE_ESM]: require() of ES Module /var/task/node_modules/.pnpm/ellipsize@0.7.0/node_modules/ellipsize/src/index.js from /var/task/node_modules/.pnpm/@jocmp+mercury-parser@3.0.6/node_modules/@jocmp/mercury-parser/dist/mercury.js not supported.
Instead change the require of index.js in /var/task/node_modules/.pnpm/@jocmp+mercury-parser@3.0.6/node_modules/@jocmp/mercury-parser/dist/mercury.js to a dynamic import() which is available in all CommonJS modules.
    at /opt/rust/nodejs.js:2:13531
    at Module.pn (/opt/rust/nodejs.js:2:13909)
    at Xe.e.<computed>.Ye._load (/opt/rust/nodejs.js:2:13501)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at a (/opt/rust/bytecode.js:2:1094)
    at Object.<anonymous> (/var/task/node_modules/.pnpm/@jocmp+mercury-parser@3.0.6/node_modules/@jocmp/mercury-parser/dist/mercury.js:38:17)
    at Module.<anonymous> (/opt/rust/bytecode.js:2:1435)
    at A.d._compile (/opt/rust/bytecode.js:2:3186) {
  code: 'ERR_REQUIRE_ESM'
}
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
Error [ERR_REQUIRE_ESM]: require() of ES Module /var/task/node_modules/.pnpm/ellipsize@0.7.0/node_modules/ellipsize/src/index.js from /var/task/node_modules/.pnpm/@jocmp+mercury-parser@3.0.6/node_modules/@jocmp/mercury-parser/dist/mercury.js not supported.
Instead change the require of index.js in /var/task/node_modules/.pnpm/@jocmp+mercury-parser@3.0.6/node_modules/@jocmp/mercury-parser/dist/mercury.js to a dynamic import() which is available in all CommonJS modules.
    at /opt/rust/nodejs.js:2:13531
    at Module.pn (/opt/rust/nodejs.js:2:13909)
    at Xe.e.<computed>.Ye._load (/opt/rust/nodejs.js:2:13501)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at a (/opt/rust/bytecode.js:2:1094)
    at Object.<anonymous> (/var/task/node_modules/.pnpm/@jocmp+mercury-parser@3.0.6/node_modules/@jocmp/mercury-parser/dist/mercury.js:38:17)
    at Module.<anonymous> (/opt/rust/bytecode.js:2:1435)
    at A.d._compile (/opt/rust/bytecode.js:2:3186) {
  code: 'ERR_REQUIRE_ESM'
}
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
