### ISSUE TITLE
Installation problem help wanted 

### ISSUE THREAD

**Issue by AngelPone** [DIYgod/RSSHub#147]
报错信息如下：
```bash
> node index.js

/usr/local/RSSHub/middleware/onerror.js:3
module.exports = async (ctx, next) => {
                       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494
:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/RSSHub/index.js:6:17)

npm ERR! Linux 3.10.0-514.26.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.14.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! RSSHub@0.0.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the RSSHub@0.0.1 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the RSSHub package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs RSSHub
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls RSSHub
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/RSSHub/npm-debug.log
```
系统：Centos7.3
cnpm : 5.3.0
Node ：6.14.0

**Comment by Ir1d** [comment]
升级一下node版本(

**Comment by AngelPone** [comment]
👌Thanks！
