### ISSUE TITLE
Instagram 某博主 RSS 生成失败

### ISSUE THREAD

**Issue by wutea7** [DIYgod/RSSHub#1496]
### 路由地址

https://rsshub.app/instagram/user/whiteblackeverything

### 实际发生了什么？

```
Error: Request failed with status code 429
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:202:15)
    at IncomingMessage.EventEmitter.emit (domain.js:439:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

**Comment by HenryQW** [comment]
429 Too Many Requests，被反爬虫了。所有大站建议自建，demo 无法保证可用性。

**Comment by wutea7** [comment]
> 429 Too Many Requests，被反爬虫了。所有大站建议自建，demo 无法保证可用性。

明白了，谢谢！
