### ISSUE TITLE
部分路由本地测试通过，但是线上出错

### ISSUE THREAD

**Issue by Andiedie** [DIYgod/RSSHub#1499]
### 路由地址
`/readhub/category/daily`
`/readhub/category/topic`
`/jike/topic/553870e8e4b0cafb0a1bef68`
`/jike/topic/55963702e4b0d84d2c30ce6f`

### 预期是什么？
本地测试均通过，正常获取 RSS 内容，无错误

### 实际发生了什么？
`https://rsshub.app/readhub/category/daily` 和 `https://rsshub.app/readhub/category/topic`：
```
RSSHub 发生了一些意外:
TypeError: Cannot read property 'title' of null
    at ctx.state.data.item.ctx.state.data.item.forEach (/app/lib/middleware/parameter.js:12:22)
    at Array.forEach ()
    at module.exports (/app/lib/middleware/parameter.js:11:33)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

`https://rsshub.app/jike/topic/553870e8e4b0cafb0a1bef68` 和 `https://rsshub.app/jike/topic/55963702e4b0d84d2c30ce6f`：
```
RSSHub 发生了一些意外:
TypeError: html.replace is not a function
    at Object.decode (/app/node_modules/he/he.js:232:15)
    at ctx.state.data.item.ctx.state.data.item.forEach (/app/lib/middleware/parameter.js:13:60)
    at Array.forEach ()
    at module.exports (/app/lib/middleware/parameter.js:11:33)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |    macOS 10.14   |
| Node version       |   10.15     |
| if Docker, version |               |

### 额外信息（日志、报错等）
本地版本 Hash：41ac7ebbc242112477cc8104d97326e6d3a137d7

**Comment by HenryQW** [comment]
我本地测试也没通过

**Comment by Andiedie** [comment]
我这边重新 Clone 一次仓库也没有重现问题。

![image](https://user-images.githubusercontent.com/21376471/51988668-3c08e180-24e0-11e9-908b-aa2e0b8625bf.png)

请问你的 Hash 是什么呢？

**Comment by HenryQW** [comment]
我本地开发也用的 redis，触发了这个错误。忘记 await 以及添加缓存寿命参数。
