### ISSUE TITLE
当rss成功启动后，几秒钟内会出现自动关闭的情况

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#1500]
系统：centos 7

npm --version

6.4.1

node --version

v10.15.1

纽约vps，ram 512 MB

成功启动的log
```
> rsshub@0.0.1 start /var/www/RSSHub
> node lib/index.js

warn: pixiv RSS is disabled for lacking config.
warn: Disqus RSS is disabled for lacking config.
warn: Twitter RSS is disabled for lacking config.
warn: Youtube RSS is disabled for lacking config.
warn: Telegram RSS is disabled for lacking config.
warn: GitHub Repos RSS is disabled for lacking config.
info: 🎉 RSSHub start! Cheers!
```

**Comment by HenryQW** [comment]
没有任何报错？

**Comment by KwToPA** [comment]
@HenryQW  自动关闭表现为 local:port突然无法打开，需要重新npm start 后才能开启。
我之后用top查看进程，突然报错 
···
error Command failed with signal "SIGKILL".                                                                                                                                      
···
发现local:port无法打开，估计应该是跟rsshub有关，我试试重装看看

**Comment by KwToPA** [comment]
@HenryQW

重装rsshub后依然有次问题，不过没有报错。
我用
```
npm start >> /var/www/rss_log.txt
```
里面只有rss源及其相关的报错，没有这个软件的报错。

请问应该用什么命令才能查看软件的报错？

**Comment by DIYgod** [comment]
@KwToPA log 都没有谁知道什么原因...

**Comment by KwToPA** [comment]
@DIYgod 不好意思，现在补上log。

清空两个log（error.log和combined.log）之后重新复现bug。本次记录的log如下

error.log
```
{"message":"Request https://www.zhihu.com/api/v4/members/zhihuid_hidden/activities?limit=7 fail, retry attempt #1: Error: Request failed with status code 401","level":"error"}
{"message":"Request https://www.zhihu.com/api/v4/members/zhihuid_hidden/activities?limit=7 fail, retry attempt #2: Error: Request failed with status code 401","level":"error"}
{"message":"Error in /zhihu/people/activities/zhihuid_hidden: Error: Request failed with status code 401\n    at createError (/var/www/RSSHub/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/var/www/RSSHub/node_modules/axios/lib/core/settle.js:18:12)\n    at IncomingMessage.handleStreamEnd (/var/www/RSSHub/node_modules/axios/lib/adapters/http.js:201:11)\n    at IncomingMessage.emit (events.js:194:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:441:20)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","level":"error"}
{"message":"Error in /weibo/user/hidden: TypeError: Cannot read property 'screen_name' of undefined\n    at module.exports (/var/www/RSSHub/lib/routes/weibo/user.js:15:55)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","level":"error"}
{"message":"Request https://www.zhihu.com/api/v4/members/zhihuid_hidden/activities?limit=7 fail, retry attempt #1: Error: Request failed with status code 410","level":"error"}
{"message":"Request https://www.zhihu.com/api/v4/members/zhihuid_hidden/activities?limit=7 fail, retry attempt #2: Error: Request failed with status code 410","level":"error"}
{"message":"Error in /zhihu/people/activities/zhihuid_hidden: Error: Request failed with status code 410\n    at createError (/var/www/RSSHub/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/var/www/RSSHub/node_modules/axios/lib/core/settle.js:18:12)\n    at IncomingMessage.handleStreamEnd (/var/www/RSSHub/node_modules/axios/lib/adapters/http.js:201:11)\n    at IncomingMessage.emit (events.js:194:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:441:20)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","level":"error"}
{"message":"Request https://www.zhihu.com/api/v4/members/zhihuid_hidden/activities?limit=7 fail, retry attempt #1: Error: Request failed with status code 401","level":"error"}
{"message":"Request https://www.zhihu.com/api/v4/members/zhihuid_hidden/activities?limit=7 fail, retry attempt #2: Error: Request failed with status code 401","level":"error"}
{"message":"Error in /zhihu/people/activities/zhihuid_hidden: Error: Request failed with status code 401\n    at createError (/var/www/RSSHub/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/var/www/RSSHub/node_modules/axios/lib/core/settle.js:18:12)\n    at IncomingMessage.handleStreamEnd (/var/www/RSSHub/node_modules/axios/lib/adapters/http.js:201:11)\n    at IncomingMessage.emit (events.js:194:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:441:20)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","level":"error"}
```

combined.log
```
{"message":"pixiv RSS is disabled for lacking config.","level":"warn"}
{"message":"Disqus RSS is disabled for lacking config.","level":"warn"}
{"message":"Twitter RSS is disabled for lacking config.","level":"warn"}
{"message":"Youtube RSS is disabled for lacking config.","level":"warn"}
{"message":"Telegram RSS is disabled for lacking config.","level":"warn"}
{"message":"GitHub Repos RSS is disabled for lacking config.","level":"warn"}
{"message":"🎉 RSSHub start! Cheers!","level":"info"}
{"message":"Listening Port hidden","level":"info"}
{"message":"/zhihu/people/activities/hidden, user IP: ::ffff:vpsIP_hidden","level":"info"}
{"message":"Request https://www.zhihu.com/api/v4/members/hidden/activities?limit=7 fail, retry attempt #1: Error: Request failed with status code 401","level":"error"}
{"message":"Request https://www.zhihu.com/api/v4/members/hidden/activities?limit=7 fail, retry attempt #2: Error: Request failed with status code 401","level":"error"}
{"message":"Error in /zhihu/people/activities/hidden: Error: Request failed with status code 401\n    at createError (/var/www/RSSHub/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/var/www/RSSHub/node_modules/axios/lib/core/settle.js:18:12)\n    at IncomingMessage.handleStreamEnd (/var/www/RSSHub/node_modules/axios/lib/adapters/http.js:201:11)\n    at IncomingMessage.emit (events.js:194:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:441:20)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","level":"error"}
{"message":"/zhihu/people/activities/hidden, user IP: ::ffff:vpsIP_hidden","level":"info"}
{"message":"/weibo/user/hidden, user IP: ::ffff:vpsIP_hidden","level":"info"}
{"message":"/zhihu/people/activities/hidden, user IP: ::ffff:vpsIP_hidden","level":"info"}
{"message":"Error in /weibo/user/hidden: TypeError: Cannot read property 'screen_name' of undefined\n    at module.exports (/var/www/RSSHub/lib/routes/weibo/user.js:15:55)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","level":"error"}
{"message":"Request https://www.zhihu.com/api/v4/members/hidden/activities?limit=7 fail, retry attempt #1: Error: Request failed with status code 410","level":"error"}
{"message":"Request https://www.zhihu.com/api/v4/members/hidden/activities?limit=7 fail, retry attempt #2: Error: Request failed with status code 410","level":"error"}
{"message":"/zhihu/people/activities/hidden, user IP: ::ffff:vpsIP_hidden","level":"info"}
{"message":"Error in /zhihu/people/activities/hidden: Error: Request failed with status code 410\n    at createError (/var/www/RSSHub/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/var/www/RSSHub/node_modules/axios/lib/core/settle.js:18:12)\n    at IncomingMessage.handleStreamEnd (/var/www/RSSHub/node_modules/axios/lib/adapters/http.js:201:11)\n    at IncomingMessage.emit (events.js:194:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:441:20)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","level":"error"}
{"message":"/zhihu/people/activities/hidden, user IP: ::ffff:vpsIP_hidden","level":"info"}
{"message":"Request https://www.zhihu.com/api/v4/members/hidden/activities?limit=7 fail, retry attempt #1: Error: Request failed with status code 401","level":"error"}
{"message":"Request https://www.zhihu.com/api/v4/members/hidden/activities?limit=7 fail, retry attempt #2: Error: Request failed with status code 401","level":"error"}
{"message":"Error in /zhihu/people/activities/hidden: Error: Request failed with status code 401\n    at createError (/var/www/RSSHub/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/var/www/RSSHub/node_modules/axios/lib/core/settle.js:18:12)\n    at IncomingMessage.handleStreamEnd (/var/www/RSSHub/node_modules/axios/lib/adapters/http.js:201:11)\n    at IncomingMessage.emit (events.js:194:15)\n    at IncomingMessage.EventEmitter.emit (domain.js:441:20)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","level":"error"}
{"message":"/zhihu/people/activities/hidden, user IP: ::ffff:vpsIP_hidden","level":"info"}
```

**Comment by HenryQW** [comment]
只发现 401 unauthorized 错误，不影响程序。可以考虑加一个 pm2 监控一下到底出了什么问题

**Comment by KwToPA** [comment]
rsshub昨天持续运行了好几个小时。之后发现又自动关闭了，用pm2监控得到
```
PM2 > App [index:0] exited with code [0] via signal [SIGKILL]                                                            │
PM2 > App [index:0] starting in -fork mode-                                                                              │
PM2 > App [index:0] online                  
```
其余都是路由相关的信息。根据local:port页面中的
运行时间:  
可以推测似乎进行了一次重启。

**Comment by DIYgod** [comment]
你有用到 抖音 多抓鱼 少数派 这几个路由么

**Comment by KwToPA** [comment]
@DIYgod  没有。 我在512M的的机器上还运行了一个脚本，用来录制直播。 这么一说可能跟内存有关。

**Comment by KwToPA** [comment]
但是我停掉那个脚本后，还是会出现rsshub自动关闭。在一台vps只运行rsshub的前提下，昨天连续运行时长，最长有几个小时，最短的只有5分钟左右
