### ISSUE TITLE
微博关键词rss error

### ISSUE THREAD

**Issue by mankaki** [DIYgod/RSSHub#1512]
### 路由地址
/weibo/keyword/:keyword

### 预期是什么？
按关键字搜索微博

### 实际发生了什么？
出错

### 额外信息（日志、报错等）
RSSHub 发生了一些意外:
Error: Request failed with status code 418
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)

**Comment by imlonghao** [comment]
@mankaki 微博反爬建议自建

**Comment by jccode** [comment]
??? 我也发现这个地址挂了?.
