### ISSUE TITLE
ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by dtlnor** [DIYgod/RSSHub#15279]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/deploy/

### 预期是什么？

通过`npm install` `npm start` 可以正常运行

### 实际发生了什么？

能正常install，但不能运行

### 部署

自建

### 部署相关信息

OS: Win10; Node: Node.js v21.3.0, npm: npm@10.4.0

### 额外信息

```shell
> rsshub@1.0.0 start
> cross-env NODE_ENV=production tsx lib/index.ts


node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\Documents\GitHub\RSSHub\assets\build\routes.json' imported from C:\Users\Documents\GitHub\RSSHub\lib\registry.ts
    at finalizeResolution (node:internal/modules/esm/resolve:264:11)
    at moduleResolve (node:internal/modules/esm/resolve:917:10)
    at defaultResolve (node:internal/modules/esm/resolve:1130:11)
    at nextResolve (node:internal/modules/esm/hooks:749:28)
    at d (file:///C:/Users/Documents/GitHub/RSSHub/node_modules/tsx/dist/esm/index.mjs:5:34)
    at O (file:///C:/Users/Documents/GitHub/RSSHub/node_modules/tsx/dist/esm/index.mjs:5:1162)
    at nextResolve (node:internal/modules/esm/hooks:749:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:237:30)
    at MessagePort.handleMessage (node:internal/modules/esm/worker:199:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:822:20) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///C:/Users/Documents/GitHub/RSSHub/assets/build/routes.json'
}

Node.js v21.3.0

```
```


### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by DIYgod** [comment]
Please read the docs: https://docs.rsshub.app/deploy/#manual-deployment
