### ISSUE TITLE
官方站与同HEAD自建站关于知乎路由表现不一致

### ISSUE THREAD

**Issue by dzx-dzx** [DIYgod/RSSHub#15619]
### 路由地址

```routes
/zhihu/question/:questionId/:sortBy?
```

### 完整路由地址

```fullroutes
/zhihu/question/526941332
```

### 相关文档

https://docs.rsshub.app/routes/social-media#%E7%94%A8%E6%88%B7%E6%96%87%E7%AB%A0

### 预期是什么？

表现相同

### 实际发生了什么？

官方站可访问，自建不可

### 部署

自建

### 部署相关信息

Windows, v20.11.1, [3a4d8db2](https://github.com/DIYgod/RSSHub/commit/3a4d8db2)

### 额外信息

```shell
info: <-- GET /zhihu/question/526941332
error: Error in /zhihu/question/526941332: TypeError: TypeError: Cannot read properties of undefined (reading 'set-cookie')
    at <anonymous> (***\RSSHub\lib\routes\zhihu\question.ts:52:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.tryGet (***\RSSHub\lib\utils\cache\index.ts:84:27)
    at Object.handler (***\RSSHub\lib\routes\zhihu\question.ts:43:24)
    at wrapedHandler (***\RSSHub\lib\registry.ts:93:33)
    at async dispatch (file:///***/RSSHub/node_modules/hono/dist/compose.js:29:17)
    at middleware (***\RSSHub\lib\middleware\cache.ts:42:9)
    at async dispatch (file:///***/RSSHub/node_modules/hono/dist/compose.js:29:17)
    at middleware (***\RSSHub\lib\middleware\parameter.ts:65:5)
    at async dispatch (file:///***/RSSHub/node_modules/hono/dist/compose.js:29:17)
    at middleware (***\RSSHub\lib\middleware\anti-hotlink.ts:89:5)
    at async dispatch (file:///***/RSSHub/node_modules/hono/dist/compose.js:29:17)
    at middleware (***\RSSHub\lib\middleware\header.ts:26:5)
    at async dispatch (file:///***/RSSHub/node_modules/hono/dist/compose.js:29:17)
    at middleware (***\RSSHub\lib\middleware\template.tsx:15:5)
    at async dispatch (file:///***/RSSHub/node_modules/hono/dist/compose.js:29:17)
    at middleware (***\RSSHub\lib\middleware\debug.ts:16:5)
    at async dispatch (file:///***/RSSHub/node_modules/hono/dist/compose.js:29:17)
    at middleware (***\RSSHub\lib\middleware\access-control.ts:21:9)
    at async dispatch (file:///***/RSSHub/node_modules/hono/dist/compose.js:29:17)
    at middleware (***\RSSHub\lib\middleware\sentry.ts:18:5)
    at async dispatch (file:///***/RSSHub/node_modules/hono/dist/compose.js:29:17)
    at middleware (***\RSSHub\lib\middleware\logger.ts:35:5)
    at async dispatch (file:///***/RSSHub/node_modules/hono/dist/compose.js:29:17)
    at async dispatch (file:///***/RSSHub/node_modules/hono/dist/compose.js:29:17)
    at async compress2 (file:///***/RSSHub/node_modules/hono/dist/middleware/compress/index.js:5:5)
    at async dispatch (file:///***/RSSHub/node_modules/hono/dist/compose.js:29:17)
    at async trimTrailingSlash2 (file:///***/RSSHub/node_modules/hono/dist/middleware/trailing-slash/index.js:4:5)
info: --> GET /zhihu/question/526941332 503 10s
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by dzx-dzx** [comment]
@TonyRL I'm sorry, why is it closed without any comment?

**Comment by dzx-dzx** [comment]
It...happened again on this 31e2a43a. @TonyRL

**Comment by TonyRL** [comment]
/test
```routes
/zhihu/question/526941332
```
