### ISSUE TITLE
色花堂報錯

### ISSUE THREAD

**Issue by ak502-hk** [DIYgod/RSSHub#15630]
### Routes

```routes
Route requested: /sehuatang/gqzwzm
```

### Full routes

```fullroutes
Error message: Error: this route is empty, please check the original site or create an issue
    at module.exports (/home/ubuntu/RSSHub/lib/middleware/parameter.js:46:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/ubuntu/RSSHub/lib/middleware/anti-hotlink.js:99:5)
    at async module.exports (/home/ubuntu/RSSHub/lib/middleware/template.js:15:5)
    at async /home/ubuntu/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/home/ubuntu/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/home/ubuntu/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/home/ubuntu/RSSHub/lib/middleware/header.js:21:5)
    at async module.exports (/home/ubuntu/RSSHub/lib/middleware/debug.js:9:5)
    at async grant (/home/ubuntu/RSSHub/lib/middleware/access-control.js:24:13)

Helpful Information to provide when opening issue:
Path: /sehuatang/gqzwzm
Node version: v16.16.0
Git Hash: 86d10ae
```

### Related documentation

https://docs.rsshub.app/routes/multimedia#%E8%89%B2%E8%8A%B1%E5%A0%82

### What is expected?

No error

### What is actually happening?

got error today

### Deployment information

Self-hosted

### Additional info

```shell
今天剛剛出錯..會不會是網站改變?
```

### This is not a duplicated issue

- [X] I have searched [existing issues](https://github.com/DIYgod/RSSHub/issues) to ensure this bug has not already been reported

**Comment by Felix2yu** [comment]
### Routes
```
/sehuatang/:subforumid?/:type?
``` 
### Full routes
```
/sehuatang/gqzwzm
```

### Additional info
```
FetchError: [GET] "https://www.sehuatang.net/forum.php?mod=forumdisplay&orderby=dateline&fid=103": 403 Forbidden
```

**Comment by ak502-hk** [comment]
Route requested: /gqzwzm

Error message: Response code 403 (Forbidden): target website might be blocking our access, you can [host your own RSSHub instance](https://docs.rsshub.app/install/) for a better usability.

Helpful Information to provide when opening issue:
Path: /gqzwzm
Node version: v16.16.0
Git Hash: 86d10ae
