### ISSUE TITLE
豆瓣发现的一个栏目抓取出错

### ISSUE THREAD

**Issue by brilon** [DIYgod/RSSHub#1564]
### 路由地址
https://rsshub.app/douban/explore/column/4
### 预期是什么？
正常返回feed内容：
https://www.douban.com/explore/column/4
### 实际发生了什么？
RSSHub 发生了一些意外:
Error: Request failed with status code 404
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
### 额外信息（日志、报错等）

**Comment by brilon** [comment]
@LogicJake 请看下

**Comment by LogicJake** [comment]
@brilon 好的

**Comment by LogicJake** [comment]
这个栏目下有个用户注销，导致他的文章也被删除，但豆瓣依然显示数据
