### ISSUE TITLE
爱思想排行榜 503 出错

### ISSUE THREAD

**Issue by queensferryme** [DIYgod/RSSHub#1607]
### Involved route

`/aisixiang/ranking/:type?/:range?`

### What is expected?

生成对应 `type` 与 `range` 的[爱思想文章排行榜](http://www.aisixiang.com/toplist/)

### What is actually happening?

返回 `503` 错误

### Self-deployed information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### Additional info (logs errors etc)

```
RSSHub 发生了一些意外:
Error: Request failed with status code 503
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```
以及[官方文档](https://docs.rsshub.app/#%E7%88%B1%E6%80%9D%E6%83%B3)排行榜举例 url 有错误，应该是 `/aisixiang/ranking/1/7` 而不是 `/aisixiang/column/1/7`

**Comment by yefoenix** [comment]
@queensferryme 可能是爱思想服务器屏蔽了国外IP

**Comment by HenryQW** [comment]
@yefoenix 爱思想正常访问都会503，他的 nginx 服务器特别烂。

**Comment by queensferryme** [comment]
RSS已经恢复正常，可能是由于爱思想服务不稳定。
