### ISSUE TITLE
Debian编译报错

### ISSUE THREAD

**Issue by yzkoori** [DIYgod/RSSHub#17480]
### 路由地址

```routes
NOROUTE
```

### 完整路由地址

```fullroutes
NOROUTE
```

### 相关文档

https://docs.rsshub.app/zh/deploy/

### 预期是什么？

完成编译

### 实际发生了什么？

编译失败

### 部署

自建

### 部署相关信息

Linux 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux  Node.js v22.11.0

### 额外信息

```shell
pnpm : 9.12.3

/app/RSSHub# pnpm build

> rsshub@1.0.0 build /app/RSSHub
> tsx scripts/workflow/build-routes.ts

/app/RSSHub/.pnp.cjs:25137
    throw firstError;
    ^

Error: Your application tried to access get-tsconfig, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: get-tsconfig
Required by: /app/RSSHub/node_modules/.pnpm/tsx@4.19.2/node_modules/tsx/dist/

Require stack:
- /app/RSSHub/node_modules/.pnpm/tsx@4.19.2/node_modules/tsx/dist/register-DCnOAxY2.cjs
- /app/RSSHub/node_modules/.pnpm/tsx@4.19.2/node_modules/tsx/dist/cjs/index.cjs
- /app/RSSHub/node_modules/.pnpm/tsx@4.19.2/node_modules/tsx/dist/get-pipe-path-BoR10qr8.cjs
- /app/RSSHub/node_modules/.pnpm/tsx@4.19.2/node_modules/tsx/dist/preflight.cjs
- internal/preload
    at require$$0.Module._resolveFilename (/app/RSSHub/.pnp.cjs:25136:13)
    at require$$0.Module._load (/app/RSSHub/.pnp.cjs:24986:42)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:141:16)
    at Object.<anonymous> (/app/RSSHub/node_modules/.pnpm/tsx@4.19.2/node_modules/tsx/dist/register-DCnOAxY2.cjs:1:211)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1689:10)
    at require$$0.Module._extensions..js (/app/RSSHub/.pnp.cjs:25180:33)

Node.js v22.11.0
 ELIFECYCLE  Command failed with exit code 1.
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by yzkoori** [comment]
按照pnpm的提示安装了一堆依赖但还是没有解决问题，后来找到一个方法，删除根目录下.pnp.cjs文件，问题解决，删除重新再拉一遍仓库用pnpm也没复现问题。怀疑是之前用yarn build过一遍导致的。
但是目前版本用yarn 3.5.0 确实没办法build

**Comment by yzkoori** [comment]
11月份用pnpm虽然跑起来了，但是运行十几个小时后会随机卡进bug，一直打印一个错误（log被我搞丢了），然后磁盘被占满，app崩溃没法用，就换回了legacy，node 用的 v16，yarn跑没发生过问题。
后来更新到2024.12.12的版本，重新开了一个文件夹，用node 16.20.2 跑pnpm，也没有出现过问题了，用推荐的v22跑反而会出现warning (node:8340) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead. (Use `node --trace-deprecation ...` to show where the warning was created)
感觉还是用v16稳定点
