### ISSUE TITLE
豆瓣高分电影出问题了哦

### ISSUE THREAD

**Issue by mrdong916** [DIYgod/RSSHub#1781]
### 路由地址
https://rsshub.app/douban/movie/playing/7.5/郑州
### 实际发生了什么？
RSSHub 发生了一些意外:
Error: Request failed with status code 400
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:202:15)
    at endReadableNT (_stream_readable.js:1132:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by LogicJake** [comment]
![image](https://user-images.githubusercontent.com/20673460/54582256-0cd81080-4a4b-11e9-808b-800d151864e7.png)

**Comment by DIYgod** [comment]
现在没问题，可能反爬或网络抽风，忽略

**Comment by jiey2016** [comment]
![image](https://user-images.githubusercontent.com/19381978/57851636-ab96a880-7813-11e9-9dae-424d480f4773.png)
又不行了，求修复 @DIYgod

**Comment by DIYgod** [comment]
豆瓣接口现在要求 apikey，但是豆瓣开发平台已经关了，需要把这个路由改成从页面获取

**Comment by DIYgod** [comment]
fixed 101f3ee61cffe855e58ea1b40ef4b8baecbb3018
