### ISSUE TITLE
获取抖音RSS报错：Failed to launch chrome

### ISSUE THREAD

**Issue by wonderzhou** [DIYgod/RSSHub#1835]
### 路由地址
/douyin/user/93610979153
### 预期是什么？
正常获取抖音内容
### 实际发生了什么？
报错
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 | CentOS Linux release 7.5.1804    |
| Node version       | v10.15.3      |
| if Docker, version |               |

### 额外信息（日志、报错等）
RSSHub 发生了一些意外:
Error: Failed to launch chrome!
/usr/local/rsshub/node_modules/_puppeteer@1.13.0@puppeteer/.local-chromium/linux-637110/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/rsshub/node_modules/_puppeteer@1.13.0@puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/usr/local/rsshub/node_modules/_puppeteer@1.13.0@puppeteer/lib/Launcher.js:331:50)
    at Interface.emit (events.js:194:15)
    at Interface.close (readline.js:379:8)
    at Socket.onend (readline.js:157:10)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by ueiu** [comment]
嗯..我当时在CentOS系统部署也遇到了,后来解决了.你可以参考一下这篇文章:https://luodao.me/post/puppeteer-pakeng.html,就是puppeteer需要安装一个Chromium,解压安装好后就可以获取抖音的rss了

**Comment by wonderzhou** [comment]
> 嗯..我当时在CentOS系统部署也遇到了,后来解决了.你可以参考一下这篇文章: https://luodao.me/post/puppeteer-pakeng.html
> 就是puppeteer需要安装一个Chromium,解压安装好后就可以获取抖音的rss了

完美解决，感谢感谢
