### ISSUE TITLE
NGA论坛的二次元国家地理版块的Fid路由出错

### ISSUE THREAD

**Issue by 3cr13** [DIYgod/RSSHub#1962]
### 路由地址
https://rsshub.app/nga/forum/-447601
### 预期是什么？
使用RSSHub的演示地址，订阅NGA的网事杂谈板块等板块，均正常，但在订阅二次元国家地理板块，则无法正常订阅RSS，在该板块使用NGA论坛提供的?lite=xml参数和其它板块一样是可以获取xml，但由于格式它无法直接作为rss订阅源地址
### 实际发生了什么？
https://rsshub.app/nga/forum/-447601 使用浏览器打开报错，浏览器F12确认板块Fid为-447601无误，如果使用相似的其它板块的fid（如-343809，为汽车俱乐部板块的fid）则可以正常订阅rss
### 额外信息（日志、报错等）
使用浏览器打开https://rsshub.app/nga/forum/-447601 的报错信息如下

RSSHub 发生了一些意外: 
TypeError: html.replace is not a function
    at Object.decode (/app/node_modules/he/he.js:232:15)
    at ctx.state.data.item.ctx.state.data.item.forEach (/app/lib/middleware/parameter.js:13:60)
    at Array.forEach ()
    at module.exports (/app/lib/middleware/parameter.js:11:33)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

**Comment by xyqfer** [comment]
额，这个我在本地用最新的代码试了是好的，demo 为啥挂了估计要麻烦 @DIYgod 看下了

**Comment by DIYgod** [comment]
Fixed. ec9f9aa018bb9b288fcb5f2967ba074027d1e030

[这个帖子](https://nga.178.com/read.php?tid=15599858&rand=293)的内容 “11111” 被 redis 当作 number 类型了

**Comment by zhuchiheng** [comment]
又挂了 >_<
