### ISSUE TITLE
抖音无抓取内容

### ISSUE THREAD

**Issue by Mr-Phone** [DIYgod/RSSHub#2034]
### 路由地址
抖音
### 预期是什么？
抓取到内容
### 实际发生了什么？
偶尔有部分账户无内容
![image](https://user-images.githubusercontent.com/9606042/57126097-46c46280-6dbe-11e9-99d2-aec43cb1b053.png)
账号：https://www.iesdouyin.com/share/user/58162853937
### 部署相关信息
Centos 7
PM2
#1928 

###错误信息
error: Error in /douyin/user/58162853937: TypeError: Cannot read property 'play_addr' of undefined
    at formatItem (/root/RSSHub/lib/routes/douyin/utils.js:4:39)
    at Array.map (<anonymous>)
    at module.exports (/root/RSSHub/lib/routes/douyin/user.js:53:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by xyqfer** [comment]
看了一眼接口返回值，原来抖音还可以传图片的？😢

**Comment by Mr-Phone** [comment]
> 看了一眼接口返回值，原来抖音还可以传图片的？😢

**Comment by Mr-Phone** [comment]
> 看了一眼接口返回值，原来抖音还可以传图片的？😢

是的，抖音可以传图片
