### ISSUE TITLE
在Windows下，如何调试订阅源的js脚本

### ISSUE THREAD

**Issue by Derekmini** [DIYgod/RSSHub#2203]
### 这是一个什么样的功能？

在Windows下RSSHub中js脚本的调试环境

### 这个功能可以解决什么问题？

自己已经在VPS上通过Docker搭建了RSSHub，用起来非常好，对于没有添加的源，拿Huginn做了补充，但是，RSSHub太好用了，所以一直计划将Huginn的内容转到RSSHub下来实现。

之前没有接触过js，所以想参照当前已有的脚本来改写，docs.rsshub.app[编写脚本教程](https://docs.rsshub.app/joinus/#步骤-1-编写脚本)中的内容我大致能看懂，我计划试着将现有的脚本运行调试一下，查看一下变量、理解一下js脚本思路，但是配置的工作环境不正确。

我在windows上搭建的环境：参照[廖雪峰的教程](https://www.liaoxuefeng.com/wiki/1022910821149312/1023025235359040)，[安装了Node.js](https://www.liaoxuefeng.com/wiki/1022910821149312/1023025597810528)、添加了Windows系统环境PATH、[安装了 Visual Studio Code IDE软件](https://www.liaoxuefeng.com/wiki/1022910821149312/1099503821472096)，并下载了**RSSHub源码**设置为当前工作目录，我试着调试了一下，出现如下错误：
```javascript
Error: Cannot find module 'dotenv'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
at Function.Mod
```

请问，在win下应如何配置工作环境、RSSHub源码正常的目录结构是什么样子的？

我最终想实现的过程是：正常运行一个现有的某个源的脚本，并以此为模板，为另一个结构类似的网站写一个新的订阅源脚本。

### 额外描述

我也想推广一下RSSHub，对于Windows下刚开始参与写RSSHub订阅源脚本的朋友，可以以此作为一个参考，先搭建应用软件的环境、配置好js脚本的工作目录，从成功调试现有的订阅源js脚本开始，再一步一步仿写，最终制作更多的源，推广更多小白参与进来。

谢谢！

**Comment by DIYgod** [comment]
安装依赖了么？请参考[手动部署](https://docs.rsshub.app/install/#%E6%89%8B%E5%8A%A8%E9%83%A8%E7%BD%B2)

**Comment by Derekmini** [comment]
> 安装依赖了么？请参考[手动部署](https://docs.rsshub.app/install/#%E6%89%8B%E5%8A%A8%E9%83%A8%E7%BD%B2)

给npm挂http代理：
```
npm config set proxy=http://127.0.0.1:2080
```
安装依赖：
```
npm install
```
测试：
```
http://localhost:1200/infzm/2 #南方周末
# 成功获取内容
```

**Comment by Derekmini** [comment]
在Visual Studio Code中进行调试时，会自动在RSSHub目录下创建一个`.vscode`文件夹，并创建一个`launch.json`文件，其内容如下：
```
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\lib\\index.js"
        }
    ]
}
```
为了复现docs.rsshub.app[步骤 1: 编写脚本](https://docs.rsshub.app/joinus/#步骤-1-编写脚本)中内容，对\lib\routes\bilibili\coin.js脚本进行调试，将`launch.json`内容改为如下：
```
{
    // 使用 IntelliSense 了解相关属性。 
    // 悬停以查看现有属性的描述。
    // 欲了解更多信息，请访问: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}\\lib\\routes\\bilibili\\coin.js"
        }
    ]
}
```

调试控制台内容如下：
```
D:\Program Files\nodejs\node.exe --inspect-brk=3276 lib\routes\bilibili\coin.js
Debugger listen
ing on ws://127.0.0.1:3276/534293e5-2256-485b-b420-aa3276900517
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
internal/modules/cjs/
loader.js:584
    throw err;
    ^

Error: Cannot find module '@/utils/axios'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15
)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at
Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (d:\Newspace\RSSHub\lib\routes\bilibili\coin.j
s:1:77)
    at Module._compile (internal/modules/cjs/loader.js:698:14)
    at Object.Module._extensions..js (internal
/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    a
t tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Funct
ion.Module._load (internal/modules/cjs/loader.js:531:3)
Waiting for the
Error: Cannot find module '@/utils/axios'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (d:\Newspace\RSSHub\lib\routes\bilibili\coin.js:1:77)
    at Module._compile (internal/modules/cjs/loader.js:698:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
 debugger to disconnect...
```

`axios`在`RSSHub\node_modules\axios`处，请问，在Win下，如何将其添加到环境中？

**Comment by DIYgod** [comment]
那个是 vscode 自动生成的，不需要改，直接控制台执行 npm run dev

**Comment by Derekmini** [comment]
点击调试后，在控制台下面`>`后输入并执行 `npm run dev`，得到如下提示：
```
npm run dev
SyntaxError: Unexpected identifier
```

**Comment by Derekmini** [comment]
在Visual Studio Code中点击`调试`后，我在浏览器中打开`http://localhost:1200`，发现RSSHub可以正常工作，请问，如果继续调试的话，该如何操作？

**Comment by DIYgod** [comment]
@Derekmini 没看懂你想调试什么...一般是打开对应路由看是否有正常工作

**Comment by DIYgod** [comment]
@Derekmini 与本项目无关，请自行 Google，关键词 vscode debug node

**Comment by Derekmini** [comment]
谢谢提示！我去学习一下！
