### ISSUE TITLE
语雀 Request failed with status code 429

### ISSUE THREAD

**Issue by geerda123** [DIYgod/RSSHub#2217]
RSSHub 发生了一些意外:
Error: Request failed with status code 429
    at createError (/data/wwwroot/rsshub.app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/data/wwwroot/rsshub.app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/data/wwwroot/rsshub.app/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)

**Comment by aka-rin** [comment]
429 是请求频率过高被限制了吧……

**Comment by yefoenix** [comment]
429 是请求超限，建议申请 token 并自建

**Comment by DIYgod** [comment]
demo 加了 token，已恢复
