### ISSUE TITLE
博主（方案 1）部分失效

### ISSUE THREAD

**Issue by StrollStars** [DIYgod/RSSHub#2228]
### 路由地址
/weibo/user/:uid

### 预期是什么？
正常抓取

### 实际发生了什么？
有些能够正常抓取，有些失效，例如：https://rsshub.app/weibo/user/2831094660

### 额外信息（日志、报错等）
Error: Request failed with status code 418
    at createError (/data/wwwroot/rsshub.app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/data/wwwroot/rsshub.app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/data/wwwroot/rsshub.app/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:201:15)
    at endReadableNT (_stream_readable.js:1130:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)

**Comment by yefoenix** [comment]
@StrollStars 微博返回了一个418，说它是个茶壶。反爬了，请自建，自建测试没问题。

**Comment by zengxs** [comment]
微博的接口请求频率太快就会返回 HTTP 418，极限频率应该是200ms~300ms一次请求，建议控制在最多500ms一次请求的频率以下

**Comment by StrollStars** [comment]
@yefoenix @zengxs 感谢二位告知，自建确实可以。
