### ISSUE TITLE
pixiv 用户动态不能获取

### ISSUE THREAD

**Issue by ClarkeCheng** [DIYgod/RSSHub#2341]
### 路由地址
[https://rsshub.app/pixiv/user/11](https://rsshub.app/pixiv/user/11)
### 预期是什么？
返回数据
### 实际发生了什么？
返回
```
RSSHub 发生了一些意外:
HTTPError: Response code 400 (Bad Request)
    at EventEmitter. (/data/wwwroot/rsshub.app/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by DIYgod** [comment]
无法复现，可能网络问题
