### ISSUE TITLE
目前最新的docker镜像无法启动

### ISSUE THREAD

**Issue by jpacg** [DIYgod/RSSHub#2377]
日志是
```
> rsshub@0.0.1 start /app
> node lib/index.js

warn: pixiv RSS is disabled due to the lack of token, api key or relevant config in config.js.
warn: Disqus RSS is disabled due to the lack of token, api key or relevant config in config.js.
warn: Twitter RSS is disabled due to the lack of token, api key or relevant config in config.js.
/app/lib/routes/twitter/utils.js:113
const consumer_keys = config.twitter.consumer_key.split(',');
                                                  ^

TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (/app/lib/routes/twitter/utils.js:113:51)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/app/lib/routes/twitter/followings.js:1:77)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rsshub@0.0.1 start: `node lib/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rsshub@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-12T02_02_02_372Z-debug.log
```

**Comment by jpacg** [comment]
看代码已经修复了，但docker镜像还是旧的，没有更新。

**Comment by DIYgod** [comment]
Fixed.
