### ISSUE TITLE
wemp.app 微信抓取错误

### ISSUE THREAD

**Issue by Undefined01** [DIYgod/RSSHub#2378]
### 路由地址

https://rsshub.app/wechat/wemp/36836fbe-bdec-4758-8967-7cc82722952d

### 预期是什么？

正常rss

### 实际发生了什么？

```
RSSHub 发生了一些意外:
HTTPError: Response code 403 (Forbidden)
    at EventEmitter. (/data/wwwroot/rsshub.app/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

### 部署相关信息

演示地址

**Comment by yefoenix** [comment]
@Undefined01 反爬严格，自建也不一定可用……
