### ISSUE TITLE
IOS 限免提醒 404 not found

### ISSUE THREAD

**Issue by hueyless** [DIYgod/RSSHub#2403]
### 路由地址
https://rsshub.app/appstore/price/cn/ios/id1152443474

### 预期是什么？
有返回

### 实际发生了什么？
RSSHub 发生了一些意外:
Error: this route is empty, please check the origin site or create an issue to feedback on https://github.com/DIYgod/RSSHub/issues/new/choose
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:7:15)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:36:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:17:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:5:9)

### 部署相关信息
官方版本

**Comment by DIYgod** [comment]
Fixed 3c0bfeff9718ce9d0165ae4fefcda77d08c0710c
