### ISSUE TITLE
nHentai 挂好久啦

### ISSUE THREAD

**Issue by aka-rin** [DIYgod/RSSHub#2410]
一直没人修…… （#2128 里提到过但还是单开一个吧）

### 路由地址

- https://rsshub.app/nhentai/search/chinese
- https://rsshub.app/nhentai/language/chinese

### 预期是什么？

Sètú!

### 实际发生了什么？

- Error 504 Gateway time-out
- Error: this route is empty, please check the origin site or create an issue to feedback on https://github.com/DIYgod/RSSHub/issues/new/choose

### 额外信息（日志、报错等）

```
RSSHub 发生了一些意外:
Error: this route is empty, please check the origin site or create an issue to feedback on https://github.com/DIYgod/RSSHub/issues/new/choose
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:7:15)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:36:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:17:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:5:9)
```

**Comment by kt286** [comment]
第一条路由自建没问题  应该是服务器网络问题
第二条路由关键字已经变了

**Comment by aka-rin** [comment]
试试换成 https://nhent.ai ？

**Comment by kt286** [comment]
@DIYgod 刚才看了一下  貌似正常了
