### ISSUE TITLE
bilibili非默认收藏夹失效

### ISSUE THREAD

**Issue by BeautyYuYanli** [DIYgod/RSSHub#2430]
文档中提供的演示地址[https://rsshub.app/bilibili/fav/756508/50948568](https://rsshub.app/bilibili/fav/756508/50948568)返回了

```
RSSHub 发生了一些意外:
Error: this route is empty, please check the origin site or create an issue to feedback on https://github.com/DIYgod/RSSHub/issues/new/choose
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:7:15)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:36:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:17:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:5:9)
```
@Qixingchen

**Comment by Qixingchen** [comment]
@BeautyYuYanli 接口更换 我更新下
