### ISSUE TITLE
Dockone周报失效

### ISSUE THREAD

**Issue by Ghosin** [DIYgod/RSSHub#2449]
### 路由地址
https://rsshub.app/dockone/weekly  

### 预期是什么？
RSS输出  

### 实际发生了什么？
HTTP 404  

### 额外信息（日志、报错等）
```
RSSHub 发生了一些意外:  
HTTPError: Response code 404 (Not Found)  
    at EventEmitter. (/data/wwwroot/rsshub.app/node_modules/got/source/as-promise.js:74:19)  
    at processTicksAndRejections (internal/process/task_queues.js:89:5)  
```

**Comment by kt286** [comment]
为啥不用官方源
http://weekly.dockone.io/feed

**Comment by Ghosin** [comment]
ok
