### ISSUE TITLE
自建实例特定Instagram用户无法获取

### ISSUE THREAD

**Issue by RekiDunois** [DIYgod/RSSHub#2513]
### 路由地址
https://rsshub.app/instagram/user/_hotbin
### 预期是什么？
正确生成rss feed
### 实际发生了什么？
+ 自建实例
```
RSSHub 发生了一些意外:
Error: this route is empty, please check the origin site or create an issue to feedback on https://github.com/DIYgod/RSSHub/issues/new/choose
    at module.exports (/app/lib/middleware/parameter.js:11:15)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async module.exports (/app/lib/middleware/template.js:15:5)
    at async /app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/app/lib/middleware/api-template.js:2:5)
    at async module.exports (/app/lib/middleware/utf8.js:4:5)
    at async module.exports (/app/lib/middleware/debug.js:14:5)
    at async module.exports (/app/lib/middleware/access-control.js:36:13)
    at async module.exports (/app/lib/middleware/header.js:17:5)
    at async module.exports (/app/lib/middleware/onerror.js:5:9)
```
+ demo 
```
RSSHub 发生了一些意外:
HTTPError: Response code 429 (-)
    at EventEmitter. (/data/wwwroot/rsshub.app/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |        heroku       |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
目前还没有找到其他特征相似的用户。

**Comment by yefoenix** [comment]
这是个私密账户啊……

**Comment by RekiDunois** [comment]
能不能通过增加ins的账号密码环境变量来抓取这类私密账号呢

**Comment by yefoenix** [comment]
@RekiDunois https://www.instagram.com/developer/

**Comment by DIYgod** [comment]
私密账户无法抓取
