### ISSUE TITLE
AI研习社 Error: wrong path

### ISSUE THREAD

**Issue by geerda123** [DIYgod/RSSHub#2516]
### 路由地址

https://rsshub.app/aiyanxishe
### 实际发生了什么？
Error: wrong path
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:7:15)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    “”“”“”“”“etc”

**Comment by kt286** [comment]
好好看文档  issue可以关了

**Comment by kt286** [comment]
路由: /aiyanxishe/:id/:sort?

参数:
id, `必选` - 领域 id，全部领域为 `all`，单独领域 id 抓包可得
sort, 可选 - 排序方式，默认为 new（最新），也可选择 hot（最热）或 recommend（推荐）

**Comment by SettingDust** [comment]
这种模板文档都不看的，别回复直接等关闭就是了= =
