### ISSUE TITLE
bihu.com爬取失败

### ISSUE THREAD

**Issue by lylunula** [DIYgod/RSSHub#2526]
### 路由地址
举例: https://rsshub.app/bihu/activaties/1478342200
路由: /bihu/activaties/:id

### 预期是什么？
正常订阅

### 实际发生了什么？
RSSHub 发生了一些意外:
HTTPError: Response code 400 (Bad Request)
    at EventEmitter. (/data/wwwroot/rsshub.app/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

**Comment by kt286** [comment]
网站API变了  并且加入了`极验深知`豪华套餐  不好搞啊
https://docs.geetest.com/deepknow/overview/flowchart

**Comment by lylunula** [comment]
感谢各位，看起来没那么好解决，我就先close掉吧
