### ISSUE TITLE
看漫画失效

### ISSUE THREAD

**Issue by KenWuqianghao** [DIYgod/RSSHub#2536]

**Comment by kt286** [comment]
自建可以 应该是反爬

**Comment by KenWuqianghao** [comment]
> 自建可以 应该是反爬

不行啊，全部显示有bug

**Comment by yefoenix** [comment]
@KenWuqianghao 为啥这个issue的description是空的？

**Comment by KenWuqianghao** [comment]
> @KenWuqianghao 为啥这个issue的description是空的？

因为就像标题一样简单明了啊

**Comment by yefoenix** [comment]
@KenWuqianghao 明了什么？错误代码不写，路由也不写一个，想测试一下还得自己翻文档

**Comment by KenWuqianghao** [comment]
https://rsshub.app/manhuagui/comic/22942
RSSHub 发生了一些意外:
RequestError: connect ETIMEDOUT 47.89.23.88:443
    at ClientRequest. (/data/wwwroot/rsshub.app/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:284:20)
    at ClientRequest.emit (events.js:201:15)
    at ClientRequest.origin.emit (/data/wwwroot/rsshub.app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:196:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)

**Comment by yefoenix** [comment]
@KenWuqianghao 用三个自建服务测试了一下都是OK的，初步判断是反爬

**Comment by DIYgod** [comment]
源站问题现已恢复
