### ISSUE TITLE
It seems that pixiv rss can't work properly. 

### ISSUE THREAD

**Issue by oreme2** [DIYgod/RSSHub#2608]
RSSHub 发生了一些意外:
HTTPError: Response code 400 (Bad Request)
    at EventEmitter. (/data/wwwroot/rsshub.app/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by BrightSphere** [comment]
```{
	"name": "HTTPError",
	"host": "oauth.secure.pixiv.net",
	"hostname": "oauth.secure.pixiv.net",
	"method": "POST",
	"path": "/auth/token",
	"protocol": "https:",
	"url": "https://oauth.secure.pixiv.net/auth/token",
	"gotOptions": {
		"path": "/auth/token",
		"protocol": "https:",
		"slashes": true,
		"auth": null,
		"host": "oauth.secure.pixiv.net",
		"port": null,
		"hostname": "oauth.secure.pixiv.net",
		"hash": null,
		"search": null,
		"query": null,
		"pathname": "/auth/token",
		"href": "https://oauth.secure.pixiv.net/auth/token",
		"retry": {
			"methods": {},
			"statusCodes": {},
			"errorCodes": {}
		},
		"headers": {
			"user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36",
			"x-app": "RSSHub",
			"accept-encoding": "gzip, deflate"
		},
		"hooks": {
			"beforeError": [],
			"init": [
				null
			],
			"beforeRequest": [],
			"beforeRedirect": [],
			"beforeRetry": [
				null
			],
			"afterResponse": [
				null
			]
		},
		"decompress": true,
		"throwHttpErrors": true,
		"followRedirect": true,
		"stream": false,
		"form": false,
		"json": false,
		"cache": false,
		"useElectronNet": false,
		"_overheadLength": 768,
		"_valueLength": 160,
		"_valuesToMeasure": [],
		"writable": false,
		"readable": true,
		"dataSize": 0,
		"maxDataSize": 2097152,
		"pauseStreams": true,
		"_released": false,
		"_streams": [
			"----------------------------779093560277834196109463\r\nContent-Disposition: form-data; name=\"client_id\"\r\n\r\n",
			"MOBrBDS8blbauoSck0ZfDbtuzpyT",
			null,
			"----------------------------779093560277834196109463\r\nContent-Disposition: form-data; name=\"client_secret\"\r\n\r\n",
			"lsACyCD94FhDUtGTXi3QzcFE2uU1hqtDaKeqrdwj",
			null,
			"----------------------------779093560277834196109463\r\nContent-Disposition: form-data; name=\"username\"\r\n\r\n",
			"********************",
			null,
			"----------------------------779093560277834196109463\r\nContent-Disposition: form-data; name=\"password\"\r\n\r\n",
			"*************",
			null,
			"----------------------------779093560277834196109463\r\nContent-Disposition: form-data; name=\"get_secure_url\"\r\n\r\n",
			"1",
			null,
			"----------------------------779093560277834196109463\r\nContent-Disposition: form-data; name=\"grant_type\"\r\n\r\n",
			"refresh_token",
			null,
			"----------------------------779093560277834196109463\r\nContent-Disposition: form-data; name=\"refresh_token\"\r\n\r\n",
			"d********************************I",
			null
		],
		"_currentStream": null,
		"_insideLoop": false,
		"_pendingNext": false,
		"_boundary": "--------------------------779093560277834196109463",
		"method": "POST"
	},
	"statusCode": 400,
	"statusMessage": "Bad Request",
	"headers": {
		"server": "nginx",
		"date": "Thu, 11 Jul 2019 08:18:36 GMT",
		"content-type": "application/json",
		"content-length": "114",
		"connection": "close",
		"x-content-type-options": "nosniff",
		"strict-transport-security": "max-age=31536000",
		"x-frame-options": "SAMEORIGIN"
	},
	"body": "{\"has_error\":true,\"errors\":{\"system\":{\"message\":\"Invalid grant_type parameter or parameter missing\",\"code\":1508}}}",
	"stack": "HTTPError: Response code 400 (Bad Request)\n    at EventEmitter.emitter.on (/app/node_modules/got/source/as-promise.js:74:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
}
```
补充一下log

然后我把refreshToken方法里的请求写法换成和login里的一样，好像就没问题了。

**Comment by yefoenix** [comment]
@BrightSphere 欢迎pr
