### ISSUE TITLE
sec.doday  腾讯-玄武实验室-日推 挂掉了

### ISSUE THREAD

**Issue by cryzlasm** [DIYgod/RSSHub#2636]
### 网站地址
https://rsshub.app/security/pulses
### 网站描述
腾讯-玄武实验室-日推 挂掉了

``` js
RSSHub 发生了一些意外:
Error: this route is empty, please check the original site or create an issue on https://github.com/DIYgod/RSSHub/issues/new/choose
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:11:15)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:36:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:17:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:5:9)
```

**Comment by LogicJake** [comment]
@cryzlasm

**Comment by SettingDust** [comment]
@cryzlasm
