### ISSUE TITLE
机核网网站改版，原路由无法抓取，需要更新。

### ISSUE THREAD

**Issue by cyy911** [DIYgod/RSSHub#2640]
### 路由地址
https://rsshub.app/gcores/category/1
https://rsshub.app/gcores/category/2
https://rsshub.app/gcores/category/3
### 预期是什么？

RSS内容

### 实际发生了什么？
RSSHub 发生了一些意外:
Error: this route is empty, please check the original site or create an issue on https://github.com/DIYgod/RSSHub/issues/new/choose
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:11:15)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:36:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:17:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:5:9)

**Comment by yefoenix** [comment]
#2639 to be merged
