### ISSUE TITLE
财新首页rss不能用了

### ISSUE THREAD

**Issue by liweitd** [DIYgod/RSSHub#2650]
如题。

**Comment by xtaodada** [comment]
### 路由地址
https://rsshub.app/caixin/article
### 预期是什么？
返回正常rss页面
### 实际发生了什么？
**demo和自建报错**
### 额外信息（日志、报错等）
```
RSSHub 发生了一些意外:
SyntaxError: Unexpected token \ in JSON at position 0
    at JSON.parse ()
    at module.exports (/data/wwwroot/rsshub.app/lib/routes/caixin/article.js:15:23)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async cache (/data/wwwroot/rsshub.app/lib/middleware/cache.js:260:9)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:36:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:17:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:5:9)
```
而且您的反馈模板呢 艹

**Comment by SettingDust** [comment]
@liweitd 自行关闭或等待关闭
