### ISSUE TITLE
rsshubd用户认证配置的功能在ttrss上一直报错，不知是何原因

### ISSUE THREAD

**Issue by Rixcloudllnll** [DIYgod/RSSHub#2668]
同一台vps上自建ttrss(docker)+rsshub，以路由```/rsshub/rss```为例，认证密码默认

protected_router.js文件
```
cat protected_router.js
const Router = require('koa-router');
const router = new Router();
const auth = require('koa-basic-auth');
const config = require('./config');

router.use('/(.*)', auth(config.authentication));

// RSSHub
router.get('/rsshub/rss', require('./routes/rsshub/rss'));

module.exports = router;
```
router.js文件
```
cat router.js
const Router = require('koa-router');
const router = new Router();
const config = require('./config');
const logger = require('./utils/logger');

// RSSHub
//router.get('/rsshub/rss', require('./routes/rsshub/rss'));

module.exports = router;
```

### 测试：

尝试用chrome打开http://ip:port/rsshub/rss
```
RSSHub 发生了一些意外:
Error: wrong path
    at module.exports (~/RSSHub/lib/middleware/parameter.js:7:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

在ttrss的```Subscribe to Feed```中按照[用户认证配置官方doc](https://docs.rsshub.app/install/#%E7%94%A8%E6%88%B7%E8%AE%A4%E8%AF%81%E9%85%8D%E7%BD%AE)填
```
http://usernam3:passw0rd@ip:port/protected/rsshub/rss
```
不勾选```This feed requires authentication.```，ttrss报错
```
Couldn't download the specified URL: HTTP/1.1 404 Not Found
```

查看rsshub 的error log，发现报错
```
 info: /protected/rsshub/rss, user IP: ::ffff:hidden
 error: Error in /rsshub/rss: UnauthorizedError: Unauthorized
     at Object.throw (~/RSSHub/node_modules/koa/lib/context.js:97:11)
     at basicAuth (~/RSSHub/node_modules/koa-basic-auth/index.js:39:23)
     at dispatch (~/RSSHub/node_modules/koa-compose/index.js:44:32)
     at next (~/RSSHub/node_modules/koa-compose/index.js:45:18)
     at ~/RSSHub/node_modules/koa-router/lib/router.js:346:16
     at dispatch (~/RSSHub/node_modules/koa-compose/index.js:44:32)
     at ~/RSSHub/node_modules/koa-compose/index.js:36:12
     at dispatch (~/RSSHub/node_modules/koa-router/lib/router.js:351:31)
     at ~/RSSHub/node_modules/koa-mount/index.js:58:11
     at dispatch (~/RSSHub/node_modules/koa/node_modules/koa-compose/index.js:42:32)
     at allowedMethods (~/RSSHub/node_modules/koa-router/lib/router.js:407:12)
     at dispatch (~/RSSHub/node_modules/koa/node_modules/koa-compose/index.js:42:32)
     at dispatch (~/RSSHub/node_modules/koa-router/lib/router.js:332:32)
     at dispatch (~/RSSHub/node_modules/koa/node_modules/koa-compose/index.js:42:32)
     at cache (~/RSSHub/lib/middleware/cache.js:260:15)
     at process._tickCallback (internal/process/next_tick.js:68:7)
```

第二次填
```
http://ip:port/protected/rsshub/rss
```
勾选```This feed requires authentication.```，填
```
usernam3
passw0rd
```
报错
```
Couldn't download the specified URL: HTTP/1.1 404 Not Found
```

查看rsshub 的error log，发现报错
```
 info: /protected/rsshub/rss, user IP: ::ffff:172.21.0.3
 error: Error in /rsshub/rss: UnauthorizedError: Unauthorized
     at Object.throw (~/RSSHub/node_modules/koa/lib/context.js:97:11)
     at basicAuth (~/RSSHub/node_modules/koa-basic-auth/index.js:39:23)
     at dispatch (~/RSSHub/node_modules/koa-compose/index.js:44:32)
     at next (~/RSSHub/node_modules/koa-compose/index.js:45:18)
     at ~/RSSHub/node_modules/koa-router/lib/router.js:346:16
     at dispatch (~/RSSHub/node_modules/koa-compose/index.js:44:32)
     at ~/RSSHub/node_modules/koa-compose/index.js:36:12
     at dispatch (~/RSSHub/node_modules/koa-router/lib/router.js:351:31)
     at ~/RSSHub/node_modules/koa-mount/index.js:58:11
     at dispatch (~/RSSHub/node_modules/koa/node_modules/koa-compose/index.js:42:32)
     at allowedMethods (~/RSSHub/node_modules/koa-router/lib/router.js:407:12)
     at dispatch (~/RSSHub/node_modules/koa/node_modules/koa-compose/index.js:42:32)
     at dispatch (~/RSSHub/node_modules/koa-router/lib/router.js:332:32)
     at dispatch (~/RSSHub/node_modules/koa/node_modules/koa-compose/index.js:42:32)
     at cache (~/RSSHub/lib/middleware/cache.js:260:15)
     at process._tickCallback (internal/process/next_tick.js:68:7)
```

第三次填
```
http://ip:port/rsshub/rss
```
勾选```This feed requires authentication.```，填
```
usernam3
passw0rd
```
报错
```
Couldn't download the specified URL: HTTP/1.1 404 Not Found
```

**Comment by kt286** [comment]
> 尝试用chrome打开http://ip:port/rsshub/rss
>
> RSSHub 发生了一些意外:
> Error: wrong path
>    at module.exports (~/RSSHub/lib/middleware/parameter.js:7:15)
>    at process._tickCallback (internal/process/next_tick.js:68:7)

很明显没搭建成功，后边的测试都没意义

**Comment by HenryQW** [comment]
![image](https://user-images.githubusercontent.com/5896343/63900975-a17f6b00-c9fa-11e9-925f-f9bbace59d83.png)
![image](https://user-images.githubusercontent.com/5896343/63901276-ccb68a00-c9fb-11e9-8f36-7d9dfd924217.png)


![image](https://user-images.githubusercontent.com/5896343/63901240-aabd0780-c9fb-11e9-8094-f780a8cc63be.png)

我用了下 postman 可以，问题貌似出现在 ttrss 和阅读器中的请求头部中没有包涵 authorization，手头没有需要认证的源可以测试。

**Comment by lechengyu** [comment]
遇到同样的问题，postman可以，但是在 ttrss中用户认证不行

**Comment by machsix** [comment]
我直接用的nginx反代。。

**Comment by Rixcloudllnll** [comment]
> 我直接用的nginx反代。。

ttrss和rsshub装在同一台机器上。config.js中有一条
```
 listenInaddrAny: parseInt(envs.LISTEN_INADDR_ANY) || 1, // 是否允许公网连接，取值 0 1
```
我改成0却不能实现加密的效果，logs里都没新的日志了，不知道为什么。

看pm2 logs rsshub 里面的IP 是 172.21.0.4 ，明明是局域网
@HenryQW

**Comment by DIYgod** [comment]
> > 我直接用的nginx反代。。
> 
> ttrss和rsshub装在同一台机器上。config.js中有一条
> 
> ```
>  listenInaddrAny: parseInt(envs.LISTEN_INADDR_ANY) || 1, // 是否允许公网连接，取值 0 1
> ```
> 
> 我改成0却不能实现加密的效果，logs里都没新的日志了，不知道为什么。
> 
> 看pm2 logs rsshub 里面的IP 是 172.21.0.4 ，明明是局域网

957a244737922861157c213510366bb72357934d 修复了这个问题
