### ISSUE TITLE
部分用户的instagram rss无法生成

### ISSUE THREAD

**Issue by tmdjiuji** [DIYgod/RSSHub#2706]
### 路由地址
https://rsshub.app/instagram/user/kokikobaby
### 预期是什么？
生成此用户 kokikobaby 的instagram 的rss
### 实际发生了什么？
显示出错信息，无法生成

### 额外信息（日志、报错等）
Error: this route is empty, please check the original site or create an issue on https://github.com/DIYgod/RSSHub/issues/new/choose
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:11:15)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:36:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:17:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:5:9)

**Comment by yefoenix** [comment]
@tmdjiuji 私密账户无法抓取，提 issue 前请先进行搜索。
duplicate #2513
