### ISSUE TITLE
NGA 路由目前失效

### ISSUE THREAD

**Issue by gelmannt** [DIYgod/RSSHub#2756]
### 路由地址

https://rsshub.app/nga/forum/485

### 预期是什么？

抓取 NGA 特定板块帖子

### 实际发生了什么？

抓取失败

### 额外信息（日志、报错等）

HTTPError: Response code 502 (Bad Gateway)
    at EventEmitter. (/data/wwwroot/rsshub.app/node_modules/got/source/as-promise.js:74:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by gelmannt** [comment]
https://rsshub.app/nga/forum/485 目前可以正常抓取但其他板块依旧报错
`TypeError: Cannot read property 'content' of undefined
    at /data/wwwroot/rsshub.app/lib/routes/nga/forum.js:49:62
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Object.app.context.cache.tryGet (/data/wwwroot/rsshub.app/lib/middleware/cache.js:136:17)
    at async /data/wwwroot/rsshub.app/lib/routes/nga/forum.js:36:33
    at async Promise.all (index 2)
    at async module.exports (/data/wwwroot/rsshub.app/lib/routes/nga/forum.js:26:24)
    at async cache (/data/wwwroot/rsshub.app/lib/middleware/cache.js:260:9)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:36:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:17:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:5:9)`
