### ISSUE TITLE
微博在ttrss中提示404

### ISSUE THREAD

**Issue by richartli** [DIYgod/RSSHub#2772]
### 输出
http://weibo.com/2707092383的微博内容

###
ttrss提示错误信息  HTTP/1.1 404 Not Found；
rsshub提示
RSSHub 发生了一些意外:
HTTPError: Response code 418 (I'm a Teapot)
    at EventEmitter.emitter.on (/app/node_modules/got/source/as-promise.js:74:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
### 部署相关信息
群晖docker 部署最新版rsshub 及 ttrss

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by Astrian** [comment]
@richartli 微博日常反爬返回错误。可能得随缘才能看好不好的了了

**Comment by richartli** [comment]
> @richartli 微博日常反爬返回错误。可能得随缘才能看好不好的了了

在提交bug时看到默认模版里面，不是返回403是微博反爬么？

**Comment by Astrian** [comment]
@richartli 418 也是，隔壁奇点第三方客户端之前经常遇到 418，最近倒是少了，不知道触发到微博什么奇怪的开关……

**Comment by RookieZoe** [comment]
docker-compose 部署的，刚刚更新后，github 和 weibo 的 都挂了，升级之前是正常的

```bash
# root @ vultr in ~/rss [10:57:05]
$ curl http://172.18.0.3/github/trending/weekly/rust
RSSHub 发生了一些意外: <pre>RequestError: getaddrinfo EAI_AGAIN github.com github.com:443
    at ClientRequest.request.once.error (/app/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:194:15)
    at ClientRequest.origin.emit.args (/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre>#
# root @ vultr in ~/rss [10:58:18]
$ curl http://172.18.0.3/weibo/user/1195230310/1
RSSHub 发生了一些意外: <pre>RequestError: getaddrinfo EAI_AGAIN m.weibo.cn m.weibo.cn:443
    at ClientRequest.request.once.error (/app/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:194:15)
    at ClientRequest.origin.emit.args (/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre>#
# root @ vultr in ~/rss [11:00:57]
$ curl http://172.18.0.3/weibo/user/1195230310
RSSHub 发生了一些意外: <pre>RequestError: getaddrinfo EAI_AGAIN m.weibo.cn m.weibo.cn:443
    at ClientRequest.request.once.error (/app/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:194:15)
    at ClientRequest.origin.emit.args (/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)</pre>
```

**Comment by yefoenix** [comment]
目前看你的自建是 ok 的，issue 可以关闭了
@DIYgod
