### ISSUE TITLE
FT 中文网获取错误

### ISSUE THREAD

**Issue by wym3253** [DIYgod/RSSHub#2797]
### 路由地址
/ft/chinese/news
### 预期是什么？
正常获取文章
### 实际发生了什么？
报错
### 部署相关信息

官方和自建均有问题，自建已经同步最新主线。

### 额外信息（日志、报错等）

Error: this route is empty, please check the original site or create an issue on https://github.com/DIYgod/RSSHub/issues/new/choose
    at module.exports (/app/lib/middleware/parameter.js:15:15)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/app/lib/middleware/template.js:15:5)
    at async /app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/app/lib/middleware/api-template.js:2:5)
    at async module.exports (/app/lib/middleware/utf8.js:4:5)
    at async module.exports (/app/lib/middleware/debug.js:14:5)
    at async module.exports (/app/lib/middleware/access-control.js:36:13)
    at async module.exports (/app/lib/middleware/header.js:17:5)
    at async module.exports (/app/lib/middleware/onerror.js:5:9)

**Comment by kt286** [comment]
没毛病啊

![image](https://user-images.githubusercontent.com/10684972/62745965-f412da80-ba7f-11e9-8ffe-94b4bb52fffd.png)

**Comment by wym3253** [comment]
现在正常了。
