### ISSUE TITLE
【淘股吧】Bug report——自建和rsshub都失效

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#2819]
### 路由地址

/taoguba/user/:id

### 预期是什么？

正常推送

### 实际发生了什么？

自建
```
RSSHub 发生了一些意外:
Error: wrong path
    at module.exports (～/RSSHub/lib/middleware/parameter.js:11:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

rsshub
```
RSSHub 发生了一些意外:

Error: wrong path
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:11:15)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:36:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:17:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:5:9)
```

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       centos7        |
| Node version       |    v10.16.1           |
| if Docker, version |       null        |

### 额外信息（日志、报错等）

见上，

@emdoe 谢谢🙏

**Comment by kt286** [comment]
@KwToPA 能先认真看完文档再提 issue 么
还有别动不动就瞎@人

**Comment by KwToPA** [comment]
@kt286  不好意思，上面路由手打写错，已改正。 

报错信息两者都变成
```
HTTPError: Response code 403 (Forbidden)
```
应该是被封ip

顺便对作者 @emdoe 说声打扰了

**Comment by emdoe** [comment]
抱歉才看到…有找到问题就好啦 :-)

**Comment by DIYgod** [comment]
抓太多了，限制了下数量 50ed42bd112eebbc41230640e4c0a746a4c84645
