### ISSUE TITLE
【第一财经 - 直播区】Bug Report-自建和rsshub均反馈 options.query.replace is not a function

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#2824]
### 路由地址

/yicai/brief

### 预期是什么？

正常推送

### 实际发生了什么？

自建和rsshub均反馈

```
RSSHub 发生了一些意外:

TypeError: options.query.replace is not a function
    at got.extend.hooks.init (/app/lib/utils/got.js:85:51)
    at normalize (/app/node_modules/got/source/normalize-arguments.js:137:18)
    at got (/app/node_modules/got/source/create.js:32:28)
    at module.exports (/app/lib/routes/yicai/brief.js:11:28)
    at dispatch (/app/node_modules/koa-compose/index.js:44:32)
    at next (/app/node_modules/koa-compose/index.js:45:18)
    at /app/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/app/node_modules/koa-compose/index.js:44:32)
    at /app/node_modules/koa-compose/index.js:36:12
    at dispatch (/app/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/app/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at cache (/app/lib/middleware/cache.js:260:15)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/app/lib/middleware/parameter.js:8:5)
    at async module.exports (/app/lib/middleware/template.js:15:5)
    at async /app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/app/lib/middleware/api-template.js:2:5)
    at async module.exports (/app/lib/middleware/utf8.js:4:5)
    at async module.exports (/app/lib/middleware/debug.js:14:5)
    at async module.exports (/app/lib/middleware/access-control.js:36:13)
    at async module.exports (/app/lib/middleware/header.js:17:5)
    at async module.exports (/app/lib/middleware/onerror.js:5:9)
```

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |          centos7     |
| Node version       |     v10.16.1          |
| if Docker, version |        null       |

### 额外信息（日志、报错等）

报错见上。还有奇怪的现象，在本地ip和开proxy的情况下，第一财经-直播区的此页面[https://www.yicai.com/brief/](https://www.yicai.com/brief/) 是正常推送，此页面[https://www.yicai.com/brief](https://www.yicai.com/brief)最新推送是好几天前的，清除cookies也有此现象。开tor则不会复现。

@sanmmm 谢谢🙏。

**Comment by DIYgod** [comment]
中间件问题，已修复

**Comment by KwToPA** [comment]
@DIYgod 谢谢
