### ISSUE TITLE
Bilibili 用户关注视频动态路由

### ISSUE THREAD

**Issue by StubbornYang** [DIYgod/RSSHub#2853]
使用最新的Cookies获取方式，服务器IP与获取Cookies的IP相同，部署方式为Docker Compose，系统为Ubuntu

> RSSHub 发生了一些意外:
Error: wrong path
    at module.exports (/app/lib/middleware/parameter.js:11:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by DIYgod** [comment]
请按照模板提交 issue
