### ISSUE TITLE
instagram失效

### ISSUE THREAD

**Issue by Mr-Phone** [DIYgod/RSSHub#2910]
### 路由地址
instagram/user

### 实际发生了什么？
原先订阅230个账号，缓存10分钟，正常运行了1个多月
今天，缓存调整到20分钟，换了2个IP，其它不变，运行2多小时就挂了
估计instagram反爬策略升级了

### 部署相关信息
centos 7
node部署
自建

### 额外信息（日志、报错等）
RSSHub 发生了一些意外:
TypeError: Cannot read property '0' of undefined
    at module.exports (/root/RSSHub/lib/routes/instagram/user.js:15:45)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by DIYgod** [comment]
源站反爬，目前无解，自建可以使用动态代理
