### ISSUE TITLE
12306的相关路由无法使用

### ISSUE THREAD

**Issue by umm233** [DIYgod/RSSHub#2923]
### 路由地址
`/12306/zxdt/:id?`
访问链接：https://rsshub.app/12306/zxdt

### 预期是什么？
12306公告的最新动态

### 实际发生了什么？
直接报错

### 额外信息（日志、报错等）
```
TypeError: Cannot read property 'trim' of null
    at /data/wwwroot/rsshub.app/lib/routes/12306/zxdt.js:57:21
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Promise.all (index 17)
    at async module.exports (/data/wwwroot/rsshub.app/lib/routes/12306/zxdt.js:38:17)
    at async cache (/data/wwwroot/rsshub.app/lib/middleware/cache.js:262:9)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:36:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:5:9)
```

**Comment by umm233** [comment]
不加参数已经可以使用，但加上路由参数，出现类似问题，如访问https://rsshub.app/12306/zxdt/4


```
TypeError: Cannot read property 'trim' of null at /app/lib/routes/12306/zxdt.js:57:21 at runMicrotasks () at processTicksAndRejections (internal/process/task_queues.js:85:5) at async Promise.all (index 19) at async module.exports (/app/lib/routes/12306/zxdt.js:38:17) at async cache (/app/lib/middleware/cache.js:262:9) at async module.exports (/app/lib/middleware/parameter.js:8:5) at async module.exports (/app/lib/middleware/template.js:15:5) at async /app/lib/middleware/api-response-handler.js:143:9 at async module.exports (/app/lib/middleware/api-template.js:2:5) at async module.exports (/app/lib/middleware/utf8.js:4:5) at async module.exports (/app/lib/middleware/debug.js:14:5) at async module.exports (/app/lib/middleware/access-control.js:36:13) at async module.exports (/app/lib/middleware/header.js:20:5) at async module.exports (/app/lib/middleware/onerror.js:5:9)
```

对于没有动态（内容）的页面，直接报错，如访问 https://rsshub.app/12306/zxdt/3

```
Error: this route is empty, please check the original site or create an issue on https://github.com/DIYgod/RSSHub/issues/new/choose at module.exports (/app/lib/middleware/parameter.js:15:15) at runMicrotasks () at processTicksAndRejections (internal/process/task_queues.js:85:5) at async module.exports (/app/lib/middleware/template.js:15:5) at async /app/lib/middleware/api-response-handler.js:143:9 at async module.exports (/app/lib/middleware/api-template.js:2:5) at async module.exports (/app/lib/middleware/utf8.js:4:5) at async module.exports (/app/lib/middleware/debug.js:14:5) at async module.exports (/app/lib/middleware/access-control.js:36:13) at async module.exports (/app/lib/middleware/header.js:20:5) at async module.exports (/app/lib/middleware/onerror.js:5:9)
```

**Comment by umm233** [comment]
@DIYgod
