### ISSUE TITLE
I couldn't get any Instagram feed

### ISSUE THREAD

**Issue by volrath73** [DIYgod/RSSHub#2965]
### Involved route
/instagram/user/:id

### What is expected?
Get Instagram feed.

### What is actually happening?
No RSS feed output.

### Additional info (logs errors etc)

> RSSHub 发生了一些意外:
TypeError: Cannot read property '0' of undefined
    at module.exports (/app/lib/routes/instagram/user.js:15:45)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async cache (/app/lib/middleware/cache.js:262:9)
    at async module.exports (/app/lib/middleware/parameter.js:7:5)
    at async module.exports (/app/lib/middleware/template.js:15:5)
    at async /app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/app/lib/middleware/api-template.js:2:5)
    at async module.exports (/app/lib/middleware/utf8.js:4:5)
    at async module.exports (/app/lib/middleware/debug.js:14:5)
    at async module.exports (/app/lib/middleware/access-control.js:36:13)
    at async module.exports (/app/lib/middleware/header.js:20:5)
    at async module.exports (/app/lib/middleware/onerror.js:5:9)

**Comment by HenryQW** [comment]
It would be very wise to:

1. Read the documentation, especially the FAQ section: 

Q: Can I use the demo instance？

A: rsshub.app is the demo instance provided, running the latest build of RSSHub from master branch, the cache is set 20 minutes and it's free to use. However, popular websites such as Instagram and YouTube etc. may pose a request quota on individual IP address, which means it can get unreliable from time to time for the demo instance. You are encouraged to host your own RSSHub instance for a better usability.

We all learned hard that a few hours of trial and error can save you several minutes of looking at the documentation.

2. Search for existing issues before opening a new one, the answer to your question might likely be there. This saves everyone “several minutes” so that we can all focus on reading more documentations.
