### ISSUE TITLE
新京报rss从8月30日起无法打开

### ISSUE THREAD

**Issue by Huang-CL** [DIYgod/RSSHub#2977]
### 路由地址
新京报rss，比如
https://rsshub.app/bjnews/realtime

### 预期是什么？
正常rss编码

### 实际发生了什么？
经过长时间加载之后显示以下错误信息

RSSHub 发生了一些意外:

RequestError: connect ETIMEDOUT 116.207.118.76:80
    at ClientRequest. (/data/wwwroot/rsshub.app/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:291:20)
    at ClientRequest.emit (events.js:208:15)
    at ClientRequest.origin.emit (/data/wwwroot/rsshub.app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at Socket.socketErrorListener (_http_client.js:402:9)
    at Socket.emit (events.js:203:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

**Comment by kt286** [comment]
@DIYgod @Huang-CL 现在可以了

**Comment by Huang-CL** [comment]
确实可以了。非常感谢这么快就解决了问题！
