### ISSUE TITLE
Instagram用户内容无法抓取

### ISSUE THREAD

**Issue by KumazakiRyoha** [DIYgod/RSSHub#3013]
### 路由地址
举例: https://rsshub.app/instagram/user/diygod
路由: /instagram/user/:id
### 预期是什么？
根据用户id订阅instagram
### 实际发生了什么？
TypeError: Cannot read property '0' of undefined
    at module.exports (/data/wwwroot/rsshub.app/lib/routes/instagram/user.js:15:45)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async cache (/data/wwwroot/rsshub.app/lib/middleware/cache.js:262:9)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:7:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:36:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:18:9)
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by kt286** [comment]
能先搜一下历史 issue 么
https://github.com/DIYgod/RSSHub/issues?utf8=%E2%9C%93&q=is%3Aissue+Instagram
