### ISSUE TITLE
Zaker不能工作

### ISSUE THREAD

**Issue by hankcjl** [DIYgod/RSSHub#3040]
### 路由地址
https://rsshub.app/zaker/channel/13
https://rsshub.app/zaker/source/12291
### 预期是什么？
获取对应的rss信息
### 实际发生了什么？
报错
### 部署相关信息
是演示地址(rsshub.app
### 额外信息（日志、报错等）
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:15:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:36:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)
For online documentation and support please refer to docs.rsshub.app.

**Comment by muzea** [comment]
应该是 myzaker 改版，页面结构变了，等一个好心人。
