### ISSUE TITLE
后续（https://houxu.app）路由部分损坏

### ISSUE THREAD

**Issue by Maecenas** [DIYgod/RSSHub#3061]
### 路由地址

[路由](https://docs.rsshub.app/new-media.html#live)：`/houxu/live/:id/:timeline?`
举例：<https://rsshub.app/houxu/live/5/original>

### 预期是什么？

正常解析

### 实际发生了什么？

路由报错

### 额外信息（日志、报错等）

```
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:15:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:36:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)
```

**Comment by xyqfer** [comment]
https://houxu.app/lives/5 话说是网站改版了吗？没找到有设置/过滤 timeline 的地方...

**Comment by kt286** [comment]
应该是
