### ISSUE TITLE
明明反馈Process successfully started，却部署失败（通过镜像恢复，解决问题。估计是9月20日提交的rsshub 有些问题）

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3123]
用的安装脚本之前都可以成功部署，突然发现路由全挂，ip:port 无法打开。

pm2 stop rsshub ， pm2 restart rsshub 也无法成功启动

反馈
```

[PM2] Applying action stopProcessId on app [rsshub](ids: 0)
[PM2] [rsshub](0) ✓
┌──────────┬────┬─────────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user │ watching │
├──────────┼────┼─────────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────┼──────────┤
│ rsshub   │ 0  │ 0.1.1   │ fork │ 0   │ stopped │ 518     │ 0      │ 0%  │ 0 B    │ root │ disabled │
└──────────┴────┴─────────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
Cloning into 'RSSHub'...
yarn install v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
Done in 97.22s.
[PM2] Applying action restartProcessId on app [rsshub](ids: 0)
[PM2] [rsshub](0) ✓
[PM2] Process successfully started
┌──────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├──────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ rsshub   │ 0  │ 0.1.1   │ fork │ 26498 │ online │ 518     │ 0s     │ 0%  │ 21.4 MB   │ root │ disabled │
└──────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

pm2 show rsshub
```
 Describing process with id 0 - name rsshub 
┌───────────────────┬──────────────────────────────────┐
│ status            │ errored                          │
│ name              │ rsshub                           │
│ version           │ 0.1.1                            │
│ restarts          │ 533                              │
│ uptime            │ 0                                │
│ script path       │ ~/RSSHub/lib/index.js     │
│ script args       │ N/A                              │
│ error log path    │ /root/.pm2/logs/rsshub-error.log │
│ out log path      │ /root/.pm2/logs/rsshub-out.log   │
│ pid path          │ /root/.pm2/pids/rsshub-0.pid     │
│ interpreter       │ node                             │
│ interpreter args  │ N/A                              │
│ script id         │ 0                                │
│ exec cwd          │ ~                         │
│ exec mode         │ fork_mode                        │
│ node.js version   │ 10.16.1                          │
│ node env          │ N/A                              │
│ watch & reload    │ ✘                                │
│ unstable restarts │ 0                                │
│ created at        │ N/A                              │
└───────────────────┴──────────────────────────────────┘
```

show logs rsshub 
```
0|rsshub   | TypeError: Cannot read property 'loggerLevel' of undefined
0|rsshub   |     at Object.<anonymous> (~/RSSHub/lib/utils/logger.js:5:19)
0|rsshub   |     at Module._compile (internal/modules/cjs/loader.js:778:30)
0|rsshub   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
0|rsshub   |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|rsshub   |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|rsshub   |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|rsshub   |     at Module.require (internal/modules/cjs/loader.js:692:17)
0|rsshub   |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:70:37)
0|rsshub   |     at require (internal/modules/cjs/helpers.js:25:18)
0|rsshub   |     at Object.<anonymous> (~/RSSHub/lib/utils/request-wrapper.js:4:16)
```

pm2 stop rsshub
```
[PM2] Applying action stopProcessId on app [rsshub](ids: 0)
[PM2] [rsshub](0) ✓
┌──────────┬────┬─────────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ user │ watching │
├──────────┼────┼─────────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────┼──────────┤
│ rsshub   │ 0  │ 0.1.1   │ fork │ 0   │ stopped │ 549     │ 0      │ 0%  │ 0 B    │ root │ disabled │
└──────────┴────┴─────────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

pm2 restart rsshub
```
Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [rsshub](ids: 0)
[PM2] [rsshub](0) ✓
┌──────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬─────┬──────────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem      │ user │ watching │
├──────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼─────┼──────────┼──────┼──────────┤
│ rsshub   │ 0  │ 0.1.1   │ fork │ 28557 │ online │ 549     │ 0s     │ 0%  │ 6.0 MB   │ root │ disabled │
└──────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴─────┴──────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

### 谢谢

**Comment by KwToPA** [comment]
是手动部署 
系统： centos 7
yarn: v1.17.3
---
通过镜像恢复，解决问题。估计是昨天提交的rsshub 有些问题

**Comment by KwToPA** [comment]
@DIYgod

**Comment by DIYgod** [comment]
无法复现，检查下是否修改了某些文件？

**Comment by KwToPA** [comment]
> 无法复现，检查下是否修改了某些文件？

没有修改文件，脚本逻辑基本上就是删除，重新git，安装
rm -rf rsshub
git clone
yarn

我是每天凌晨自动git一遍，今天挂了，我用20日凌晨的rsshub 文件夹替换21日（今天）的，再重新yarn就解决了

**Comment by KwToPA** [comment]
文件夹替换完成后，我把 rm -rf rsshub ， git clone 这两句注释掉，用同一个脚本执行的

**Comment by DIYgod** [comment]
可以正常使用的 `20日凌晨的rsshub 文件夹` 具体版本号是多少？首页 debug 信息里可以看到

**Comment by KwToPA** [comment]
> 可以正常使用的 `20日凌晨的rsshub 文件夹` 具体版本号是多少？首页 debug 信息里可以看到

我用pm2 show rsshub 看了看，估计是这个
```
┌──────────────────┬──────────────────────────────────────────┐
│ revision control │ git                                      │
│ remote url       │ https://github.com/DIYgod/RSSHub.git     │
│ repository root  │ ～/RSSHub                          │
│ last update      │ 2019-09-21T07:34:53.764Z                 │
│ revision         │ 3973071c11f9791f3b34f696c1fefa6d2d78aef1 │
│ comment          │ feat: add 网易号 (#3087)                    │
│                  │                                          │
                      │Update router.js
                                        │
                   │ * Update new-media.md
                                        │
│                  │ * Create dy.js                           │
│ branch           │ master                                   │
```

根据网易号，这个版本应该是 Sep 15, 2019 的

我用原镜像重新开了一台机器，用相同脚本更新到最新版本
```
 Revision control metadata 
┌──────────────────┬──────────────────────────────────────────────────────────────────────────┐
│ revision control │ git                                                                      │
│ remote url       │ https://github.com/DIYgod/RSSHub.git                                     │
│ repository root  │ /var/www/RSSHub                                                          │
│ last update      │ 2019-09-21T10:30:18.663Z                                                 │
│ revision         │ a302620469e7c47e1c95ce3b6034776a1301c58b                                 │
│ comment          │ Merge pull request #3121 from DIYgod/dependabot/npm_and_yarn/nock-11.3.5 │
│ branch           │ master                                                                   │
└──────────────────┴──────────────────────────────────────────────────────────────────────────┘
```
ip:port就打不开了，原镜像不更新时可以正常工作

**Comment by KwToPA** [comment]
重新弄了，首先现实的确是 git hash:   3973071
---
https://github.com/DIYgod/RSSHub/blob/master/lib/config.js
```
        // 是否显示 Debug 信息，取值 boolean 'false' 'key' ，取值为 'false' false 时永远不显示，取值为 'key' 时带上 ?debug=key 显示
```

这边注释是不是漏了 true ？

**Comment by KwToPA** [comment]
首页显示

**Comment by KwToPA** [comment]
重新用yarn试了下，发现  Revision control metadata  都没了，只有

pm2 show rsshub

```
Describing process with id 0 - name rsshub 
┌───────────────────┬──────────────────────────────────┐
│ status            │ errored                          │
│ name              │ rsshub                           │
│ version           │ 0.1.1                            │
│ restarts          │ 184                              │
│ uptime            │ 0                                │
│ script path       │~/RSSHub/lib/index.js     │
│ script args       │ N/A                              │
│ error log path    │ /root/.pm2/logs/rsshub-error.log │
│ out log path      │ /root/.pm2/logs/rsshub-out.log   │
│ pid path          │ /root/.pm2/pids/rsshub-0.pid     │
│ interpreter       │ node                             │
│ interpreter args  │ N/A                              │
│ script id         │ 0                                │
│ exec cwd          │ ~                         │
│ exec mode         │ fork_mode                        │
│ node.js version   │ 10.16.1                          │
│ node env          │ N/A                              │
│ watch & reload    │ ✘                                │
│ unstable restarts │ 0                                │
│ created at        │ N/A                              │
└───────────────────┴──────────────────────────────────┘
```
其他反馈都相同。

---
用sudo npm install 安装，报错
```
../src/common.cc:25:22: fatal error: vips/vips8: No such file or directory
```

**Comment by kt286** [comment]
@KwToPA 新版本配置文件有修改，你把原来的相关修改重改一下，不要用原来那个文件覆盖新文件

**Comment by KwToPA** [comment]
> @KwToPA 新版本配置文件有修改，你把原来的相关修改重改一下，不要用原来那个文件覆盖新文件

换成新的config.js 弄好了，谢谢
