### ISSUE TITLE
【/cctv/:category】Bug Report——自建和rsshub均报错:SyntaxError: Unexpected token 和 Response code 404 (Not Found)

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3161]
### 路由地址
/cctv/:category
### 预期是什么？
正常推送
### 实际发生了什么？
报错
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
自建反馈
```
SyntaxError: Unexpected token ) in JSON at position 39599
    at JSON.parse ()
    at module.exports (～/RSSHub/lib/routes/cctv/utils/news.js:15:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

rsshub反馈
```
SyntaxError: Unexpected token ) in JSON at position 39807
    at JSON.parse ()
    at module.exports (/data/wwwroot/rsshub.app/lib/routes/cctv/utils/news.js:15:23)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/routes/cctv/category.js:12:24)
    at async cache (/data/wwwroot/rsshub.app/lib/middleware/cache.js:258:9)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)
```

**Comment by KwToPA** [comment]
ttrss上 反馈 ```HTTP/1.1 404 Not Found```

**Comment by KwToPA** [comment]
有出现了，自建的最新的一条是
奋斗是新时代最美的姿态，29日的新闻

**Comment by KwToPA** [comment]
报错变成了 
```
SyntaxError: Unexpected token ) in JSON at position 39425
```

**Comment by KwToPA** [comment]
上面是 中国板块 /cctv/china  的报错

新闻联播 /cctv/xwlb 自建和rsshub 均 报错
```
Error in /cctv/xwlb: Response code 404 (Not Found): target website might be blocking our access, you can <a href="https://docs.rsshub.app/install/">host your own RSSHub instance</a> for a better usability.
```
问题是我新开一台能ping 通的机器也是这样

**Comment by hoilc** [comment]
![image](https://user-images.githubusercontent.com/9067094/66032343-d5890700-e537-11e9-9fdc-69b0846aa00e.png)
![image](https://user-images.githubusercontent.com/9067094/66032389-e5a0e680-e537-11e9-829c-1d5d4724a3db.png)
这边本地和RSSHUB都工作正常，最近修复参见https://github.com/DIYgod/RSSHub/issues/3050

**Comment by KwToPA** [comment]
> ![image](https://user-images.githubusercontent.com/9067094/66032343-d5890700-e537-11e9-9fdc-69b0846aa00e.png)
> ![image](https://user-images.githubusercontent.com/9067094/66032389-e5a0e680-e537-11e9-829c-1d5d4724a3db.png)
> 这边本地和RSSHUB都工作正常，最近修复参见#3050

建议等等，这个现象我这边时隐时现。昨天突然好了，一会儿又报错

**Comment by KwToPA** [comment]
此刻这两个路由在我的机器上就是好的，到时候碰到红了我再at你
