### ISSUE TITLE
【/cninfo/announcement/:code/:category?】Bug Report-其中code填写all，在自建和rsshub均报错

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#3162]
### 路由地址
/cninfo/announcement/:code/:category?
### 预期是什么？
参数有效
### 实际发生了什么？
参数部分无效

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）

Rsshub 反馈
```
Error: this route is empty, please check the original site or create an issue
    at module.exports (/app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/app/lib/middleware/template.js:15:5)
    at async /app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/app/lib/middleware/api-template.js:2:5)
    at async module.exports (/app/lib/middleware/utf8.js:4:5)
    at async module.exports (/app/lib/middleware/debug.js:14:5)
    at async module.exports (/app/lib/middleware/access-control.js:29:13)
    at async module.exports (/app/lib/middleware/header.js:20:5)
    at async module.exports (/app/lib/middleware/onerror.js:20:9)
```

自建
```
Error: this route is empty, please check the original site or create an issue
    at module.exports (～/RSSHub/lib/middleware/parameter.js:19:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

若参数code填写股票代码，则能成功推送内容。

---

### 谢谢

**Comment by KwToPA** [comment]
ttrss上 反馈 ```HTTP/1.1 404 Not Found```

**Comment by KwToPA** [comment]
在code后加上 category? 则可以正常推送，但是文档中写
```
category, 可选 - 公告分类，对A股有效如 gqjl 表示 股权激励 分类 
```
而且我记忆中，之间测试是可以不加category

**Comment by KwToPA** [comment]
突然就恢复了
