### ISSUE TITLE
Github issues: this route is empty

### ISSUE THREAD

**Issue by max-arnold** [DIYgod/RSSHub#3182]
### Involved route

https://rsshub.app/github/issue/saltstack/salt-jenkins

### What is expected?

An RSS feed for the following issue tracker: https://github.com/saltstack/salt-jenkins/issues

### What is actually happening?

A 404 page with the following traceback:

```
Looks like something went wrong

Error: this route is empty, please check the original site or create an issue
    at module.exports (/app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/app/lib/middleware/template.js:15:5)
    at async /app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/app/lib/middleware/api-template.js:2:5)
    at async module.exports (/app/lib/middleware/utf8.js:4:5)
    at async module.exports (/app/lib/middleware/debug.js:14:5)
    at async module.exports (/app/lib/middleware/access-control.js:29:13)
    at async module.exports (/app/lib/middleware/header.js:20:5)
    at async module.exports (/app/lib/middleware/onerror.js:20:9)
```

**Comment by yefoenix** [comment]
似乎 增加一个 allow empty 就好了？
