### ISSUE TITLE
/t66y/7 404错误

### ISSUE THREAD

**Issue by librix** [DIYgod/RSSHub#3226]
### 路由地址
/t66y/7
### 预期是什么？
200 ok
### 实际发生了什么？
404 error

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |     windows Version 10.0.10240        |
| Node version       |     v12.10.0         |

### 额外信息（日志、报错等）

```
info: Proxy for http://www.t66y.com/thread0806.php?fid=7&search=today
error: Error in /t66y/7: Error: this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create an issue</a>
    at module.exports (D:\github\npmdir\RSSHub\lib\middleware\parameter.js:15:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (D:\github\npmdir\RSSHub\lib\middleware\template.js:15:5)
    at async D:\github\npmdir\RSSHub\lib\middleware\api-response-handler.js:143:9
    at async module.exports (D:\github\npmdir\RSSHub\lib\middleware\api-template.js:2:5)
    at async module.exports (D:\github\npmdir\RSSHub\lib\middleware\utf8.js:4:5)
    at async module.exports (D:\github\npmdir\RSSHub\lib\middleware\debug.js:14:5)
    at async module.exports (D:\github\npmdir\RSSHub\lib\middleware\access-control.js:36:13)
    at async module.exports (D:\github\npmdir\RSSHub\lib\middleware\header.js:20:5)
    at async module.exports (D:\github\npmdir\RSSHub\lib\middleware\onerror.js:20:9)
```

检查 `RSSHub\lib\routes\t66y\`下存在 `post.js` 和 `index.js` 文件，2019-9-12 修改，6k大小。
存在语句：
```
router.get('/t66y/post/:tid', require('./routes/t66y/post'));
router.get('/t66y/:id/:type?', require('./routes/t66y/index'));
```

**Comment by DIYgod** [comment]
无法复现，可能网络问题

**Comment by kt286** [comment]
墙内本地挂梯子，浏览器可以访问  但是rsshub获取不到
墙外服务器没有问题

**Comment by librix** [comment]
> 无法复现，可能网络问题

但是存在
info: Proxy for http://www.t66y.com/thread0806.php?fid=7&search=today
说明代理配置正确呀。

**Comment by yefoenix** [comment]
@librix 其他需要代理的路由可以正常抓取吗？

**Comment by librix** [comment]
> 代理的路由可以正常

推特没有问题，我写的代理规则是：
```
url_regex: process.env.PROXY_URL_REGEX || '(twitter)|(github)|(twimg)|(amazonaws)|(t66y\.com)',
```
