### ISSUE TITLE
移动支付网源失效

### ISSUE THREAD

**Issue by luojianxhlxt** [DIYgod/RSSHub#3268]
### 路由地址
https://rsshub.app/mpaypass/news
### 预期是什么？
正常工作
### 实际发生了什么？
拉取失败，报错
### 额外信息（日志、报错等）
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:19:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)
For online documentation and support please refer to docs.rsshub.app.

**Comment by zhuan-zhu** [comment]
推荐使用移动支付网 分类源，原新闻源主要来源微信端，分类源来自web端。
https://rsshub.app/mpaypass/main
