### ISSUE TITLE
[ERROR]https://rsshub.app/smzdm/ranking/dianshang/32/3

### ISSUE THREAD

**Issue by ccinoo** [DIYgod/RSSHub#3330]
### 路由地址
https://rsshub.app/smzdm/ranking/dianshang/32/3
### 预期是什么？
正常 rss源返回
### 实际发生了什么？
￼返回报错

Looks like something went wrong

Error: this route is empty, please check the original site or create an issue at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:19:19) at processTicksAndRejections (internal/process/task_queues.js:85:5) at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5) at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9 at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5) at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5) at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5) at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13) at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5) at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)

For online documentation and support please refer
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
￼

Looks like something went wrong

Error: this route is empty, please check the original site or create an issue at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:19:19) at processTicksAndRejections (internal/process/task_queues.js:85:5) at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5) at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9 at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5) at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5) at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5) at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13) at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5) at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)

For online documentation and support please refer

**Comment by Jeason0228** [comment]
自建正常
![企业微信截图_20191030132254](https://user-images.githubusercontent.com/44083849/67831382-1d8c5100-fb19-11e9-8b65-90ad66a3fc96.png)
