### ISSUE TITLE
今日头条关键词不支持中文搜索

### ISSUE THREAD

**Issue by eric1932** [DIYgod/RSSHub#3409]
### 路由地址
https://rsshub.app/jinritoutiao/keyword/量子位
https://rsshub.app/jinritoutiao/keyword/%E9%87%8F%E5%AD%90%E4%BD%8D
### 预期是什么？
rss 订阅信息
### 实际发生了什么？
Error: this route is empty
### 部署相关信息
Docker compose; 使用 rsshub.app 也会出现同样问题

### 额外信息（日志、报错等）
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:19:19)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by DIYgod** [comment]
无法复现

**Comment by eric1932** [comment]
又试了一下，的确可以了
