### ISSUE TITLE
“湖南省政府采购网”RSS源报错

### ISSUE THREAD

**Issue by 07382359** [DIYgod/RSSHub#3488]
### 路由地址
https://rsshub.app/gov/hunan/notice/all
### 预期是什么？
正常输出RSS订阅数据。
### 实际发生了什么？
报错，无法正常获取RSS数据。
### 部署相关信息
开发者@Jeason0228 才能回答这个问题……

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
以下为页面上的错误提示：
Looks like something went wrong
TypeError: Cannot read property 'map' of undefined
    at module.exports (/data/wwwroot/rsshub.app/lib/routes/gov/hunan/notice.js:73:55)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async cache (/data/wwwroot/rsshub.app/lib/middleware/cache.js:203:9)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by Jeason0228** [comment]
@Bright-W 感谢修复~!

**Comment by Bright-W** [comment]
@Jeason0228 貌似如果是1月的话, start date 的格式也会出错. 刚发现的.

**Comment by Jeason0228** [comment]
javascript 新手  忘记了这个月份的坑是从0开始算的0 0.
麻烦你再改改提交吧

**Comment by Jeason0228** [comment]
返回查询的数据不太对？ 全是重复的 奇怪~

**Comment by Bright-W** [comment]
你的cache key有问题, 都是同样的key. 
应该用item.NOTICE_ID 做key
