### ISSUE TITLE
演示地址的 App Store 内购限免提醒只有文档里写的那个打开，换别的 app 都不行

### ISSUE THREAD

**Issue by lucky13820** [DIYgod/RSSHub#3490]
### 路由地址
https://rsshub.app/appstore/iap/ca/id1191337894

### 预期是什么？
打开能显示 app 的内购限免信息

### 实际发生了什么？
显示 route is empty，我试了好几个有内购的 app 都不行，只有文档里写的 Darkroom 的可以。

### 部署相关信息
官方演示地址

### 额外信息（日志、报错等）
```
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)
```

**Comment by HenryQW** [comment]
不知道为什么苹果的 API 返回的数据格式不统一，有些 app 可以， 有些 app 内购项目是空值，有空再修复。
![image](https://user-images.githubusercontent.com/5896343/69591233-00e51b00-0fea-11ea-94f5-565c3f1dfb66.png)

**Comment by iedkujqmbly** [comment]
我提的#3509被合并到这里了。HenryQW加油啊！

**Comment by iedkujqmbly** [comment]
我之前反映的 #3509 问题依然没有解决。https://rsshub.app/appstore/iap/cn/id1472328263
报告如下错误：

Looks like something went wrong
TypeError: Cannot read property 'url' of undefined
    at /data/wwwroot/rsshub.app/lib/routes/apple/appstore/in-app-purchase.js:47:103
    at Array.map ()
    at module.exports (/data/wwwroot/rsshub.app/lib/routes/apple/appstore/in-app-purchase.js:42:20)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async cache (/data/wwwroot/rsshub.app/lib/middleware/cache.js:203:9)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by lucky13820** [comment]
没错，我也遇到这个问题了，`TypeError: Cannot read property 'url' of undefined`

**Comment by DIYgod** [comment]
fixed in #3574
