### ISSUE TITLE
Instagram 无法抓取

### ISSUE THREAD

**Issue by ljxsz** [DIYgod/RSSHub#3512]
### 路由地址
http://ljxsz.me:1200/instagram/user/ljxsz

### 预期是什么？
抓取instagram用户ljxsz的seed

### 实际发生了什么？

seed无法显示

TypeError: Cannot read property '0' of undefined
    at module.exports (/app/lib/routes/instagram/user.js:15:45)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |  Synology DSM 6.2.2 Update 4             |
| Node version       |     10.15.3          |
| if Docker, version |        18.09       |

### 额外信息（日志、报错等）

TypeError: Cannot read property '0' of undefined
    at module.exports (/app/lib/routes/instagram/user.js:15:45)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by dabo-t** [comment]
订阅了太多账户，instagram反爬了

**Comment by ljxsz** [comment]
收到，多谢！
