### ISSUE TITLE
部分知乎专栏报错

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [DIYgod/RSSHub#3558]
### 路由地址
https://rsshub.app/zhihu/zhuanlan/Vinzent
https://rsshub.app/zhihu/zhuanlan/c_119395780
https://rsshub.app/zhihu/zhuanlan/c_1052862727860699136
### 预期是什么？
返回rss页
### 实际发生了什么？
TypeError: Cannot read property 'map' of undefined
    at module.exports (/data/wwwroot/rsshub.app/lib/routes/zhihu/zhuanlan.js:37:14)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async cache (/data/wwwroot/rsshub.app/lib/middleware/cache.js:203:9)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by DIYgod** [comment]
知乎反爬，请自建
