### ISSUE TITLE
一禁止缓存就报错？

### ISSUE THREAD

**Issue by ClarkeCheng** [DIYgod/RSSHub#367]
在config.js第6行，我把
```
cacheType: process.env.CACHE_TYPE || 'memory', // 缓存类型，支持 'memory' 和 'redis'，设为空可以禁止缓存
```
改成
```
cacheType: process.env.CACHE_TYPE || '', // 缓存类型，支持 'memory' 和 'redis'，设为空可以禁止缓存
```
或
```
cacheType: process.env.CACHE_TYPE || null, // 缓存类型，支持 'memory' 和 'redis'，设为空可以禁止缓存
```
访问UP 主投稿路由，如`/bilibili/user/video/2`就报错
```
RSSHub 发生了一些意外:
TypeError: Cannot read property 'get' of undefined
    at Object.getUsernameFromUID (/root/RSSHub/routes/bilibili/cache.js:10:36)
    at module.exports (/root/RSSHub/routes/bilibili/video.js:7:30)
    at dispatch (/root/RSSHub/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/root/RSSHub/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /root/RSSHub/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/root/RSSHub/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /root/RSSHub/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/root/RSSHub/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/root/RSSHub/node_modules/koa-compose/index.js:42:32)
    at module.exports (/root/RSSHub/middleware/filter.js:2:11)
    at dispatch (/root/RSSHub/node_modules/koa-compose/index.js:42:32)
    at module.exports (/root/RSSHub/middleware/template.js:10:11)
    at dispatch (/root/RSSHub/node_modules/koa-compose/index.js:42:32)
    at module.exports (/root/RSSHub/middleware/utf8.js:4:11)
    at dispatch (/root/RSSHub/node_modules/koa-compose/index.js:42:32)
    at module.exports (/root/RSSHub/middleware/debug.js:17:11)
```
但是我订阅的其他路由却是正常的。

**Comment by DIYgod** [comment]
@ClarkeCheng 是 bug

**Comment by DIYgod** [comment]
Fixed. e507ac46eabade91279300aeb7b74ad1a30a251c
