### ISSUE TITLE
Acfun 许多番剧订阅失效

### ISSUE THREAD

**Issue by Firesocks** [DIYgod/RSSHub#3690]
### 路由地址
https://rsshub.app/acfun/bangumi/6000686
### 预期是什么？
订阅瑞克和莫蒂
### 实际发生了什么？
订阅失败
我尝试了大概5-6个番剧也都订阅失败，瑞克和莫蒂我已经尝试了三天都是报错。

### 额外信息（日志、报错等）
SyntaxError: Unexpected end of JSON input
    at JSON.parse ()
    at module.exports (/data/wwwroot/rsshub.app/lib/routes/acfun/bangumi.js:14:28)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async cache (/data/wwwroot/rsshub.app/lib/middleware/cache.js:203:9)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by DIYgod** [comment]
#3700
