### ISSUE TITLE
Google Scholar 的RSS不工作

### ISSUE THREAD

**Issue by Hermittttt** [DIYgod/RSSHub#3692]
### 路由地址
/google/scholar/:query
### 预期是什么？
预期演示地址 https://rsshub.app/google/scholar/data+visualization 能够连接
### 实际发生了什么？
无法连接，不是403错误，显示空路由
### 额外信息（日志、报错等）
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by umm233** [comment]
这个路由在本地跑没问题，估计是被反爬了

**Comment by Hermittttt** [comment]
感谢回应
如果是因为反爬没有办法解决的话需要关闭这个issue吗？
