### ISSUE TITLE
看雪的WEB精华帖抓取失败

### ISSUE THREAD

**Issue by argzs** [DIYgod/RSSHub#3872]
### 路由地址
https://rsshub.app/pediy/topic/web/digest

### 预期是什么？
正常返回精华帖子

### 实际发生了什么？
Looks like something went wrong

### 额外信息（日志、报错等）
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by hoilc** [comment]
确认路由没有问题，只是该板块限制非登陆用户，精华帖为空

![image](https://user-images.githubusercontent.com/9067094/73861616-3d4db680-4878-11ea-93a7-9f1dad1a4cea.png)

测试另一板块精华主题如下

![image](https://user-images.githubusercontent.com/9067094/73861767-77b75380-4878-11ea-8697-32c950770c53.png)
