### ISSUE TITLE
一个路由异常

### ISSUE THREAD

**Issue by ljh740** [DIYgod/RSSHub#4024]
### 路由地址
https://rsshub.app/discuz/x/https%3A%2F%2Fwww.52pojie.cn%2Fforum-21-1.html
### 预期是什么？
https://www.52pojie.cn/forum-21-1.html
### 实际发生了什么？
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/rsshub.app/lib/middleware/onerror.js:20:9)
### 额外信息（日志、报错等）
https://rsshub.app/discuz/x/https%3A%2F%2Fwww.52pojie.cn%2Fforum-16-1.html 有效
https://rsshub.app/discuz/x/https%3A%2F%2Fwww.52pojie.cn%2Fforum-21-1.html 报错
这是为什么?

**Comment by junfengP** [comment]
https://www.52pojie.cn/forum-21-1.html

![image](https://user-images.githubusercontent.com/15406392/74797644-8ab13580-5306-11ea-9590-c3e98d36d7ac.png)
