### ISSUE TITLE
色花堂出错

### ISSUE THREAD

**Issue by ly012** [DIYgod/RSSHub#4043]
### 路由地址
/dsndsht23/gqzwzm
### 预期是什么？
正常使用
### 实际发生了什么？
Looks like something went wrong
MaxRedirectsError: Redirected 10 times. Aborting.
    at ClientRequest.handleResponse (/app/node_modules/got/dist/source/request-as-event-emitter.js:102:31)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:323:22)
    at ClientRequest.EventEmitter.emit (domain.js:482:12)
    at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/index.js:41:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:476:22)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket.EventEmitter.emit (domain.js:482:12)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 | Ubuntu 18.04.4 LTS |
| Node version       |               |
| if Docker, version | 19.03.6 |

**Comment by hoilc** [comment]
@ly012 反爬了吧🤪

**Comment by junfengP** [comment]
首页被套了一层保护，需要浏览器点击，跳转至https://www.22tang.me/，把地址改成这个就可以了

**Comment by junfengP** [comment]
论坛开放了RSS，只是不支持BT
![image](https://user-images.githubusercontent.com/15406392/74906745-dd651d00-53ec-11ea-839c-7ffb7d74bd06.png)

不过这个RSS用浏览器、wget、postman都可以正常访问。
但是curl和ttrss会显示`HTTP 302`, FeedDemon也是报错订阅不了。

**Comment by junfengP** [comment]
> 首页被套了一层保护，需要浏览器点击，跳转至[https://www.22tang.me/，把地址改成这个就可以了](https://www.22tang.me/%EF%BC%8C%E6%8A%8A%E5%9C%B0%E5%9D%80%E6%94%B9%E6%88%90%E8%BF%99%E4%B8%AA%E5%B0%B1%E5%8F%AF%E4%BB%A5%E4%BA%86)

不对，好像是被套了CF保护

**Comment by DarkAge2018** [comment]
@junfengP 用feedly订阅，发现最近中字板块都是稳定更新11部片子，如果多余11部，就会漏掉最前面更新的几部。素人以及亚洲有码都有这个问题。不知道是feedly抓取，还是源的问题。刚好源挂了，来不及测试其他阅读器。

**Comment by junfengP** [comment]
> @junfengP 用feedly订阅，发现最近中字板块都是稳定更新11部片子，如果多余11部，就会漏掉最早更新的几部。素人以及亚洲有码也都有这个问题。不知道是feedly抓取，还是源的问题。刚好源挂了，来不及测试其他阅读器。

色花堂属于短时间放出大量新文章。
路由内设定单次抓取11篇文章，所以论坛短时间放出超过11篇文章就会丢失部分。
一次抓取大量文章对于RSSHub其他路由以及源站会带来影响，所以没有增加抓取数量。
<br>
解决方案：
1. 自建，并修改源码抓取数量
2. 修改阅读器更新时间到 15分钟

**Comment by 100001000** [comment]
> > @junfengP 用feedly订阅，发现最近中字板块都是稳定更新11部片子，如果多余11部，就会漏掉最早更新的几部。素人以及亚洲有码也都有这个问题。不知道是feedly抓取，还是源的问题。刚好源挂了，来不及测试其他阅读器。
> 
> 色花堂属于短时间放出大量新文章。
> 路由内设定单次抓取11篇文章，所以论坛短时间放出超过11篇文章就会丢失部分。
> 一次抓取大量文章对于RSSHub其他路由以及源站会带来影响，所以没有增加抓取数量。
> 
> 
> 解决方案：
> 
> 1. 自建，并修改源码抓取数量
> 2. 修改阅读器更新时间到 15分钟

请问去哪修改抓取数量啊，已自建了。

**Comment by junfengP** [comment]
@100001000 
` lib/routes/dsndsht23/index.js`

![image](https://user-images.githubusercontent.com/15406392/75091306-d08c2900-55a6-11ea-941b-992d01bd285d.png)

**Comment by tony-hk** [comment]
改了抓取数量也是出同样问题

**Comment by junfengP** [comment]
> 改了抓取数量也是出同样问题

啥问题，路由报错?  见 #4051

**Comment by tony-hk** [comment]
> 
> 
> > 改了抓取数量也是出同样问题
> 
> 啥问题，路由报错? 见 #4051

Looks like something went wrong
MaxRedirectsError: Redirected 10 times. Aborting.
at ClientRequest.handleResponse (/app/node_modules/got/dist/source/request-as-event-emitter.js:102:31)
at Object.onceWrapper (events.js:418:26)
at ClientRequest.emit (events.js:323:22)
at ClientRequest.EventEmitter.emit (domain.js:482:12)
at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/index.js:41:20)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
at TLSSocket.socketOnData (_http_client.js:476:22)
at TLSSocket.emit (events.js:311:20)
at TLSSocket.EventEmitter.emit (domain.js:482:12)
at addChunk (_stream_readable.js:294:12)
at readableAddChunk (_stream_readable.js:275:11)
at TLSSocket.Readable.push (_stream_readable.js:209:10)
at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by junfengP** [comment]
> > > 改了抓取数量也是出同样问题
> > 
> > 
> > 啥问题，路由报错? 见 #4051
> 
> Looks like something went wrong
> MaxRedirectsError: Redirected 10 times. Aborting.
> at ClientRequest.handleResponse (/app/node_modules/got/dist/source/request-as-event-emitter.js:102:31)
> at Object.onceWrapper (events.js:418:26)
> at ClientRequest.emit (events.js:323:22)
> at ClientRequest.EventEmitter.emit (domain.js:482:12)
> at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/index.js:41:20)
> at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
> at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
> at TLSSocket.socketOnData (_http_client.js:476:22)
> at TLSSocket.emit (events.js:311:20)
> at TLSSocket.EventEmitter.emit (domain.js:482:12)
> at addChunk (_stream_readable.js:294:12)
> at readableAddChunk (_stream_readable.js:275:11)
> at TLSSocket.Readable.push (_stream_readable.js:209:10)
> at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)

#4051 已修复，等待合并

**Comment by tony-hk** [comment]
> 
> 
> > > > 改了抓取数量也是出同样问题
> > > 
> > > 
> > > 啥问题，路由报错? 见 #4051
> > 
> > 
> > Looks like something went wrong
> > MaxRedirectsError: Redirected 10 times. Aborting.
> > at ClientRequest.handleResponse (/app/node_modules/got/dist/source/request-as-event-emitter.js:102:31)
> > at Object.onceWrapper (events.js:418:26)
> > at ClientRequest.emit (events.js:323:22)
> > at ClientRequest.EventEmitter.emit (domain.js:482:12)
> > at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/index.js:41:20)
> > at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
> > at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
> > at TLSSocket.socketOnData (_http_client.js:476:22)
> > at TLSSocket.emit (events.js:311:20)
> > at TLSSocket.EventEmitter.emit (domain.js:482:12)
> > at addChunk (_stream_readable.js:294:12)
> > at readableAddChunk (_stream_readable.js:275:11)
> > at TLSSocket.Readable.push (_stream_readable.js:209:10)
> > at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
> 
> #4051 已修复，等待合并

现在可以了, 不过发现有些贴会变成"原帖已被删除"
https://rsshub.app/dsndsht23/
图: https://ibb.co/xCtrcWs

**Comment by junfengP** [comment]
> 现在可以了, 不过发现有些贴会变成"原帖已被删除"
> https://rsshub.app/dsndsht23/
> 图: https://ibb.co/xCtrcWs

我本地测试，自建均没有该问题。估计是网络问题，建议自建。

**Comment by tyhunter** [comment]
@junfengP 请教下最近类似这种两条magnet连接的帖子https://www.sehuatang.org/forum.php?mod=viewthread&tid=581613&extra=page%3D1 在抓取到的记录里会被单独算为一条导致flexget不识别了，可以修复吗
