### ISSUE TITLE
自建草榴论坛 成人文學交流區板块持续出错

### ISSUE THREAD

**Issue by jiey2016** [DIYgod/RSSHub#4100]
### 路由地址
https://rsshub.app/t66y/20
### 预期是什么？
正常工作
### 实际发生了什么？
拉取失败，报错
### 部署相关信息
TypeError: Cannot read property 'match' of undefined
    at Promise.all.list.map (/app/lib/routes/t66y/index.js:111:22)
    at Array.map ()
    at module.exports (/app/lib/routes/t66y/index.js:105:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by jiey2016** [comment]
![image](https://user-images.githubusercontent.com/19381978/75441389-8fc25480-5998-11ea-9349-50f13191612d.png)

**Comment by hoilc** [comment]
严格反爬，建议自建

**Comment by yefoenix** [comment]
@hoilc 这个是自建的也报错，而其他板块没问题
