### ISSUE TITLE
腾讯企鹅号部分站点的抓取大部分时间出错

### ISSUE THREAD

**Issue by martin5lee98** [DIYgod/RSSHub#4177]
### 路由地址

https://rsshub.app/tencent/news/author/5114050

### 预期是什么？

显示冰点周刊的最新报道

### 实际发生了什么？

间歇性出错。显示：

Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)
For

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by lisxray** [comment]
似乎跟服务器环境有关

**Comment by coffiner** [comment]
> 似乎跟服务器环境有关

国内的服务器正常，国外的报这个错误~
