### ISSUE TITLE
Wechat CSM 源：URL 中的 `-` 符号将导致“路由为空”

### ISSUE THREAD

**Issue by oyiadin** [DIYgod/RSSHub#4254]
### 路由地址

/wechat/csm/i-hduhdu

### 预期是什么？

正确返回公众号文章。

### 实际发生了什么？

提示路由为空。

### 额外信息（日志、报错等）

```
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)
```

**Comment by oyiadin** [comment]
猜测是 `:id` 这种写法默认不匹配 `-` 符号，但是根据[上游文档](https://github.com/pillarjs/path-to-regexp#usage)里给出的正则，似乎是支持的，不知道是不是本项目有一些特殊配置？

**Comment by hoilc** [comment]
https://chuansongme.com/account/i-hduhdu

与RSSHub无关，建议关闭

**Comment by oyiadin** [comment]
ok sorry~ 不知道 docs 里是否可以加上相关来源的首页/文档，方便后来者知悉自查方式

**Comment by hoilc** [comment]
`id, 必选 - 公众号 id, 打开公众号页, 在 URL 中找到 id`

这里指的就是传送门的公众号页URL，目前应该没有一个来源的微信公众号是全量的。
