### ISSUE TITLE
使用今日头条的时候发现错误

### ISSUE THREAD

**Issue by ZhangRuixin** [DIYgod/RSSHub#4288]
### 返回正常的
    今日头条 ai为关键词的响应信息

### 实际发生了什么？
    出现了应该是官方配置的错误页面

### 额外信息（日志、报错等）
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by hoilc** [comment]
![image](https://user-images.githubusercontent.com/9067094/77411256-18e17580-6df7-11ea-8c07-41b92cc2dd5c.png)

怀疑反pa反爬，等待观察
