### ISSUE TITLE
Youtube某些频道会报错

### ISSUE THREAD

**Issue by Pretty9** [DIYgod/RSSHub#4295]
### 路由地址
通过RSSHub Radar 发现的路由: https://rsshub.app/youtube/channel/UC1CfXB_kRs3C-zaeTG3oGyg
### 预期是什么？
略
### 实际发生了什么？
报错

### 额外信息（日志、报错等）
Error: The request cannot be completed because you have exceeded your quota.
    at Gaxios._request (/data/wwwroot/do02.rsshub.app/node_modules/gaxios/build/src/gaxios.js:85:23)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Object.getPlaylistItems (/data/wwwroot/do02.rsshub.app/lib/routes/youtube/utils.js:29:21)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/routes/youtube/channel.js:13:19)
    at async cache (/data/wwwroot/do02.rsshub.app/lib/middleware/cache.js:203:9)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by hoilc** [comment]
API配额不足，建议自建

**Comment by geochemistry** [comment]
> 
> 
> API配额不足，建议自建

请问如何自建……遇到同样问题了
