### ISSUE TITLE
Dockerhub: Official docker library doesn't work

### ISSUE THREAD

**Issue by He3chai** [DIYgod/RSSHub#4300]
### Involved route
dockerhub

### What is expected?
Get RSS feeds for https://hub.docker.com/_/docker

### What is actually happening?
```
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)
```

### Additional info (logs errors etc)
Test URL: https://rsshub.app/dockerhub/build/library/docker

Seems to be a problem because of the name **docker**? Other official libraries are working:
https://rsshub.app/dockerhub/build/library/mysql

**Comment by hoilc** [comment]
The default tag `latest` is not included in the latest 5 tags of the image `docker`.

**Comment by He3chai** [comment]
Working, thanks :)
