### ISSUE TITLE
内容过滤参数失效了

### ISSUE THREAD

**Issue by 2220209876** [DIYgod/RSSHub#4328]
举例 1: https://rsshub.app/bilibili/user/coin/2267573?filter=微小微|赤九玖|暴走大事件 举例 2: https://rsshub.app/nga/forum/485?filter_time=600

举例: https://rsshub.app/bilibili/user/coin/2267573?filterout=微小微|赤九玖|暴走大事件
https://rsshub.app/bilibili/user/coin/2267573?filterout=%E5%BE%AE%E5%B0%8F%E5%BE%AE|%E8%B5%A4%E4%B9%9D%E7%8E%96|%E6%9A%B4%E8%B5%B0%E5%A4%A7%E4%BA%8B%E4%BB%B6

返回：
Looks like something went wrong
TypeError: Cannot read property 'map' of null
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/routes/bilibili/coin.js:24:20)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async cache (/data/wwwroot/do02.rsshub.app/lib/middleware/cache.js:203:9)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by DIYgod** [comment]
只是链接挂了，参数是好的
