### ISSUE TITLE
TypeError: Cannot read property 'groups' of null

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [DIYgod/RSSHub#4389]
### Involved route
https://rsshub.app/sciencemag/cover

### What is expected?
it work well before this week

### What is actually happening?
```
TypeError: Cannot read property 'groups' of null
    at Node. (/data/wwwroot/do02.rsshub.app/lib/routes/sciencemag/cover.js:24:74)
    at /data/wwwroot/do02.rsshub.app/node_modules/cheerio/lib/api/traversing.js:306:18
    at /data/wwwroot/do02.rsshub.app/node_modules/lodash/_baseReduce.js:18:9
    at /data/wwwroot/do02.rsshub.app/node_modules/lodash/_createBaseEach.js:24:11
    at baseReduce (/data/wwwroot/do02.rsshub.app/node_modules/lodash/_baseReduce.js:15:3)
    at Object.reduce (/data/wwwroot/do02.rsshub.app/node_modules/lodash/reduce.js:48:10)
    at initialize.exports.map (/data/wwwroot/do02.rsshub.app/node_modules/cheerio/lib/api/traversing.js:305:23)
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/routes/sciencemag/cover.js:20:10)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async cache (/data/wwwroot/do02.rsshub.app/lib/middleware/cache.js:203:9)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)
```

### Additional info (logs errors etc)

some day before, i was reported this router on issue https://github.com/DIYgod/RSSHub/issues/4173  last month, and that issue are fixed.
i provide this addition info , i hope it can help you to solution this issue.

**Comment by hoilc** [comment]
It works as expected now.

**Comment by Lyoko-Jeremie** [comment]
@hoilc yes, and no one known why ~

**Comment by hoilc** [comment]
This route reads journal information from the cover URLs.

Most likely, the pattern of some cover URL was changed temporarily.
