### ISSUE TITLE
猫眼电影 - 正在热映 抓取出错

### ISSUE THREAD

**Issue by Konano** [DIYgod/RSSHub#4416]
### 路由地址
https://rsshub.app/maoyan/hot

### 实际发生了什么？
TypeError: Cannot read property 'map' of undefined
    at module.exports (/data/wwwroot/do01.rsshub.app/lib/routes/maoyan/hot.js:10:14)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async cache (/data/wwwroot/do01.rsshub.app/lib/middleware/cache.js:203:9)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do01.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/onerror.js:20:9)

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by hoilc** [comment]
猫眼API返回为空，受当前疫情影响，确认为正常情况
