### ISSUE TITLE
小黑盒游戏打折情况

### ISSUE THREAD

**Issue by bestpika** [DIYgod/RSSHub#4484]
### 路由地址

`xiaoheihe/discount`

### 预期是什么？

有資料

### 实际发生了什么？

錯誤

### 额外信息（日志、报错等）

```
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do01.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/onerror.js:20:9)
```

**Comment by black-desk** [comment]
给你修了, 看pr给不给过了
