### ISSUE TITLE
【Bug Report】用yarn安装，安装过程中报错，某yarnpkg.com页面反馈404

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#4512]
用yarn安装，安装过程中报错
```
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...

error An unexpected error occurred: "https://registry.yarnpkg.com/@koa/router/-/router-9.0.0.tgz: Request failed \"404 Not Found\"".
```
[https://registry.yarnpkg.com/@koa/router/-/router-9.0.0.tgz](https://registry.yarnpkg.com/@koa/router/-/router-9.0.0.tgz) 这个打不开。
### version
```
│ revision control │ git                                                                         │
│ remote url       │ https://github.com/DIYgod/RSSHub.git                                        │
│ repository root  │ /var/www/RSSHub                                                             │
│ last update      │ 2020-04-19T13:09:40.434Z                                                    │
│ revision         │ 20fc36affc54dfda4d109141c482f361a3ca24d0                                    │
│ comment          │ Merge pull request #4456 from DIYgod/dependabot/npm_and_yarn/vuepress-1.4.1 │
│ branch           │ master 
```

```
┌──────────┬────┬─────────┬──────┬───────┬─────────┬─────────┬────────┬─────┬────────┬──────┬──────────┐
│ App name │ id │ version │ mode │ pid   │ status  │ restart │ uptime │ cpu │ mem    │ user │ watching │
├──────────┼────┼─────────┼──────┼───────┼─────────┼─────────┼────────┼─────┼────────┼──────┼──────────┤
│ rsshub   │ 0  │ 0.1.1   │ fork │ 10066 │ stopped │ 31      │ 0      │ 0%  │ 0 B    │ root │ disabled │
└──────────┴────┴─────────┴──────┴───────┴─────────┴─────────┴────────┴─────┴────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

### 谢谢

**Comment by KwToPA** [comment]
cat yarn-error.log

```
Arguments: 
  /usr/bin/node /usr/share/yarn/bin/yarn.js

PATH: 
  /sbin:/bin:/usr/sbin:/usr/bin

Yarn version: 
  1.22.4

Node version: 
  10.16.1

Platform: 
  linux x64

Trace: 
  Error: https://registry.yarnpkg.com/@koa/router/-/router-9.0.0.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/usr/share/yarn/lib/cli.js:696:66)
      at new ResponseError (/usr/share/yarn/lib/cli.js:802:124)
      at Request.<anonymous> (/usr/share/yarn/lib/cli.js:67057:16)
      at Request.emit (events.js:198:13)
      at Request.module.exports.Request.onRequestResponse (/usr/share/yarn/lib/cli.js:141625:10)
      at ClientRequest.emit (events.js:203:15)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
      at TLSSocket.socketOnData (_http_client.js:442:20)
      at TLSSocket.emit (events.js:198:13)

  "@koa/router@9.0.0":
    version "9.0.0"
    resolved "https://registry.yarnpkg.com/@koa/router/-/router-9.0.0.tgz#ceec54a20f5e34b19091b4e0c8fea8d00a4a0ad8"
    integrity sha512-JPi8XHgCrHkc81V7vrwuTJIFM51BNt4WryOd+0t4mCouuT5HpZa/VOzrT0Ts/ksa3b1ZyBHZeARtGObPoMHEdg==
    dependencies:
      debug "^4.1.1"
      http-errors "^1.7.3"
      koa-compose "^4.1.0"
      methods "^1.1.2"
      path-to-regexp "^6.1.0"
      urijs "^1.19.2"
```

**Comment by KwToPA** [comment]
用 npm install 报错如下
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @koa/router@9.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by KwToPA** [comment]
在RSSHub文件外，使用yarn add router
```
yarn add v1.22.4
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
warning No license field
success Saved 9 new dependencies.
info Direct dependencies
└─ router@1.3.5
info All dependencies
├─ array-flatten@3.0.0
├─ debug@2.6.9
├─ methods@1.1.2
├─ ms@2.0.0
├─ parseurl@1.3.3
├─ path-to-regexp@0.1.7
├─ router@1.3.5
├─ setprototypeof@1.2.0
└─ utils-merge@1.0.1
Done in 0.39s.
```
但[https://registry.yarnpkg.com/@koa/router/-/router-1.3.5.tgz](https://registry.yarnpkg.com/@koa/router/-/router-1.3.5.tgz)也打不开
