### ISSUE TITLE
Instagram error

### ISSUE THREAD

**Issue by lardissone** [DIYgod/RSSHub#4519]
### Involved route
/instagram/user/inspiratiq

### What is expected?
Return the RSS feed for any instagram user.

### What is actually happening?
This error is happening:
```
TypeError: Cannot read property '0' of undefined
    at module.exports (/Users/lardissone/RSSHub/lib/routes/instagram/user.js:15:45)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Self-deployed information
I have been using the Docker version for a few days and today after upgrade to latest version this error appeared.
Tried downloading the node self hosted version and same error appears.

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |  OSX Catalina             |
| Node version       | v10.16.0              |
| if Docker, version |  19.03.8, build afacb8b             |

**Comment by hoilc** [comment]
It works fine now. Can you confirm that?

![image](https://user-images.githubusercontent.com/9067094/80312271-de646180-8816-11ea-8856-0e05f82a7267.png)

**Comment by Ice-Hazymoon** [comment]
I also encountered a similar problem

## Involved route
`/instagram/user/ayasa_doya`

## Self-deployed information


Env | Value
-- | --
OS | centos 7 
Node version | v12.16.3
rsshub version | 8d7e10c3be4a9ed1749b2e4cba8f3e0eb08e7259


```
TypeError: Cannot read property '0' of undefined
    at module.exports (/www/wwwroot/rsshub.imiku.me/RSSHub/lib/routes/instagram/user.js:15:36)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cache (/www/wwwroot/rsshub.imiku.me/RSSHub/lib/middleware/cache.js:203:9)
    at async module.exports (/www/wwwroot/rsshub.imiku.me/RSSHub/lib/middleware/parameter.js:8:5)
    at async module.exports (/www/wwwroot/rsshub.imiku.me/RSSHub/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/www/wwwroot/rsshub.imiku.me/RSSHub/lib/middleware/template.js:15:5)
    at async /www/wwwroot/rsshub.imiku.me/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/www/wwwroot/rsshub.imiku.me/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/www/wwwroot/rsshub.imiku.me/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/www/wwwroot/rsshub.imiku.me/RSSHub/lib/middleware/debug.js:14:5)
    at async grant (/www/wwwroot/rsshub.imiku.me/RSSHub/lib/middleware/access-control.js:20:13)
    at async module.exports (/www/wwwroot/rsshub.imiku.me/RSSHub/lib/middleware/access-control.js:28:20)
    at async module.exports (/www/wwwroot/rsshub.imiku.me/RSSHub/lib/middleware/header.js:20:5)
    at async module.exports (/www/wwwroot/rsshub.imiku.me/RSSHub/lib/middleware/onerror.js:20:9)
```

![image](https://user-images.githubusercontent.com/25239977/81950346-64194700-9636-11ea-8bb7-58f7af8d7bf2.png)
