### ISSUE TITLE
中华人民共和国生态环境部 #公示 失效

### ISSUE THREAD

**Issue by seekdoor** [DIYgod/RSSHub#4525]
### 路由地址
`/gov/mee/gs`

### 实际发生了什么？
```
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports (/app/lib/middleware/parameter.js:19:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### 额外信息（日志、报错等）

- 使用demo
```
Looks like something went wrong
getaddrinfo EAI_AGAIN www.mee.gov.cn: target website might be blocking our access, you can host your own RSSHub instance for a better usability.
```

- 使用自己搭建
```
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports (/app/lib/middleware/parameter.js:19:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by black-desk** [comment]
这个页面貌似变化很大,你可以说一下你希望抓取到什么内容么? [新的地址](http://www.mee.gov.cn/xxgk2018/)

**Comment by 10362227** [comment]
这种简单的，建议用现成的php 
![TIM截图20200426120356](https://user-images.githubusercontent.com/10655420/80297524-50f12500-87b6-11ea-9f28-7ad5b78245a1.png)
