### ISSUE TITLE
中华人民共和国海关总署 失效

### ISSUE THREAD

**Issue by pcwuyu** [DIYgod/RSSHub#4526]
### 路由地址
`/gov/customs/list/:gchannel`

paimai,fagui等2个频道

### 实际发生了什么？
```
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports 
```

### 额外信息（日志、报错等）
```
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do01.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/onerror.js:20:9)
```

**Comment by black-desk** [comment]
fagui 我之前已经修好了, 建议你更新一下先  #4487
