### ISSUE TITLE
江苏省人民政府 政府信息公开年度报告 + 政府信息公开制度 失效

### ISSUE THREAD

**Issue by seekdoor** [DIYgod/RSSHub#4527]
### 路由地址
`/gov/province/jiangsu/annual-report`
`/gov/province/jiangsu/information-publicity`

### 实际发生了什么？
```
Error: this route is empty, please check the original site or create an issue
```

### 额外信息（日志、报错等）
```
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)
```

**Comment by murphysking** [comment]
annual-report页面的内容与其他不同，需要单独做解析
