### ISSUE TITLE
抓取微博数据报错：Cannot read property 'screen_name' of undefined

### ISSUE THREAD

**Issue by wyzane** [DIYgod/RSSHub#4539]
### 路由地址
/weibo/user/5926318749
### 预期是什么？
正常工作
### 实际发生了什么？
Cannot read property 'screen_name' of undefined，详细错误如下：
error: Error in /weibo/user/5926318749: TypeError: Cannot read property 'screen_name' of undefined
    at module.exports (/home/service/RSSHub/lib/routes/weibo/user.js:16:55)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cache (/home/service/RSSHub/lib/middleware/cache.js:203:9)
    at async module.exports (/home/service/RSSHub/lib/middleware/parameter.js:8:5)
    at async module.exports (/home/service/RSSHub/lib/middleware/template.js:15:5)
    at async /home/service/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/home/service/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/home/service/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/home/service/RSSHub/lib/middleware/debug.js:14:5)
    at async module.exports (/home/service/RSSHub/lib/middleware/access-control.js:29:13)
    at async module.exports (/home/service/RSSHub/lib/middleware/header.js:20:5)
    at async module.exports (/home/service/RSSHub/lib/middleware/onerror.js:20:9)
### 部署相关信息
rsshub.app

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       CentOS 7        |
| Node version       |      node 12.16.1         |
| if Docker, version |               |

**Comment by nczitzk** [comment]
提供的路由地址在自建服务上测试是正常的。如果该路由不再报该错误信息，你可以关闭该 issue。

提供不存在的 user id 可以复现相同的错误信息，如 /weibo/user/0。此时返回的 containerResponse.data 中的 data 字段应为 {"cards":[]}，不包含 userInfo 字段。undefined 合理。但 5926318749 是确实存在的 user id。

若仍报告相同错误，在 /home/service/RSSHub/lib/routes/weibo/user.js:16 前加上 console.log(containerResponse.data); 再访问该路由看一下输出的 containerResponse.data 然后尝试抓一下虫吧 😃

**Comment by DIYgod** [comment]
微博反爬严格，而且现在看起来是好的
