### ISSUE TITLE
安装报错，Failed to set up Chromium r737027!

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#4603]
安装报错

1、用yarn ，反馈
```
error /root/RSSHub/node_modules/puppeteer: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /root/RSSHub/node_modules/puppeteer
Output:
ERROR: Failed to set up Chromium r737027! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error: Puppeteer currently does not work on Node v14 due to an upstream bug. Please see: https://github.com/puppeteer/puppeteer/issues/5719 for details.
    at Timeout._onTimeout (/root/RSSHub/node_modules/puppeteer/lib/BrowserFetcher.js:295:27)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
  -- ASYNC --
```

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |         centos 7      |
| Node version       |      v14.0.0         |
| if Docker, version |               |

### 额外信息（日志、报错等）

yarn --version
1.22.4

npm --version
v6.14.4

2、用npm install，反馈
```
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q git://github.com/postlight/difflib.js.git /root/.npm/_cacache/tmp/git-clone-31a1fb5d/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-31a1fb5d/.git'
```

**Comment by DIYgod** [comment]
Error 里已经写得很清楚了

`Error: Puppeteer currently does not work on Node v14 due to an upstream bug. Please see: https://github.com/puppeteer/puppeteer/issues/5719 for details.`
