### ISSUE TITLE
本地宝 不支持2字母外的城市

### ISSUE THREAD

**Issue by ptsa** [DIYgod/RSSHub#4626]
### 路由地址
http://huzhou.bendibao.com/
https://rsshub.app/bendibao/news/huzhou
### 预期是什么？
和https://rsshub.app/bendibao/news/hz
这样的城市是2字母的就可以正常使用
### 额外信息（日志、报错等）
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:29:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)
For online documentation and support please refer to docs.rsshub.app.

**Comment by ptsa** [comment]
@nczitzk 可以更新下 支持除双字母外的城市么

**Comment by nczitzk** [comment]
> @nczitzk 可以更新下 支持除双字母外的城市么

本地宝的城市页面有两种样式（一部分城市没有更新到较新的一种）和城市缩写字母个数无关。之前没有测试到足够多的城市，所以没有注意到 😂
