### ISSUE TITLE
Error using Email bridge

### ISSUE THREAD

**Issue by atomtm** [DIYgod/RSSHub#4662]
### Involved route
Email
### What is expected?
Get RSS feed for incoming emails
### What is actually happening?
I am getting error
### Self-deployed information
nodejs : v13.13.0
OS: Raspbian 10
Installed using npm according to : https://docs.rsshub.app/en/usage.html#install
### Additional info (logs errors etc)
So I configured the `.env` file inside my directory like this : 
`EMAIL_CONFIG_myemail.gmail.com=password=@p@ssword@&host=imap.gmail.com&port=993`
Now when I try to get the RSS feed I use : 
`https://myhostserver.com/mail/imap/myemail@gmail.com`
and get the following error:
```
TypeError: mails.reverse is not a function
    at module.exports (/home/b/RSSHub/lib/routes/mail/imap.js:54:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cache (/home/b/RSSHub/lib/middleware/cache.js:203:9)
    at async module.exports (/home/b/RSSHub/lib/middleware/parameter.js:8:5)
    at async module.exports (/home/b/RSSHub/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/home/b/RSSHub/lib/middleware/template.js:15:5)
    at async /home/b/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/home/b/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/home/b/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/home/b/RSSHub/lib/middleware/debug.js:14:5)
    at async module.exports (/home/b/RSSHub/lib/middleware/access-control.js:29:13)
    at async module.exports (/home/b/RSSHub/lib/middleware/header.js:20:5)
    at async module.exports (/home/b/RSSHub/lib/middleware/onerror.js:20:9)
```

**Comment by MittWillson** [comment]
before this crash error, did you see some like `error: undefined` or something, i need more infomation

**Comment by yefoenix** [comment]
heroku 自建使用正常，怀疑是 rsshub 实例服务器与邮件服务器之间的可访问性问题

**Comment by HenryQW** [comment]
If you configured it correctly, it will work, I've tested it multiple times.

**Comment by atomtm** [comment]
> before this crash error, did you see some like `error: undefined` or something, i need more infomation

coming back on this , I get undefined yes
any ideas?

**Comment by atomtm** [comment]
> If you configured it correctly, it will work, I've tested it multiple times.

using `.env` file with:
`EMAIL_CONFIG_myemail.gmail.com=password=mypassword&host=imap.gmail.com&port=993`
then I use the route :
`http://localhost:1200/mail/imap/myemail.gmail.com`
logs aren't really helping here

**Comment by kevinschaul** [comment]
FYI I had to use underscores in my email address to get this to work. So `EMAIL_CONFIG_myemail_gmail_com=password=mypassword&host=imap.gmail.com&port=993`

**Comment by zoenglinghou** [comment]
@kevinschaul Yeah that is an error in the documentation as I just found out.

I am still getting the errors mentioned by @atomtm :thinking:
