### ISSUE TITLE
Google Scholar Simple Research RSS not work

### ISSUE THREAD

**Issue by starsareintherose** [DIYgod/RSSHub#4700]
### 路由地址
https://rsshub.app/google/scholar/gastropod+taxonomy
### 预期是什么？
It can work based on the publishing date.
### 实际发生了什么？
No information on it
### 部署相关信息
noraml
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do01.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:20:13)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:45:24)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/onerror.js:20:9)
For online documentation and support please refer to docs.rsshub.app.

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

**Comment by DIYgod** [comment]
https://docs.rsshub.app/faq.html
