### ISSUE TITLE
知乎收藏夹失效

### ISSUE THREAD

**Issue by Konveksa** [DIYgod/RSSHub#4715]
### 路由地址
/zhihu/collection/:id

### 预期是什么？
正常创建订阅源，正常抓取文章

### 实际发生了什么？
订阅源无法创建

### 部署相关信息
使用 demo 与最新版自建均有此问题。

### 额外信息（日志、报错等）
自建
Error: this route is empty, please check the original site or create an issue
    at module.exports (/www/wwwroot/RSSHub/lib/middleware/parameter.js:19:19)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/www/wwwroot/RSSHub/lib/middleware/template.js:15:5)
    at async /www/wwwroot/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/www/wwwroot/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/www/wwwroot/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/www/wwwroot/RSSHub/lib/middleware/debug.js:14:5)
    at async module.exports (/www/wwwroot/RSSHub/lib/middleware/access-control.js:29:13)
    at async module.exports (/www/wwwroot/RSSHub/lib/middleware/header.js:20:5)
    at async module.exports (/www/wwwroot/RSSHub/lib/middleware/onerror.js:20:9) 

demo
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:20:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:45:24)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by gixid192** [comment]
I'm still having this error, could you guy check please?

**Comment by buzhangjiuzhou** [comment]
l've encountered this problem as well.
自建：
Error: this route is empty, please check the original site or create an issue
    at module.exports (/app/lib/middleware/parameter.js:19:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
demo:
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)

And I also checked the version of mine, It is created about 3 weeks ago using docker.
