### ISSUE TITLE
/ Character breaks the Github Issue feature

### ISSUE THREAD

**Issue by Ardakilic** [DIYgod/RSSHub#4779]
### Involved route
GitHub , issues

### What is expected?
Feed to be shown properly

### What is actually happening?
Throws error

### Additional info (logs errors etc)

This is what we want to RSS:

https://github.com/mattermost/mattermost-server/issues?q=is%3Aopen+is%3Aissue+label%3ATech%2FGo+label%3A%22Help+Wanted%22

We generated a link according to documentation:

https://rsshub.app/github/issue/mattermost/mattermost-server/open/Help%20Wanted,Tech%2FGo

However, this throws an error to the browser,

```
Error: wrong path
    at module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/parameter.js:14:15)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do01.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:20:13)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:45:24)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/onerror.js:20:9)
```

As far as I can tell, it's because there's a `/` character in the label `Tech/Go`.

What are we missing? Any information would be appreciated.

Kind Regards,

**Comment by hoilc** [comment]
It doesn't. The demo instance is more likely to be misconfigured.

https://rsshub.diy.now.sh/github/issue/mattermost/mattermost-server/open/Help%20Wanted,Tech%2FGo

The vercel deployment works well.

**Comment by HenryQW** [comment]
Localhost and my own instance are working fine.
