### ISSUE TITLE
WIKI-中国大陆新闻动态 不工作了

### ISSUE THREAD

**Issue by cryzlasm** [DIYgod/RSSHub#4793]
### 路由地址
https://rsshub.app/wikipedia/mainland
### 实际发生了什么？
![image](https://user-images.githubusercontent.com/20424580/82112952-9e90fa00-9784-11ea-93c2-119722c2e425.png)

### 额外信息（日志、报错等）
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:20:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:45:24)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by yy-zhou** [comment]
Same problem here, self-host.

<img width="832" alt="Screen Shot 2020-05-16 at 20 42 02" src="https://user-images.githubusercontent.com/14092462/82135288-cea4c100-97b5-11ea-92f9-f083258618b7.png">
