### ISSUE TITLE
知乎专栏失效

### ISSUE THREAD

**Issue by deskid** [DIYgod/RSSHub#4818]
### 路由地址
https://rsshub.app/zhihu/zhuanlan/googledevelopers
### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

### 额外信息（日志、报错等）
TypeError: Cannot read property 'map' of undefined
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/routes/zhihu/zhuanlan.js:37:14)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async cache (/data/wwwroot/do02.rsshub.app/lib/middleware/cache.js:203:9)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:20:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:45:24)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by DIYgod** [comment]
反爬

**Comment by yuxineverforever** [comment]
同问 有什么办法么
