### ISSUE TITLE
pianyuan

### ISSUE THREAD

**Issue by greatcodeeer** [DIYgod/RSSHub#4828]
### 路由地址

https://rsshub.app/pianyuan/mv

### 预期是什么？

电影清单

### 实际发生了什么？

Error: this route is empty

### 额外信息（日志、报错等）

Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do01.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:20:13)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:45:24)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by hoilc** [comment]
国外IP反爬，可以国内自建
