### ISSUE TITLE
Cannot subscribe to private Twitter list

### ISSUE THREAD

**Issue by wydwww** [DIYgod/RSSHub#4875]
### Involved route
Twitter list timeline
### What is expected?
Subscribe to private lists
### What is actually happening?
My Twitter account is private. I setup the Twitter API configurations and I can subscribe to my following timeline and my non-private lists. The API works fine. The docker image is the latest.

Issue: cannot subscribe to my private lists. 

According to Twitter doc, 
> Private lists will only be shown if the authenticated user owns the specified list.
### Self-deployed information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |     Ubuntu 18.04    |
| Node version       |               |
| if Docker, version |     19.03.8     |

### Additional info (logs errors etc)
```
Error: Sorry, that page does not exist.
    at Object.exports.makeTwitError (/app/node_modules/twit/lib/helpers.js:74:13)
    at onRequestComplete (/app/node_modules/twit/lib/twitter.js:344:25)
    at Request. (/app/node_modules/twit/lib/twitter.js:364:7)
    at Request.emit (events.js:203:15)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Gunzip. (/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at Gunzip.emit (events.js:203:15)
    at Gunzip.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by promise80** [comment]
Hey

**Comment by HenryQW** [comment]
Twitter related issues are hard to fix as I do not have an API key to do so.
