### ISSUE TITLE
【水果邦 Powered by Discuz! X3】希望支持推送最新帖子，帖子最新回复，用户动态——Rss Wanted

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#4929]
### 网站地址
[https://bbs.shuiguobang.com/forum.php](https://bbs.shuiguobang.com/forum.php)
### 网站描述
果树种植相关的论坛
## 帖子推送
例如 无花果论坛 [https://bbs.shuiguobang.com/forum-379-1.html](https://bbs.shuiguobang.com/forum-379-1.html)希望能支持按照时间倒叙推送最新的帖子，[https://bbs.shuiguobang.com/forum.php?mod=forumdisplay&fid=379&filter=author&orderby=dateline](https://bbs.shuiguobang.com/forum.php?mod=forumdisplay&fid=379&filter=author&orderby=dateline)

## 回复推送
例如帖子[原创] 沤肥神器 [https://bbs.shuiguobang.com/forum.php?mod=viewthread&tid=1084703](https://bbs.shuiguobang.com/forum.php?mod=viewthread&tid=1084703)希望能支持推送最新回复

## 用户动态
例如用户曹东的动态[https://bbs.shuiguobang.com/home.php?mod=space&uid=318832&do=home](https://bbs.shuiguobang.com/home.php?mod=space&uid=318832&do=home)希望能支持推送用户动态

### 额外描述

论坛 Powered by Discuz! X3

### 谢谢

**Comment by wangnianshu** [comment]
https://docs.rsshub.app/bbs.html#discuz

**Comment by KwToPA** [comment]
> https://docs.rsshub.app/bbs.html#discuz

您好，我试了下，能够成功推送，可惜不是按照发帖顺序来。

我又尝试用时间倒序的url代替原来的，符号也替换成Ascii码了

[https://rsshub.app/discuz/x/https%3a%2f%2fbbs.shuiguobang.com%2fforum.php?mod%3Dforumdisplay%26fid%3D379%26filter%3Dauthor%26orderby%3Ddateline](https://rsshub.app/discuz/x/https%3a%2f%2fbbs.shuiguobang.com%2fforum.php?mod%3Dforumdisplay%26fid%3D379%26filter%3Dauthor%26orderby%3Ddateline)

可惜还是不行。

```
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:20:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:45:24)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)
```
应该就是不支持按时间顺序

**Comment by wangnianshu** [comment]
discuz板块里自定按发帖时间排序是可以支持的。RSSHUB的discuz推送以及对不同模板的兼容可能是有问题的。我在尝试的时候就遇到不会推送更新的问题。

**Comment by KwToPA** [comment]
> discuz板块里自定按发帖时间排序是可以支持的。RSSHUB的discuz推送以及对不同模板的兼容可能是有问题的。我在尝试的时候就遇到不会推送更新的问题。

显示```this route is empty```，是我用的参数不对吗？这个 orderby=dateline

**Comment by wangnianshu** [comment]
/forum.php?mod=forumdisplay&fid=XX&filter=author&orderby=dateline

我这样测试是没有报错的。

**Comment by KwToPA** [comment]
谢谢 ，原来是之前链接中的```?```没有用ascii替代
