### ISSUE TITLE
【中国人民银行】Navigation failed because browser has disconnected!——Bug Report

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#4937]
### 路由地址
```/pbc/goutongjiaoliu``` 和 ```/pbc/tradeAnnouncement``` ，[https://github.com/DIYgod/RSSHub/pull/4824/commits](https://github.com/DIYgod/RSSHub/pull/4824/commits)
### 预期是什么？
正常使用
## 自建

我用
```
yum -y install alsa-lib.x86_64 atk.x86_64 cups-libs.x86_64 GConf2.x86_64 gtk3.x86_64 ipa-gothic-fonts libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXrandr.x86_64 libXScrnSaver.x86_64 libXtst.x86_64 pango.x86_64 xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-fonts-cyrillic xorg-x11-fonts-misc xorg-x11-fonts-Type1 xorg-x11-utils 
```
装了puppeteer的依赖，```/pbc/goutongjiaoliu``` 和 ```/pbc/tradeAnnouncement```都报错
```
Error: Navigation failed because browser has disconnected!
    at CDPSession.LifecycleWatcher._eventListeners.helper_1.helper.addEventListener (/var/www/RSSHub/node_modules/puppeteer/lib/LifecycleWatcher.js:45:131)
    at CDPSession.emit (events.js:198:13)
    at CDPSession.EventEmitter.emit (domain.js:448:20)
    at CDPSession._onClosed (/var/www/RSSHub/node_modules/puppeteer/lib/Connection.js:181:14)
    at Connection._onMessage (/var/www/RSSHub/node_modules/puppeteer/lib/Connection.js:76:25)
    at WebSocketTransport._ws.addEventListener (/var/www/RSSHub/node_modules/puppeteer/lib/WebSocketTransport.js:25:32)
    at WebSocket.onMessage (/var/www/RSSHub/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:198:13)
    at WebSocket.EventEmitter.emit (domain.js:448:20)
    at Receiver.receiverOnMessage (/var/www/RSSHub/node_modules/ws/lib/websocket.js:801:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.EventEmitter.emit (domain.js:448:20)
    at Receiver.dataMessage (/var/www/RSSHub/node_modules/ws/lib/receiver.js:436:14)
    at Receiver.getData (/var/www/RSSHub/node_modules/ws/lib/receiver.js:366:17)
    at Receiver.startLoop (/var/www/RSSHub/node_modules/ws/lib/receiver.js:142:22)
    at Receiver._write (/var/www/RSSHub/node_modules/ws/lib/receiver.js:77:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at Socket.socketOnData (/var/www/RSSHub/node_modules/ws/lib/websocket.js:876:35)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
  -- ASYNC --
    at Frame. (/var/www/RSSHub/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.goto (/var/www/RSSHub/node_modules/puppeteer/lib/Page.js:485:53)
    at Page. (/var/www/RSSHub/node_modules/puppeteer/lib/helper.js:95:27)
    at module.exports (/var/www/RSSHub/lib/routes/pbc/goutongjiaoliu.
```
## rsshub.app

```/pbc/goutongjiaoliu``` 报错

```
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do01.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/onerror.js:20:9)
```

```/pbc/tradeAnnouncement``` 报错

```
Error: Navigation failed because browser has disconnected!
    at CDPSession. (/data/wwwroot/do02.rsshub.app/node_modules/puppeteer/lib/LifecycleWatcher.js:45:131)
    at CDPSession.emit (events.js:223:5)
    at CDPSession.EventEmitter.emit (domain.js:475:20)
    at CDPSession._onClosed (/data/wwwroot/do02.rsshub.app/node_modules/puppeteer/lib/Connection.js:181:14)
    at Connection._onMessage (/data/wwwroot/do02.rsshub.app/node_modules/puppeteer/lib/Connection.js:76:25)
    at WebSocket. (/data/wwwroot/do02.rsshub.app/node_modules/puppeteer/lib/WebSocketTransport.js:25:32)
    at WebSocket.onMessage (/data/wwwroot/do02.rsshub.app/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:223:5)
    at WebSocket.EventEmitter.emit (domain.js:475:20)
    at Receiver.receiverOnMessage (/data/wwwroot/do02.rsshub.app/node_modules/ws/lib/websocket.js:801:20)
    at Receiver.emit (events.js:223:5)
    at Receiver.EventEmitter.emit (domain.js:475:20)
    at Receiver.dataMessage (/data/wwwroot/do02.rsshub.app/node_modules/ws/lib/receiver.js:436:14)
    at Receiver.getData (/data/wwwroot/do02.rsshub.app/node_modules/ws/lib/receiver.js:366:17)
    at Receiver.startLoop (/data/wwwroot/do02.rsshub.app/node_modules/ws/lib/receiver.js:142:22)
    at Receiver._write (/data/wwwroot/do02.rsshub.app/node_modules/ws/lib/receiver.js:77:10)
    at doWrite (_stream_writable.js:435:12)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Receiver.Writable.write (_stream_writable.js:309:11)
    at Socket.socketOnData (/data/wwwroot/do02.rsshub.app/node_modules/ws/lib/websocket.js:876:35)
    at Socket.emit (events.js:223:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
  -- ASYNC --
    at Frame. (/data/wwwroot/do02.rsshub.app/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.goto (/data/wwwroot/do02.rsshub.app/node_modules/puppeteer/lib/Page.js:485:53)
    at Page. (/data/wwwroot/do02.rsshub.app/node_modules/puppeteer/lib/helper.js:95:27)
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/routes/pbc/goutongjiaoliu.js:9:16)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async cache (/data/wwwroot/do02.rsshub.app/lib/middleware/cache.js:203:9)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)
```
## 搜navigation failed because browser has disconnected，

发现[https://github.com/puppeteer/puppeteer/issues/3927#issuecomment-480286878](https://github.com/puppeteer/puppeteer/issues/3927#issuecomment-480286878)这边似乎有解决方法但我看不懂，似乎是[https://github.com/alixaxel/chrome-aws-lambda/blob/master/source/index.js](https://github.com/alixaxel/chrome-aws-lambda/blob/master/source/index.js)用了里面的 ```--single-process``` flag，不过下面也有用户说这个没用。

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |      centos          |
| Node version       |        10.21       |
| if Docker, version |               |

### 谢谢

**Comment by nczitzk** [comment]
https://github.com/DIYgod/RSSHub/pull/4824#issuecomment-640237353

**Comment by NeverBehave** [comment]
Close as won't fix from https://github.com/DIYgod/RSSHub/pull/4824#issuecomment-642318037
@DIYgod 有空可以pin一个说明

**Comment by KwToPA** [comment]
搜到两个解决方法：都是说await和forEach

## 

[https://stackoverflow.com/questions/54527982/why-is-puppeteer-reporting-unhandledpromiserejectionwarning-error-navigation](https://stackoverflow.com/questions/54527982/why-is-puppeteer-reporting-unhandledpromiserejectionwarning-error-navigation)

The ```Navigation failed because browser has disconnected error``` usually means that the node scripts that launched Puppeteer ends without waiting for the Puppeteer actions to be completed. 

## 

[https://m.jb51.cc/python/454296.html](https://m.jb51.cc/python/454296.html)

Error: Navigation failed because browser has disconnected!，换句话说就是，还没爬，浏览器就关闭了，大概就是异步问题了。 《await与forEach》

**Comment by NeverBehave** [comment]
> 搜到两个解决方法：都是说await和forEach
> 
> https://stackoverflow.com/questions/54527982/why-is-puppeteer-reporting-unhandledpromiserejectionwarning-error-navigation
> 
> The `Navigation failed because browser has disconnected error` usually means that the node scripts that launched Puppeteer ends without waiting for the Puppeteer actions to be completed.
> 
> https://m.jb51.cc/python/454296.html
> 
> Error: Navigation failed because browser has disconnected!，换句话说就是，还没爬，浏览器就关闭了，大概就是异步问题了。 《await与forEach》

这就是获取超时的行为，不是问题

**Comment by DIYgod** [comment]
超时改到 30s 了 ae529572d77407172328f27556acd01a64d52ab4
