### ISSUE TITLE
【财联社-电报】wrong path——Bug Report

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#4938]
### 路由地址
```/cls/telegragh``` [https://github.com/DIYgod/RSSHub/pull/4924](https://github.com/DIYgod/RSSHub/pull/4924)
### 预期是什么？
正常推送
### 实际发生了什么？

```/cls/depth```正常，```/cls/telegragh```报错

## 自建

```
Error: wrong path
    at module.exports (~/RSSHub/lib/middleware/parameter.js:14:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
## rsshub.app

```
Error: wrong path
    at module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/parameter.js:14:15)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do01.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/onerror.js:20:9)
```

### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |    centos 7           |
| Node version       |     10.21          |
| if Docker, version |               |

### 额外信息（日志、报错等）

│ last update      │ 2020-06-03T07:37:13.407Z
│ revision         │ 20fc36affc54dfda4d109141c482f361a3ca24d0                                    │
│ comment          │ Merge pull request #4456 from DIYgod/dependabot/npm_and_yarn/vuepress-1.4.1 │
│ branch           │ master

**Comment by nczitzk** [comment]
`/cls/telegragh` 路由是不存在的，所以会报错误 `Error: wrong path`

当前我访问 rsshub.app 的 `/cls/depth` 和 `/cls/telegraph` 两个路由获得以下提示：

```
connect ETIMEDOUT 183.131.207.42:443: target website might be blocking our access, you can host your own RSSHub instance for a better usability.
```

如上述说明，`/cls/depth` 和 `/cls/telegraph` 路由在自建 RSSHub 服务下都可以正常工作。

**Comment by KwToPA** [comment]
突然可以了，原因不明。

**Comment by DIYgod** [comment]
是文档写错了...
