### ISSUE TITLE
雪球组合的rss路径不能打开

### ISSUE THREAD

**Issue by yummyheng** [DIYgod/RSSHub#5007]
报错地址 https://rsshub.app/xueqiu/p/ZH2075374

Looks like something went wrong
Error: wrong path
    at module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/parameter.js:14:15)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do01.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by DIYgod** [comment]
wrong path
