### ISSUE TITLE
instagram "TypeError: Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by jimmy-walker** [DIYgod/RSSHub#5008]
### 路由地址
/instagram/user/:id
### 预期是什么？
返回内容
### 实际发生了什么？
TypeError: Cannot read property '0' of undefined
请问是否Instagram都不能用了？
### 部署相关信息
heroku docker自建，rsshub git bash 3413a3b

### 额外信息（日志、报错等）

```
TypeError: Cannot read property '0' of undefined
    at module.exports (/app/lib/routes/instagram/user.js:15:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cache (/app/lib/middleware/cache.js:203:9)
    at async module.exports (/app/lib/middleware/parameter.js:8:5)
    at async module.exports (/app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/app/lib/middleware/template.js:15:5)
    at async /app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/app/lib/middleware/api-template.js:2:5)
    at async module.exports (/app/lib/middleware/utf8.js:4:5)
    at async module.exports (/app/lib/middleware/debug.js:14:5)
    at async grant (/app/lib/middleware/access-control.js:23:13)
    at async module.exports (/app/lib/middleware/access-control.js:31:20)
    at async module.exports (/app/lib/middleware/header.js:20:5)
    at async module.exports (/app/lib/middleware/onerror.js:20:9)
```

**Comment by DIYgod** [comment]
https://github.com/DIYgod/RSSHub/issues/4863#issuecomment-645761284
