### ISSUE TITLE
Error With Particular Twitter User

### ISSUE THREAD

**Issue by dinosaw** [DIYgod/RSSHub#5168]
- Involved route
`/twitter/user/TwitchSupport/exclude_replies`

- What is expected
To get a feed of tweets from the @TwitchSupport Twitter account excluding replies.

- What is actually happening
Getting the following error message on both my self-hosted deployment **as well as the public RSSHub demo**:

```
Looks like something went wrong
TypeError: Cannot read property 'user' of undefined
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/routes/twitter/user.js:32:30)
    at async cache (/data/wwwroot/do02.rsshub.app/lib/middleware/cache.js:203:9)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)
```

- Self-deployment information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 | Ubuntu 20.04 LTS               |
| Node version       | v12.18.2              |
| if Docker, version | N/A              |

- Additional info (logs errors etc)
**Note:** It can pull the Twitter feed without issue if you remove the `exclude_replies` from the URL (or any of the optional parameters).

**Edit:** It actually may just appear to be an issue with `exclude_replies`. I say this because `exclude_rts` works fine.

**Comment by HenryQW** [comment]
I'm unable to fix the bug as I do not possess a twitter API key.

**Comment by dinosaw** [comment]
I don't understand. There is an [entire Twitter route](https://docs.rsshub.app/en/social-media.html#twitter) in this application, but you're saying you don't own a Twitter API key?

If that is the case, how was the route initially implemented?

And if you can't fix Twitter related issues going forward, would it not be best to simply drop support altogether instead of leaving up documents that state this application works with Twitter?

**Comment by HenryQW** [comment]
The demo runs on the API key owned by the repo owner, which is encrypted and the demo redeploys itself via a CI. I'm a maintainer without access to the unencrypted key. Twitter API application is very tricky these days and I filed 3 times all got rejected.

Plus, the route seems to work on my side. 

![image](https://user-images.githubusercontent.com/5896343/95848303-c8574880-0d45-11eb-8e37-8906d2e1b583.png)
