### ISSUE TITLE
[BUG] bilibili

### ISSUE THREAD

**Issue by poly000** [DIYgod/RSSHub#5199]
请确保已阅读 [文档](https://docs.rsshub.app) 内相关部分，并按照模版提供信息，否则 issue 将被立即关闭。

- 路由地址
 /bilibili/user/video/14803679
- 预期是什么
正常工作
- 实际发生了什么
出错
- 部署相关信息

如果是演示地址(rsshub.app)有此问题请删除此部分。

请确保您部署的是[主线 master 分支](https://github.com/DIYgod/RSSHub/tree/master)最新版 RSSHub。

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |   Archlinux     |
| Node version       |    14.5.0   |
| if Docker, version |               |

- 额外信息（日志、报错等）
```
error: Error in /bilibili/user/video/14803679: Error: this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create an issue</a>
    at module.exports (/home/poly/RSSHub/lib/middleware/parameter.js:19:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/home/poly/RSSHub/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/home/poly/RSSHub/lib/middleware/template.js:15:5)
    at async /home/poly/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/home/poly/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/home/poly/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/home/poly/RSSHub/lib/middleware/debug.js:14:5)
    at async grant (/home/poly/RSSHub/lib/middleware/access-control.js:23:13)
    at async module.exports (/home/poly/RSSHub/lib/middleware/access-control.js:31:20)
    at async module.exports (/home/poly/RSSHub/lib/middleware/header.js:20:5)
    at async module.exports (/home/poly/RSSHub/lib/middleware/onerror.js:20:9)
```

**Comment by prnake** [comment]
@poly000 请阅读相关文档，需要自行部署并配置参数

**Comment by poly000** [comment]
> @poly000 请阅读相关文档，需要自行部署并配置参数

我更新RSSHub后没读…… 我去看下
