### ISSUE TITLE
[BUG]苏州市人民政府 失效了，求更新

### ISSUE THREAD

**Issue by ieliwb** [DIYgod/RSSHub#5276]
- 路由地址
    `/gov/suzhou/news/district`
- 预期是什么

- 实际发生了什么
https://rsshub.app/gov/suzhou/news/district
失效了，求更新

**Comment by MisteryMonster** [comment]
我刚看了没问题，下次把页面返回的错误也发一下吧。

**Comment by Felix2yu** [comment]
`/gov/suzhou/doc`政府信息公开文件路由能正常更新，但`title`、`description`均为空。

`/gov/suzhou/news/:uid`下的11个路由，其中`qxzt`、`sbjzt`、`zwgg`、`news`、`zxrdzt`、`rdzt`都报错如下，另外5个能返回正常内容的最新一条也是5月31日的，已经2个月没有新条目了。

```
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do01.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/onerror.js:20:9)
```
