### ISSUE TITLE
Error in Mastodon User timeline

### ISSUE THREAD

**Issue by catatonik** [DIYgod/RSSHub#5294]
- Involved route
/mastodon/acct/:acct/:only_media?
- What is expected
Display RSS, using URL in docs https://rsshub.app/mastodon/acct/CatWhitney@mastodon.social
- What is actually happening
```
Looks like something went wrong

Error: wrong path
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:14:15)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)
```

**Comment by HenryQW** [comment]
@notofoe 看一下？

**Comment by HenryQW** [comment]
我看了下文档，相关路由需要自建并提供 API key。

https://docs.rsshub.app/social-media.html#mastodon

**Comment by notofoe** [comment]
@catatonik 
The correct feed url should be `/mastodon/acct/:acct/statuses/:only_media?`; I will update english docs soon.
