### ISSUE TITLE
印记中文周刊 无法订阅

### ISSUE THREAD

**Issue by bytemain** [DIYgod/RSSHub#5344]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/docschina/jsweekly
- 预期是什么
正常访问
- 实际发生了什么
![image](https://user-images.githubusercontent.com/13938334/89160849-4e1b8280-d5a4-11ea-9196-8ee37f800874.png)

- 额外信息（日志、报错等）
```
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do01.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/onerror.js:20:9)
```

**Comment by lengthmin** [comment]
我已经在修了

**Comment by dear-lizhihua** [comment]
@HenryQW 又不好使了

**Comment by HenryQW** [comment]
8月3号说在修 辣鸡@lengthmin

**Comment by dear-lizhihua** [comment]
https://rs.docschina.org/
