### ISSUE TITLE
货币政策司公开市场交易公告 无法订阅

### ISSUE THREAD

**Issue by yufei96** [DIYgod/RSSHub#5359]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/pbc/tradeAnnouncement

- 预期是什么
正常访问

- 实际发生了什么
直接打开链接显示*Looks like something went wrong*

- 额外信息（日志、报错等）
`Error: Navigation failed because browser has disconnected!
    at /data/wwwroot/do01.rsshub.app/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:51:147
    at /data/wwwroot/do01.rsshub.app/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:47:62
    at Array.map ()
    at Object.emit (/data/wwwroot/do01.rsshub.app/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:47:43)
    at CDPSession.emit (/data/wwwroot/do01.rsshub.app/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onClosed (/data/wwwroot/do01.rsshub.app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:247:14)
    at Connection._onMessage (/data/wwwroot/do01.rsshub.app/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:94:25)
    at WebSocket. (/data/wwwroot/do01.rsshub.app/node_modules/puppeteer/lib/cjs/puppeteer/common/WebSocketTransport.js:13:32)
    at WebSocket.onMessage (/data/wwwroot/do01.rsshub.app/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:223:5)
    at WebSocket.EventEmitter.emit (domain.js:475:20)
    at Receiver.receiverOnMessage (/data/wwwroot/do01.rsshub.app/node_modules/ws/lib/websocket.js:801:20)
    at Receiver.emit (events.js:223:5)
    at Receiver.EventEmitter.emit (domain.js:475:20)
    at Receiver.dataMessage (/data/wwwroot/do01.rsshub.app/node_modules/ws/lib/receiver.js:436:14)
    at Receiver.getData (/data/wwwroot/do01.rsshub.app/node_modules/ws/lib/receiver.js:366:17)
    at Receiver.startLoop (/data/wwwroot/do01.rsshub.app/node_modules/ws/lib/receiver.js:142:22)
    at Receiver._write (/data/wwwroot/do01.rsshub.app/node_modules/ws/lib/receiver.js:77:10)
    at doWrite (_stream_writable.js:435:12)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Receiver.Writable.write (_stream_writable.js:309:11)
    at Socket.socketOnData (/data/wwwroot/do01.rsshub.app/node_modules/ws/lib/websocket.js:876:35)`

**Comment by nczitzk** [comment]
看上去是 puppeteer 出了问题。对于该路由建议自建服务使用，测试自建服务后该路由可以正常工作。
