### ISSUE TITLE
Bilibili的rss突然无法打开

### ISSUE THREAD

**Issue by pullopen** [DIYgod/RSSHub#5406]
- 完整路由地址，包含所有必选与可选参数
rsshub.app/bilibili/user/video/25522213
- 预期是什么
返回数据
- 实际发生了什么
```
Looks like something went wrong

Error: this route is empty, please check the original site or create an issue
    at module.exports (/app/lib/middleware/parameter.js:19:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (/app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/app/lib/middleware/template.js:15:5)
    at async /app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/app/lib/middleware/api-template.js:2:5)
    at async module.exports (/app/lib/middleware/utf8.js:4:5)
    at async module.exports (/app/lib/middleware/debug.js:14:5)
    at async grant (/app/lib/middleware/access-control.js:23:13)
    at async module.exports (/app/lib/middleware/access-control.js:31:20)
    at async module.exports (/app/lib/middleware/header.js:20:5)
    at async module.exports (/app/lib/middleware/onerror.js:20:9)
```

- 部署相关信息
官方和自己在heroku上的部署都尝试了一下，都出现此类错误。

- 额外信息（日志、报错等）

**Comment by Konano** [comment]
有相同问题。
部署方式为自建。

**Comment by Konano** [comment]
已解决。
git pull 一下就好了。
