### ISSUE TITLE
水木社区用户动态路由出现bug

### ISSUE THREAD

**Issue by ZhuningS** [DIYgod/RSSHub#5411]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/newsmth/account/fef705ec94819a5a87941759e33c0982
- 预期是什么
正常抓取
- 实际发生了什么
Error in RSSHub!
RSSHub

Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do01.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/onerror.js:20:9)
For online documentation and support please refer to docs.rsshub.app.
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by nczitzk** [comment]
这边试了一下可以正常工作

![image](https://user-images.githubusercontent.com/42264778/90198118-4315ed00-de03-11ea-93ca-72da47617c31.png)
