### ISSUE TITLE
twitter list 路由获取失败

### ISSUE THREAD

**Issue by yzkoori** [DIYgod/RSSHub#5421]
- 完整路由地址，包含所有必选与可选参数
/twitter/list/rinno_yui/%E5%A5%BD%E3%81%8D%E3%81%AA%E7%B5%B5%E6%8F%8F%E3%81%8D%E3%81%95%E3%82%93
/twitter/list/yzkoori/doll

- 预期是什么
均能正常获取到rss

- 实际发生了什么
目前第一个list获取失败，第二个正常，查看log发现是8/14上午7点左右发生的，一直未恢复
之前一直是正常运行的，猜测和twitter有关
更新本地文件 / 使用演示地址 现象一致

- 部署相关信息
自己搭建的centos7.3 + node12 / 14 ，以及演示地址现象一致

- 额外信息（日志、报错等）
Looks like something went wrong
Error: Sorry, that page does not exist.
    at Object.exports.makeTwitError (/data/wwwroot/do01.rsshub.app/node_modules/twit/lib/helpers.js:74:13)
    at onRequestComplete (/data/wwwroot/do01.rsshub.app/node_modules/twit/lib/twitter.js:344:25)
    at Request. (/data/wwwroot/do01.rsshub.app/node_modules/twit/lib/twitter.js:364:7)
    at Request.emit (events.js:228:7)
    at Request.EventEmitter.emit (domain.js:475:20)
    at Gunzip. (/data/wwwroot/do01.rsshub.app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:312:28)
    at Gunzip.emit (events.js:228:7)
    at Gunzip.EventEmitter.emit (domain.js:475:20)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by HenryQW** [comment]
twitter 出了船腥版本的API V2，期待有缘人
