### ISSUE TITLE
邮件配置报错

### ISSUE THREAD

**Issue by zsbai** [DIYgod/RSSHub#5437]
- 完整路由地址，包含所有必选与可选参数
/mail/imap/xxxx@qq.com

- 预期是什么
查询邮件
- 实际发生了什么
报错

- 部署相关信息
nodejs:12.18.3
centos7

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）
利用宝塔面板搭建，配置文件：
EMAIL_CONFIG_xxxxxxxx.qq.com=password=xxxxxx&host=imap.qq.com&port=993
报错：
Error: please config email password, host, port in .env file
    at module.exports (/usr/bailu/RSSHub/lib/routes/mail/imap.js:20:15)
    at dispatch (/usr/bailu/RSSHub/node_modules/koa-compose/index.js:42:32)
    at /usr/bailu/RSSHub/node_modules/@koa/router/lib/router.js:372:16
    at dispatch (/usr/bailu/RSSHub/node_modules/koa-compose/index.js:42:32)
    at /usr/bailu/RSSHub/node_modules/koa-compose/index.js:34:12
    at dispatch (/usr/bailu/RSSHub/node_modules/@koa/router/lib/router.js:377:31)
    at dispatch (/usr/bailu/RSSHub/node_modules/koa-compose/index.js:42:32)
    at cache (/usr/bailu/RSSHub/lib/middleware/cache.js:203:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async module.exports (/usr/bailu/RSSHub/lib/middleware/parameter.js:8:5)
    at async module.exports (/usr/bailu/RSSHub/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/usr/bailu/RSSHub/lib/middleware/template.js:15:5)
    at async /usr/bailu/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/usr/bailu/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/usr/bailu/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/usr/bailu/RSSHub/lib/middleware/debug.js:14:5)
    at async grant (/usr/bailu/RSSHub/lib/middleware/access-control.js:23:13)
    at async module.exports (/usr/bailu/RSSHub/lib/middleware/access-control.js:31:20)
    at async module.exports (/usr/bailu/RSSHub/lib/middleware/header.js:20:5)
    at async module.exports (/usr/bailu/RSSHub/lib/middleware/onerror.js:20:9)

**Comment by HenryQW** [comment]
可以搜搜看相关issue，很大可能性是配置错误了

**Comment by kt286** [comment]
可能有几个原因
1. /mail/imap/`xxxx@qq.com`和配置文件中 EMAIL_CONFIG_`xxxx.qq.com`=password=xxxxxx&host=imap.qq.com&port=993中邮箱地址不匹配
2. 修改.env文件以后没有重启服务
3. .env文件没有放置在根目录下

**Comment by HenryQW** [comment]
c500cd20e30e930ad18d4a1eedccf90ff43c54b4 参考新的文档，我测试过了没有问题。
