### ISSUE TITLE
[BUG] 自建RSSHub抓取新榜公众号报错

### ISSUE THREAD

**Issue by Cyberpuncrush** [DIYgod/RSSHub#5469]
- 完整路由地址，包含所有必选与可选参数
/newrank/wechat/MathAndAlgorithm

- 预期是什么
正确抓取公众号内容

- 实际发生了什么
返回错误信息：
TypeError: Cannot read property 'name' of undefined
    at module.exports (/home/realcrush/RSSHub/lib/routes/newrank/wechat.js:20:43)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cache (/home/realcrush/RSSHub/lib/middleware/cache.js:203:9)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/parameter.js:8:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/template.js:15:5)
    at async /home/realcrush/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/debug.js:14:5)
    at async grant (/home/realcrush/RSSHub/lib/middleware/access-control.js:23:13)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/access-control.js:31:20)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/header.js:20:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/onerror.js:20:9)
且持续数小时都是这个错，以前也有抓取失败，但手动刷新源就能恢复

- 部署相关信息
手动部署 npm start
RSSHub今天更新以后出现的错误，之前无此问题

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |        Ubuntu18.04       |
| Node version       |        v12.18.2       |
| if Docker, version |               |

- 额外信息（日志、报错等）
TypeError: Cannot read property 'name' of undefined
    at module.exports (/home/realcrush/RSSHub/lib/routes/newrank/wechat.js:20:43)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cache (/home/realcrush/RSSHub/lib/middleware/cache.js:203:9)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/parameter.js:8:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/template.js:15:5)
    at async /home/realcrush/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/debug.js:14:5)
    at async grant (/home/realcrush/RSSHub/lib/middleware/access-control.js:23:13)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/access-control.js:31:20)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/header.js:20:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/onerror.js:20:9)

**Comment by Cyberpuncrush** [comment]
实验：尝试回滚到更改新榜相关代码前的版本，以及最新版本，在服务器和本地尝试部署均报一样的错TypeError: Cannot read property 'name' of undefined，非常奇怪，这样看并不是服务器ip被禁？

**Comment by HenryQW** [comment]
应该是API返回格式有问题？@BossDoge

**Comment by Cyberpuncrush** [comment]
更新：
今天再次尝试，成功抓取，不再报错，应该是新榜的token限制了一天的调用总次数，或者一天内触发反爬机制一定次数予以整天封禁。
