### ISSUE TITLE
[BUG] 自建YouTube时间线抓取错误

### ISSUE THREAD

**Issue by Cyberpuncrush** [DIYgod/RSSHub#5478]
- 完整路由地址，包含所有必选与可选参数
https://my_ip_address:1200/youtube/user/82fAbIX5l8tHKGeKRLL2rQ

- 预期是什么
正确抓取YouTube个人时间线，YouTube API KEY是刚在YouTube申请的，一次都没用过，权限也选择的是全部不受限

- 实际发生了什么
返回错误：
Error: The request cannot be completed because you have exceeded your quota.
    at Gaxios._request (/home/realcrush/RSSHub/node_modules/_gaxios@3.1.0@gaxios/build/src/gaxios.js:89:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/realcrush/RSSHub/lib/routes/youtube/utils.js:54:25
    at async Object.app.context.cache.tryGet (/home/realcrush/RSSHub/lib/middleware/cache.js:133:17)
    at async Object.getChannelWithUsername (/home/realcrush/RSSHub/lib/routes/youtube/utils.js:53:9)
    at async module.exports (/home/realcrush/RSSHub/lib/routes/youtube/user.js:11:25)
    at async cache (/home/realcrush/RSSHub/lib/middleware/cache.js:203:9)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/parameter.js:8:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/template.js:15:5)
    at async /home/realcrush/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/debug.js:14:5)
    at async grant (/home/realcrush/RSSHub/lib/middleware/access-control.js:23:13)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/access-control.js:31:20)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/header.js:20:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/onerror.js:20:9)

- 部署相关信息
自建rsshub，最新版本

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       Ubuntu18.04        |
| Node version       |        v12.18.2       |
| if Docker, version |               |

- 额外信息（日志、报错等）
Error: The request cannot be completed because you have exceeded your quota.
    at Gaxios._request (/home/realcrush/RSSHub/node_modules/_gaxios@3.1.0@gaxios/build/src/gaxios.js:89:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/realcrush/RSSHub/lib/routes/youtube/utils.js:54:25
    at async Object.app.context.cache.tryGet (/home/realcrush/RSSHub/lib/middleware/cache.js:133:17)
    at async Object.getChannelWithUsername (/home/realcrush/RSSHub/lib/routes/youtube/utils.js:53:9)
    at async module.exports (/home/realcrush/RSSHub/lib/routes/youtube/user.js:11:25)
    at async cache (/home/realcrush/RSSHub/lib/middleware/cache.js:203:9)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/parameter.js:8:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/template.js:15:5)
    at async /home/realcrush/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/debug.js:14:5)
    at async grant (/home/realcrush/RSSHub/lib/middleware/access-control.js:23:13)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/access-control.js:31:20)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/header.js:20:5)
    at async module.exports (/home/realcrush/RSSHub/lib/middleware/onerror.js:20:9)

**Comment by HenryQW** [comment]
我本地工作正常
