### ISSUE TITLE
今日热榜抓取源出现错误

### ISSUE THREAD

**Issue by flf2015** [DIYgod/RSSHub#5594]
今日热榜
#榜单
作者: @LogicJake

举例: https://rsshub.app/tophub/Om4ejxvxEN

路由: /tophub/:id

参数:
id, 必选 - 榜单id，可在 URL 中找到

----------------------------------------------
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)
For online documentation and support please refer to docs.rsshub.app.

**Comment by laampui** [comment]
本地看了是可以的，线上的却会出现楼主所描述的问题。

**Comment by TonyRL** [comment]
/test
```routes
/tophub/Om4ejxvxEN
```
