### ISSUE TITLE
路透社中文频道抓取错误

### ISSUE THREAD

**Issue by wym3253** [DIYgod/RSSHub#5599]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/reuters/channel/cn/analyses
- 预期是什么
正常抓取
- 实际发生了什么
报错
- 部署相关信息
官方与自建均出现错误

| Env                | Value         |
| ------------------ | ------------- |
| OS                 | Debian              |
| Node version       | v12.18.3              |
| if Docker, version |               |

- 额外信息（日志、报错等）
TypeError: Cannot read property '0' of null
    at Object.ProcessFeed (/data/wwwroot/do02.rsshub.app/lib/routes/reuters/utils.js:25:69)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async /data/wwwroot/do02.rsshub.app/lib/routes/reuters/channel.js:147:104
    at async Object.app.context.cache.tryGet (/data/wwwroot/do02.rsshub.app/lib/middleware/cache.js:133:17)
    at async /data/wwwroot/do02.rsshub.app/lib/routes/reuters/channel.js:147:63
    at async Promise.all (index 5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/routes/reuters/channel.js:147:19)
    at async cache (/data/wwwroot/do02.rsshub.app/lib/middleware/cache.js:203:9)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:8:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)

**Comment by duguyipiao** [comment]
us和uk也不行了，例如：
https://rsshub.app/reuters/channel/us/world
https://rsshub.app/reuters/channel/uk/world
