### ISSUE TITLE
Outage.Report seems to be broken

### ISSUE THREAD

**Issue by PeterDaveHello** [DIYgod/RSSHub#5636]
- The involved route, with all required and optional parameters

https://rsshub.app/outagereport/ubisoft/5

(from the doc https://docs.rsshub.app/forecast.html#outage-report)

- What is expected

A valid RSS feed returned

- What is actually happening

I've two different error here, both not work as expected:

1. Error 502 / Bad gateway

2. `Looks like something went wrong`

```
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do01.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do01.rsshub.app/lib/middleware/onerror.js:20:9)
```

- Additional info (logs errors etc)

I've tried with some other services' outage report, like Slack and GitHub, not just Ubisoft from the document, but none of them works.

**Comment by ueiu** [comment]
Can you accept the output RSS if the latest value is 0？
example：
![image](https://user-images.githubusercontent.com/39592269/93035772-849eef80-f670-11ea-9e9c-c08d15da59ca.png)

**Comment by PeterDaveHello** [comment]
> Can you accept the output RSS if the latest value is 0？

Not sure the relation with this issue?

**Comment by ueiu** [comment]
When the current logic is 0, rss is not output, resulting in not working.

**Comment by ueiu** [comment]
I mean, can you accept rss output at 0?

**Comment by PeterDaveHello** [comment]
Personally, I can. Also think it should be, instead of error ;)

**Comment by PeterDaveHello** [comment]
@ueiu @HenryQW thanks for the quick fix!
Looks like there is another small issue after the revise, no matter if there is any outage report count change, the RSS reader keeps update new feeds, even there is no any outage report, not sure if we can use the most recent report datetime + report count as the guid of the feed item, to avoid the keep updating 0 reports issue? Many thanks!
