### ISSUE TITLE
中国地震台抓取源出现错误

### ISSUE THREAD

**Issue by shitianshiwa** [DIYgod/RSSHub#5718]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/earthquake/ceic/1
- 预期是什么
```
以下为显示样子的示例，非真实数据（炸了并没有内容）
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>
<![CDATA[ 最近24小时地震信息 ]]>
</title>
<link>http://www.ceic.ac.cn/speedsearch</link>
<atom:link href="http://rsshub.app/earthquake/ceic/2" rel="self" type="application/rss+xml"/>
<description>
<![CDATA[
最近24小时地震信息 - Made with love by RSSHub(https://github.com/DIYgod/RSSHub)
]]>
</description>
<generator>RSSHub</generator>
<webMaster>i@diygod.me (DIYgod)</webMaster>
<language>zh-cn</language>
<lastBuildDate>Thu, 24 Sep 2020 05:37:39 GMT</lastBuildDate>
<ttl>60</ttl>
<item>
<title>
<![CDATA[ 台湾台东县发生3.7级地震 ]]>
</title>
<description>
<![CDATA[
发震时刻(UTC+8) 2020-09-23 12:00:01<br>参考位置 台湾台东县<br>震级(M) 3.7<br>纬度(°) 23.36<br>经度(°) 121.47<br>深度(千米) 13<br>录入时间 2020-09-23 12:07:25
]]>
</description>
<pubDate>Wed, 23 Sep 2020 04:00:01 GMT</pubDate>
<guid isPermaLink="false">CD20200923120001</guid>
<link>http://www.ceic.ac.cn/CD20200923120001.html</link>
</item>
</channel>
</rss>
```
- 实际发生了什么
```
Looks like something went wrong
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:19:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)
```

- 部署相关信息
演示地址
- 额外信息（日志、报错等）
获取信息api的实际情况
http://www.ceic.ac.cn/ajax/speedsearch?num=1&&page=1
({"shuju":[],"jieguo":"\u6700\u8fd124\u5c0f\u65f6\u5730\u9707\u4fe1\u606f","page":"","num":0})
"\u6700\u8fd124\u5c0f\u65f6\u5730\u9707\u4fe1\u606f"=最近24小时地震信息

**Comment by shitianshiwa** [comment]
https://github.com/DIYgod/RSSHub/blob/master/lib/middleware/parameter.js#L18
```
if ((!ctx.state.data.item || ctx.state.data.item.length === 0) && !ctx.state.data.allowEmpty) {
            throw Error('this route is empty, please check the original site or <a href="https://github.com/DIYgod/RSSHub/issues/new/choose">create an issue</a>');
        }
```
看来修不了了

**Comment by nczitzk** [comment]
这边测试在本地和 [rsshub.app](https://rsshub.app/earthquake/ceic/1) 上该路由都可以正常工作

**Comment by shitianshiwa** [comment]
> 这边测试在本地和 [rsshub.app](https://rsshub.app/earthquake/ceic/1) 上该路由都可以正常工作

应该可以不解决
出错原因是，源数据有一定概率出现[]
https://github.com/DIYgod/RSSHub/blob/master/lib/routes/earthquake/ceic.js#L41

`({"shuju":[],"jieguo":"\u6700\u8fd124\u5c0f\u65f6\u5730\u9707\u4fe1\u606f","page":"","num":0})`
"\u6700\u8fd124\u5c0f\u65f6\u5730\u9707\u4fe1\u606f"=最近24小时地震信息

**Comment by simoin** [comment]
这应该是24小时里没有地震吧

![](https://i.imgur.com/W26pQEa.png)

**Comment by shitianshiwa** [comment]
> 这应该是24小时里没有地震吧
> 
> ![](https://camo.githubusercontent.com/330dd6880e40ab3413eee98530c18e18b8441963/68747470733a2f2f692e696d6775722e636f6d2f573236705145612e706e67)

对
