### ISSUE TITLE
Bilibili 用户关注视频动态 失效

### ISSUE THREAD

**Issue by Konano** [DIYgod/RSSHub#5782]
- 完整路由地址，包含所有必选与可选参数

/bilibili/followings/video/xxxxxx

- 预期是什么

200

- 实际发生了什么

404

- 部署相关信息

- 额外信息（日志、报错等）

TypeError: Cannot read property 'map' of undefined
    at module.exports (/root/RSSHub/lib/routes/bilibili/followings_video.js:27:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async cache (/root/RSSHub/lib/middleware/cache.js:203:9)
    at async module.exports (/root/RSSHub/lib/middleware/parameter.js:9:5)
    at async module.exports (/root/RSSHub/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/root/RSSHub/lib/middleware/template.js:15:5)
    at async /root/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/root/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/root/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/root/RSSHub/lib/middleware/header.js:20:5)
    at async module.exports (/root/RSSHub/lib/middleware/debug.js:14:5)
    at async grant (/root/RSSHub/lib/middleware/access-control.js:23:13)
    at async module.exports (/root/RSSHub/lib/middleware/access-control.js:31:20)
    at async module.exports (/root/RSSHub/lib/middleware/onerror.js:20:9)

**Comment by Konano** [comment]
可知原因是 cookie 失效。
