### ISSUE TITLE
Acfun叕不行了，老样子route is empty

### ISSUE THREAD

**Issue by Garrise** [DIYgod/RSSHub#5814]
- 完整路由地址，包含所有必选与可选参数
https://rsshub.app/acfun/bangumi/6003907
- 预期是什么
返回正确的RSS信息
- 实际发生了什么
返回错误信息
Error: this route is empty, please check the original site or create an issue
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:20:19)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)
- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |               |
| Node version       |               |
| if Docker, version |               |

- 额外信息（日志、报错等）

**Comment by black-desk** [comment]
实测没问题
![https://rsshub.app/acfun/bangumi/6003907](https://i.loli.net/2020/10/08/DusZvhOJrGPKMjd.png)

**Comment by HenryQW** [comment]
测试没问题。
