### ISSUE TITLE
Wordpress for www.hpmor.xyz throws

### ISSUE THREAD

**Issue by Jack-Works** [DIYgod/RSSHub#5823]
- The involved route, with all required and optional parameters

https://rsshub.app/blogs/wordpress/www.hpmor.xyz/

- What is expected

Provide an RSS

- What is actually happening

```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:223:5)
    at TLSSocket.EventEmitter.emit (domain.js:475:20)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12)
```

**Comment by hoilc** [comment]
源站证书链不全 https://www.ssllabs.com/ssltest/analyze.html?d=www.hpmor.xyz&latest

建议直接使用 https://www.hpmor.xyz/feed/
