### ISSUE TITLE
RSSHub 莫名被 Kill

### ISSUE THREAD

**Issue by Konano** [DIYgod/RSSHub#5953]
```
Oct 19 20:17:24 iZ2zebcpqw746wm1b764k1Z cnpm[8578]: error: Request undefined fail, retry attempt #1: RequestError: Client network socket disconnected before secure TLS connection was established
Oct 19 20:42:29 iZ2zebcpqw746wm1b764k1Z cnpm[8578]: Killed
Oct 19 20:42:30 iZ2zebcpqw746wm1b764k1Z cnpm[8578]: npm ERR! code ELIFECYCLE
Oct 19 20:42:30 iZ2zebcpqw746wm1b764k1Z cnpm[8578]: npm ERR! errno 137
Oct 19 20:42:30 iZ2zebcpqw746wm1b764k1Z cnpm[8578]: npm ERR! rsshub@1.0.0 start: `node lib/index.js`
Oct 19 20:42:30 iZ2zebcpqw746wm1b764k1Z cnpm[8578]: npm ERR! Exit status 137
Oct 19 20:42:30 iZ2zebcpqw746wm1b764k1Z cnpm[8578]: npm ERR!
Oct 19 20:42:30 iZ2zebcpqw746wm1b764k1Z cnpm[8578]: npm ERR! Failed at the rsshub@1.0.0 start script.
Oct 19 20:42:30 iZ2zebcpqw746wm1b764k1Z cnpm[8578]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Oct 19 20:42:30 iZ2zebcpqw746wm1b764k1Z cnpm[8578]: npm ERR! A complete log of this run can be found in:
Oct 19 20:42:30 iZ2zebcpqw746wm1b764k1Z cnpm[8578]: npm ERR!     /root/.npm/_logs/2020-10-19T12_42_29_863Z-debug.log
```

`/root/.npm/_logs/2020-10-19T12_42_29_863Z-debug.log` 内容：
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm',
1 verbose cli   '--userconfig=/tmp/.cnpmrc',
1 verbose cli   '--disturl=https://npm.taobao.org/mirrors/node',
1 verbose cli   '--registry=https://r.npm.taobao.org',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle rsshub@1.0.0~prestart: rsshub@1.0.0
6 info lifecycle rsshub@1.0.0~start: rsshub@1.0.0
7 verbose lifecycle rsshub@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle rsshub@1.0.0~start: PATH: /usr/local/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/RSSHub/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle rsshub@1.0.0~start: CWD: /root/RSSHub
10 silly lifecycle rsshub@1.0.0~start: Args: [ '-c', 'node lib/index.js' ]
11 silly lifecycle rsshub@1.0.0~start: Returned: code: 137  signal: null
12 info lifecycle rsshub@1.0.0~start: Failed to exec start script
13 verbose stack Error: rsshub@1.0.0 start: `node lib/index.js`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid rsshub@1.0.0
15 verbose cwd /root/RSSHub
16 verbose Linux 4.4.0-117-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/tmp/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://r.npm.taobao.org" "start"
18 verbose node v12.16.1
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 137
22 error rsshub@1.0.0 start: `node lib/index.js`
22 error Exit status 137
23 error Failed at the rsshub@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```

触发条件未知。

**Comment by HenryQW** [comment]
`Client network socket disconnected before secure TLS connection was established`

是不是用代理了

**Comment by jianfei96** [comment]
被kill正常吧，这程序有时候会跑到CPU 100%，限制高的VPS上面就会被kill了

**Comment by Konano** [comment]
> `Client network socket disconnected before secure TLS connection was established`
> 
> 是不是用代理了

啊这是没有的

**Comment by hoilc** [comment]
退出码137

内存不足，被系统kill
