### ISSUE TITLE
观察者网出错

### ISSUE THREAD

**Issue by roberChen** [DIYgod/RSSHub#5969]
---
name: 🐛 Bug 报告
about: 观察者网
---

- 完整路由地址，包含所有必选与可选参数: https://rsshub.app/guanchazhe/index/all

- 预期是什么: 正常访问

- 实际发生了什么: 出现错误

- 部署相关信息: 官方源

- 额外信息（日志、报错等）: 见下

```bash
TypeError: Cannot read property 'map' of undefined
    at module.exports (/data/wwwroot/do02.rsshub.app/lib/routes/guanchazhe/index.js:206:29)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async cache (/data/wwwroot/do02.rsshub.app/lib/middleware/cache.js:203:9)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/parameter.js:9:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/template.js:15:5)
    at async /data/wwwroot/do02.rsshub.app/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/api-template.js:2:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/utf8.js:4:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/header.js:20:5)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/debug.js:14:5)
    at async grant (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:23:13)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/access-control.js:48:24)
    at async module.exports (/data/wwwroot/do02.rsshub.app/lib/middleware/onerror.js:20:9)

```

相关代码(206行): https://github.com/DIYgod/RSSHub/blob/e028a8e6dfecc3580a59ffb05d3db9f82952d8f3/lib/routes/guanchazhe/index.js#L200-L214

**Comment by roberChen** [comment]
# 可能的原因
在短暂的分析后,我认为这个bug的原因是相关api的网址发生了变化:
https://github.com/DIYgod/RSSHub/blob/e028a8e6dfecc3580a59ffb05d3db9f82952d8f3/lib/routes/guanchazhe/index.js#L10

应当改为

```suggestion
-        gundong: { name: '滚动新闻', url: 'https://www.guancha.cn/api/new_gundong.htm' },
+        gundong: { name: '滚动新闻', url: 'https://www.guancha.cn/api/gundong.htm' },
```

**Comment by roberChen** [comment]
# 已发起尝试解决bug的pr
我提交了pr #5970 尝试解决这个问题,不保证有效.
