### ISSUE TITLE
快递100 路由疑似已经不可用

### ISSUE THREAD

**Issue by RtYkk** [DIYgod/RSSHub#6598]
- 完整路由地址，包含所有必选与可选参数
/kuaidi100/track/shunfeng/SF1007896781640/0383
（此处若替换为自己的快递信息仍然不可用）
- 预期是什么
显示快递信息
- 实际发生了什么
报错
- 部署相关信息
自建

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |       Debian 10        |
| Node version       |        v14.15.0       |
| Npm version       |        6.14.9       |
| if Docker, version |               |

- 额外信息（日志、报错等）
`Error message: Error: 暂时无法获取快递信息，请稍后重试...
    at Object.getQuery (/home/software/RSSHub/RSSHub/lib/routes/kuaidi100/utils.js:205:27)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports (/home/software/RSSHub/RSSHub/lib/routes/kuaidi100/index.js:18:17)
    at async cache (/home/software/RSSHub/RSSHub/lib/middleware/cache.js:203:9)
    at async module.exports (/home/software/RSSHub/RSSHub/lib/middleware/parameter.js:9:5)
    at async module.exports (/home/software/RSSHub/RSSHub/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/home/software/RSSHub/RSSHub/lib/middleware/template.js:19:5)
    at async /home/software/RSSHub/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/home/software/RSSHub/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/home/software/RSSHub/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/home/software/RSSHub/RSSHub/lib/middleware/header.js:21:5)
    at async module.exports (/home/software/RSSHub/RSSHub/lib/middleware/debug.js:14:5)
    at async grant (/home/software/RSSHub/RSSHub/lib/middleware/access-control.js:23:13)
    at async module.exports (/home/software/RSSHub/RSSHub/lib/middleware/access-control.js:31:20)
    at async module.exports (/home/software/RSSHub/RSSHub/lib/middleware/onerror.js:20:9)`

**Comment by NeverBehave** [comment]
可以提供一个在官网可以查询到信息的id但是rss无法获取的例子吗？

**Comment by RtYkk** [comment]
> 可以提供一个在官网可以查询到信息的id但是rss无法获取的例子吗？

感谢回复。刚刚去试了一下，好像是快递 100 本身出现了问题？因为我目前没有还在运送中的快递，最近的快递也已经在 7 号送达，所以我只能试了试三家公司（分别是顺丰，中通，圆通）的快递单号，都能在各个快递公司的官网上查询到结果，快递 100 全都是查无结果，不知道是不是因为快递 100 查不了旧的信息，但没道理啊……有两个单号我在第一次查询时还跳出了完全不匹配的结果，也就是显示了另一个快递的信息。
查询环境是：快递 100 的 web [(https://www.kuaidi100.com/)](https://www.kuaidi100.com/) ,未登录状态。

**Comment by NeverBehave** [comment]
网页版似乎是有问题的, 不匹配或者是查无结果基本上是当系统检测到参数异常或者是信息太久查不到
但是在官网查询也是无效的, 所以基本断定API坏了
