### ISSUE TITLE
npm install 出现 error

### ISSUE THREAD

**Issue by jianfei96** [DIYgod/RSSHub#6841]
#### 路由地址（不包含参数）

```routes
非路由问题
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
非路由问题
```

#### 相关文档地址

- [部署安装](https://docs.rsshub.app/install/#ansible-bu-shu-an-zhuang)

#### 预期是什么
顺利安装

#### 实际发生了什么
```
make: *** [dicts.target.mk:26: Release/STPhrases.ocd2] Segmentation fault (core dumped)
make: Leaving directory '/srv/http/RSSHub/node_modules/opencc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.10.12-lqx1-1-lqx
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/srv/http/RSSHub/node_modules/opencc/build/Release/opencc.node" "--module_name=opencc" "--module_path=/srv/http/RSSHub/node_modules/opencc/build/Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /srv/http/RSSHub/node_modules/opencc
gyp ERR! node -v v10.23.2
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/srv/http/RSSHub/node_modules/opencc/build/Release/opencc.node --module_name=opencc --module_path=/srv/http/RSSHub/node_modules/opencc/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/srv/http/RSSHub/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.10.12-lqx1-1-lqx
node-pre-gyp ERR! command "/usr/bin/node" "/srv/http/RSSHub/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /srv/http/RSSHub/node_modules/opencc
node-pre-gyp ERR! node -v v10.23.2
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/srv/http/RSSHub/node_modules/opencc/build/Release/opencc.node --module_name=opencc --module_path=/srv/http/RSSHub/node_modules/opencc/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
[opencc] Removing "/srv/http/RSSHub/node_modules/opencc/build/Release"
make: Entering directory '/srv/http/RSSHub/node_modules/opencc/build'
```

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |      Arch Linux         |
| Node version       |        10,12,14       |
| if Docker, version |       None        |

- 额外信息（日志、报错等）
- log
[2021-02-03T11_20_26_305Z-debug.log](https://github.com/DIYgod/RSSHub/files/5918028/2021-02-03T11_20_26_305Z-debug.log)

**Comment by NeverBehave** [comment]
OpenCC问题，未来可能考虑将这个部分的功能移动到单独的项目部分
https://github.com/DIYgod/RSSHub/issues/6785
