### ISSUE TITLE
熊猫直播不支持星颜星秀房间

### ISSUE THREAD

**Issue by wutea7** [DIYgod/RSSHub#691]
星颜星秀直播间的 URL 为 https://xingyan.panda.tv/xxxxxx

其中 xxxxxx 为房间号

根据路由设置 RSS 地址应为 https://rsshub.app/panda/room/xxxxxx

但结果提示如下：

```
RSSHub 发生了一些意外:

TypeError: Cannot read property 'name' of undefined
    at module.exports (/app/routes/panda/room.js:17:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by DIYgod** [comment]
超时，issue 暂时关闭
