### ISSUE TITLE
npm install rsshub 似乎一直执行不完……

### ISSUE THREAD

**Issue by nielinjie** [DIYgod/RSSHub#7194]
如题，既不失败也不成功，报错是报了挺多，有同学可以帮助的一下么？ -

```
pm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/14.0.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --module=/Users/nielinjie/Projects/sizhiComm/searchFeed/node_modules/opencc/build/Release/opencc.node --module_name=opencc --module_path=/Users/nielinjie/Projects/sizhiComm/searchFeed/node_modules/opencc/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/nielinjie/Projects/sizhiComm/searchFeed/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm ERR! node-pre-gyp ERR! System Darwin 20.3.0
npm ERR! node-pre-gyp ERR! command "/usr/local/Cellar/node/14.0.0/bin/node" "/Users/nielinjie/Projects/sizhiComm/searchFeed/node_modules/.bin/node-pre-gyp" "rebuild"
npm ERR! node-pre-gyp ERR! cwd /Users/nielinjie/Projects/sizhiComm/searchFeed/node_modules/opencc
npm ERR! node-pre-gyp ERR! node -v v14.0.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.14.0
npm ERR! node-pre-gyp ERR! not ok
```

我用的版本如下，源是npm的原始源，用了梯子 - 

```
➜  searchFeed git:(master) ✗ node --version
v14.0.0
➜  searchFeed git:(master) ✗ npm --version 
7.5.4
```

**Comment by NeverBehave** [comment]
merged with #6785

**Comment by nielinjie** [comment]
似乎一直在这个地方反复重定向。
```
difflib: http fetch GET 304 https://codeload.github.com/postlight/difflib.js/tar.gz/32e8e38c7fcd935241b9baab71bb432fd9b166ed 18826ms (from cache)
```
