### ISSUE TITLE
部分微博用户手机版无法获取

### ISSUE THREAD

**Issue by kasora** [DIYgod/RSSHub#7202]
#### 路由地址（不包含参数）

```
/weibo/user
```

#### 完整路由地址，包含所有必选与可选参数

```
https://rsshub.app/weibo/user/1240852941
```

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#wei-bo

#### 预期是什么
能够正确的获取到 [该用户](https://weibo.com/caisemiyu) 的 timeline

#### 实际发生了什么
手机版无法打开该用户主页，桌面版可以正常打开
[此处](https://github.com/DIYgod/RSSHub/blob/5298f845f2/lib/routes/weibo/user.js#L29) 预设的返回值结构错误
对应的接口为 `https://m.weibo.cn/api/container/getIndex?type=uid&value=1240852941`

- 额外信息（日志、报错等）
```
error: Error in /weibo/user/1240852941: TypeError: Cannot read property '1' of undefined
    at module.exports (/home/ntzyz/RSSHub/lib/routes/weibo/user.js:29:66)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async cache (/home/ntzyz/RSSHub/lib/middleware/cache.js:172:9)
    at async module.exports (/home/ntzyz/RSSHub/lib/middleware/parameter.js:9:5)
    at async module.exports (/home/ntzyz/RSSHub/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/home/ntzyz/RSSHub/lib/middleware/template.js:19:5)
    at async /home/ntzyz/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/home/ntzyz/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/home/ntzyz/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/home/ntzyz/RSSHub/lib/middleware/header.js:21:5)
    at async module.exports (/home/ntzyz/RSSHub/lib/middleware/debug.js:9:5)
    at async grant (/home/ntzyz/RSSHub/lib/middleware/access-control.js:24:13)
    at async module.exports (/home/ntzyz/RSSHub/lib/middleware/access-control.js:32:20)
    at async module.exports (/home/ntzyz/RSSHub/lib/middleware/onerror.js:21:9)
```

**Comment by Rongronggg9** [comment]
> [此处](https://github.com/DIYgod/RSSHub/blob/5298f845f2/lib/routes/weibo/user.js) 预设的返回值结构错误

Not really. Fixing the "expected structure" would not help fix the issue.

For more details: https://github.com/DIYgod/RSSHub/issues/10046#issuecomment-1167831199
