### ISSUE TITLE
[BUG] 无法获取B站用户关注动态

### ISSUE THREAD

**Issue by YehowahLiu** [DIYgod/RSSHub#7225]
#### 路由地址（不包含参数）

```routes
/bilibili/followings/video/:uid/:disableEmbed?
```

#### 完整路由地址，包含所有必选与可选参数

```fullroutes
http://127.0.0.1:1200/bilibili/followings/dynamic/54438788
```

#### 相关文档地址

- https://docs.rsshub.app/social-media.html#bilibili
- https://docs.rsshub.app/install/#pei-zhi-bu-fen-rss-mo-kuai-pei-zhi

#### 预期是什么
正确获取用户关注动态的时间线

#### 实际发生了什么
```
Error message: Error: 对应 uid 的 Bilibili 用户的 Cookie 已过期
```

#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |           Arch Linux    |
| Node version       |        V15.12.0       |
| if Docker, version |               |

#### 额外信息（日志、报错等）

- 错误信息
```
Route requested: /bilibili/followings/dynamic/54438788

Error message: Error: 对应 uid 的 Bilibili 用户的 Cookie 已过期
    at module.exports (/home/redme/Software/rsshub/lib/routes/bilibili/followings_dynamic.js:26:15)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async cache (/home/redme/Software/rsshub/lib/middleware/cache.js:172:9)
    at async module.exports (/home/redme/Software/rsshub/lib/middleware/parameter.js:9:5)
    at async module.exports (/home/redme/Software/rsshub/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/home/redme/Software/rsshub/lib/middleware/template.js:19:5)
    at async /home/redme/Software/rsshub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/home/redme/Software/rsshub/lib/middleware/api-template.js:2:5)
    at async module.exports (/home/redme/Software/rsshub/lib/middleware/utf8.js:4:5)
    at async module.exports (/home/redme/Software/rsshub/lib/middleware/header.js:21:5)
    at async module.exports (/home/redme/Software/rsshub/lib/middleware/debug.js:9:5)
    at async grant (/home/redme/Software/rsshub/lib/middleware/access-control.js:24:13)
    at async module.exports (/home/redme/Software/rsshub/lib/middleware/access-control.js:32:20)
    at async module.exports (/home/redme/Software/rsshub/lib/middleware/onerror.js:21:9)
```

- .env
```
# redme @ arch in ~/Software/rsshub on git:master x [19:11:20] 
$ cat .env 
PROXY_URL=http://127.0.0.1:8889
BILIBILI_COOKIE_54438788=xxxxxxxxx,xxxxxxxxxx,xxxxx*xx
```
- 获取cookie的界面
![图片](https://user-images.githubusercontent.com/52659312/111904230-c9bd3780-8a80-11eb-921f-23080bf8c60e.png)

**Comment by Qeynos** [comment]
http://my.host:1200/bilibili/user/dynamic/54438788

我可以正常抓取，是路由写得不对吧

**Comment by TigerCubDen** [comment]
试试复制整段Cookie进去而不仅仅是SESSDATA字段。

**Comment by YehowahLiu** [comment]
> 试试复制整段Cookie进去而不仅仅是SESSDATA字段。

可行，谢谢!

**Comment by maquedexiju** [comment]
萌新求问，如何“复制整段 Cookie”？

**Comment by YehowahLiu** [comment]
> > > 试试复制整段Cookie进去而不仅仅是SESSDATA字段。
> > 
> > 
> > 可行，谢谢!
> 
> 萌新求问，如何“复制整段 Cookie”？

Firefox上的操作如图：
![2021-04-15_17-59](https://user-images.githubusercontent.com/52659312/114851466-74244280-9e14-11eb-8b10-4426c032f218.png)

**Comment by maquedexiju** [comment]
> > > > 试试复制整段Cookie进去而不仅仅是SESSDATA字段。
> > > 
> > > 
> > > 可行，谢谢!
> > 
> > 
> > 萌新求问，如何“复制整段 Cookie”？
> 
> Firefox上的操作如图：
> ![2021-04-15_17-59](https://user-images.githubusercontent.com/52659312/114851466-74244280-9e14-11eb-8b10-4426c032f218.png)

感谢！已解决

**Comment by wujunchuan** [comment]
既然是这样的话，为什么在文档里还是写只复制 `SESSDATA` 字段呢？是否需要一个 PR 更新文档

**Comment by TigerCubDen** [comment]
> 既然是这样的话，为什么在文档里还是写只复制 `SESSDATA` 字段呢？是否需要一个 PR 更新文档

你可以去提交一下pr

**Comment by moving-hawk** [comment]
soga, 我复制了sessdata不行....
