### ISSUE TITLE
Cannot login with the Instagram route

### ISSUE THREAD

**Issue by chawaa** [DIYgod/RSSHub#7289]
- The involved route, with all required and optional parameters

Instagram route via my instance with correct Instagram credentials, e.g. myrsshub/instagram/user/93.minho

- What is expected

The route return a feed.

- What is actually happening

I get an error:

```
Route requested: /instagram/user/93.minho
Error message: IgLoginRequiredError: GET /api/v1/users/search/?timezone_offset=28800&q=93.minho&count=30 - 403 Forbidden; login_required
    at Request.handleResponseError (C:\Users\90794\Desktop\rsshub\node_modules\instagram-private-api\dist\core\request.js:113:24)
    at Request.send (C:\Users\90794\Desktop\rsshub\node_modules\instagram-private-api\dist\core\request.js:53:28)
    at async UserRepository.search (C:\Users\90794\Desktop\rsshub\node_modules\instagram-private-api\dist\repositories\user.repository.js:24:26)
    at async UserRepository.searchExact (C:\Users\90794\Desktop\rsshub\node_modules\instagram-private-api\dist\repositories\user.repository.js:36:24)
    at async UserRepository.getIdByUsername (C:\Users\90794\Desktop\rsshub\node_modules\instagram-private-api\dist\repositories\user.repository.js:81:22)
    at async loadContent (C:\Users\90794\Desktop\rsshub\lib\routes\instagram\index.js:21:22)
    at async module.exports (C:\Users\90794\Desktop\rsshub\lib\routes\instagram\index.js:85:20)
    at async cache (C:\Users\90794\Desktop\rsshub\lib\middleware\cache.js:172:9)
    at async module.exports (C:\Users\90794\Desktop\rsshub\lib\middleware\parameter.js:9:5)
    at async module.exports (C:\Users\90794\Desktop\rsshub\lib\middleware\anti-hotlink.js:33:5)
    at async module.exports (C:\Users\90794\Desktop\rsshub\lib\middleware\template.js:19:5)
    at async C:\Users\90794\Desktop\rsshub\lib\middleware\api-response-handler.js:143:9
    at async module.exports (C:\Users\90794\Desktop\rsshub\lib\middleware\api-template.js:2:5)
    at async module.exports (C:\Users\90794\Desktop\rsshub\lib\middleware\utf8.js:4:5)
    at async module.exports (C:\Users\90794\Desktop\rsshub\lib\middleware\header.js:21:5)
    at async module.exports (C:\Users\90794\Desktop\rsshub\lib\middleware\debug.js:9:5)
    at async grant (C:\Users\90794\Desktop\rsshub\lib\middleware\access-control.js:24:13)
    at async module.exports (C:\Users\90794\Desktop\rsshub\lib\middleware\access-control.js:32:20)
    at async module.exports (C:\Users\90794\Desktop\rsshub\lib\middleware\onerror.js:21:9)
```

- Self-deployment information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |      centos 7.8       |
| Node version       |     v12.14.1         |
| if Docker, version |          ❌             |

- Additional info (logs errors etc)

I have configured RSSHub by setting environment variables

`.env`  file

```
IG_PROXY=socks://127.0.0.1:58591
IG_USERNAME=******
IG_PASSWORD=*****
```
Have successfully logged in. But Instagram forced to change the password. After that, this error occurred. I registered a new account and still have this problem.

No two factor authentication, and Instagram didn't show me any information. 

Thanks!

**Comment by shizunge** [comment]
Similar problem.

**Comment by shizunge** [comment]
Besides
```
Error message: IgLoginRequiredError: GET /api/v1/users/search/?timezone_offset=28800&q=93.minho&count=30 - 403 Forbidden; login_required
```
I got 
```
error: Instagram login fail: IgResponseError: POST /api/v1/accounts/msisdn_header_bootstrap/ - 302 Found; 
```

**Comment by shizunge** [comment]
Found this  post
https://github.com/dilame/instagram-private-api/issues/1417

It looks something wrong in the `instagram-private-api` library. 
Maybe we do not need the preloginflow in https://github.com/DIYgod/RSSHub/blob/master/lib/routes/instagram/utils.js, suggesting by https://github.com/dilame/instagram-private-api/issues/1417#issuecomment-896905280

**Comment by gov-sec** [comment]
im getting the same thing

**Comment by macron13** [comment]
install by docker:
docker run -d --name rsshub -p 1200:1200 -e CACHE_EXPIRE=3600 -e  IG_USERNAME=user -e IG_PASSWORD=**** 
diygod/rsshub

> rsshub@1.0.0 start /app
> node lib/index.js

info: Listening Port 1200
info: 🎉 RSSHub start! Cheers!
info: 💖 Can you help keep this open source project alive? Please sponsor 👉 https://docs.rsshub.app/en/support
info: /instagram/user/opkorolev, user IP: ::ffff:
error: Instagram error: IgLoginRequiredError: GET /api/v1/users/search/?timezone_offset=28800&q=user&count=30 - 403 Forbidden; login_required
error: Instagram login fail: IgResponseError: POST /api/v1/accounts/msisdn_header_bootstrap/ - 302 Found; 
error: Error in /instagram/user/opkorolev: GET /api/v1/users/search/?timezone_offset=28800&q=user&count=30 - 403 Forbidden; login_required

i week ago it's worked :(
