### ISSUE TITLE
PM2管理后闪退

### ISSUE THREAD

**Issue by starsareintherose** [DIYgod/RSSHub#7341]
#### 预期是什么
可以Ubuntu 20.04 LTS 正常访问
#### 实际发生了什么
```
guoyi@Helix:~/RSSHub$ sudo pm2 start lib/index.js --name rsshub
[PM2] Applying action restartProcessId on app [rsshub](ids: 0)
[PM2] [rsshub](0) ✓
[PM2] Process successfully started
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
├────┼────────────────────┼──────────┼──────┼───────────┼──────────┼──────────┤
│ 0  │ rsshub             │ fork     │ 30   │ online    │ 0%       │ 8.2mb    │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
guoyi@Helix:~/RSSHub$ pm2
usage: pm2 [options] <command>

pm2 -h, --help             all available commands and options
pm2 examples               display pm2 usage examples
pm2 <command> -h           help on a specific command

Access pm2 files in ~/.pm2
guoyi@Helix:~/RSSHub$ pm2 list
┌────┬────────────────────┬──────────┬──────┬───────────┬──────────┬──────────┐
│ id │ name               │ mode     │ ↺    │ status    │ cpu      │ memory   │
└────┴────────────────────┴──────────┴──────┴───────────┴──────────┴──────────┘
Module
┌────┬────────────────────┬──────────┬──────────┬──────────┐
│ id │ name               │ status   │ cpu      │ mem      │
├────┼────────────────────┼──────────┼──────────┼──────────┤
│ 0  │ got                │ online   │ 0%       │ 44.9mb   │
└────┴────────────────────┴──────────┴──────────┴──────────┘
```
#### 部署相关信息
Ubuntu 20.04 LTS

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |        Ubuntu 20.04       |
| Node version       |      v10.19.0        |
| if Docker, version |        NA       |

- 额外信息（日志、报错等）
```
guoyi@Helix:~/RSSHub$ sudo npm start

> rsshub@1.0.0 start
> node lib/index.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'module-alias'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/guoyi/RSSHub/lib/app.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by TonyRL** [comment]
Similar issue https://github.com/DIYgod/RSSHub/issues/8957
