### ISSUE TITLE
yarn format 出现 Must use import to load ES Module 错误

### ISSUE THREAD

**Issue by hxse** [DIYgod/RSSHub#7434]
#### 预期是什么
`yarn format` 正常格式化代码
#### 实际发生了什么
报错 `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module `
看起来是 `RSSHub\docs\.format\chineseFormat.js` 这个文件里用了 require() , 但node_modules里却是 ES模块?
#### 部署相关信息

- 额外信息（日志、报错等）
```
D:\Note\02-Computer\program\rsshub\RSSHub>yarn run format
yarn run v1.22.5
$ eslint "**/*.js" --fix && node docs/.format/format.js && prettier "**/*.{js,json}" --write
internal/modules/cjs/loader.js:1153
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\Note\02-Computer\program\rsshub\RSSHub\node_modules\string-width\index.js
require() of ES modules is not supported.
require() of D:\Note\02-Computer\program\rsshub\RSSHub\node_modules\string-width\index.js from D:\Note\02-Computer\program\rsshub\RSSHub\docs\.format\chineseFormat.js is an ES 
module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\Note\02-Computer\program\rsshub\RSSHub\node_modules\string-width\package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:13)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\Note\02-Computer\program\rsshub\RSSHub\docs\.format\chineseFormat.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by NeverBehave** [comment]
请报一下node版本号

**Comment by hxse** [comment]
> 请报一下node版本号
node -v
v12.18.3

**Comment by NeverBehave** [comment]
https://github.com/DIYgod/RSSHub/pull/7012

**Comment by Wsine** [comment]
我这边测试了一下，也有相同的问题，在 Node 版本大于 14 的情况下，仓库目录没有做任何更改

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/8842278/117529043-e1885500-b007-11eb-9fb4-e8b480256813.png">
