### ISSUE TITLE
运行提示: TypeError: Cannot read property 'json' of undefined

### ISSUE THREAD

**Issue by pivdets** [DIYgod/RSSHub#75]
运行提示:

```
$ nodejs index.js
/home/pivdets/RSSHub/utils/logger.js:5
    format: winston.format.json(),
                           ^

TypeError: Cannot read property 'json' of undefined
    at Object.<anonymous> (/home/pivdets/RSSHub/utils/logger.js:5:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pivdets/RSSHub/index.js:3:16)
    at Module._compile (module.js:652:30)
```

操作系统: 
```
$ cat /etc/issue
Ubuntu 16.04.4 LTS \n \l
```

node 版本:
```bash
$ nodejs -v
v8.11.1
```

相关模块版本:
```bash
$ yarn list winston koa
yarn list v1.6.0
warning ../package.json: No license field
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ koa@2.5.0
└─ winston@3.0.0-rc3
Done in 0.52s.
```

**Comment by DerekTso** [comment]
instead of `$ nodejs index.js`
try `$ node index.js`

**Comment by DIYgod** [comment]
无法复现，请尝试更新 node 版本或重新安装依赖
