### ISSUE TITLE
npm run script 在 node_modules 使用软链接时，加载 $(npm bin) 项目本地安装的包出错

### ISSUE THREAD

**Issue by Maecenas** [DIYgod/RSSHub#767]
在 #762 遇到的问题

**Expected behavior:**

`$ npm run lint` 和 `$ npm run format` 时使用项目显式指定安装的依赖（ESLint、Prettier）。

npm run script 时会自动把 `$(npm bin)` 加到 `PATH` 最前面。

一开始我以为是文件路径带空格而无法解析的问题，（iCloud Drive 路径在 `~/Library/Mobile Documents/com~apple~CloudDocs/`），切换新目录没有解决问题。

**Actual behavior:**

```
ESLint: 5.6.0.
ESLint couldn't find the plugin "eslint-plugin-prettier". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-prettier is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-prettier@latest --save-dev

Path to ESLint package: /usr/local/lib/node_modules/eslint
```

**Environment:**

node v10.11.0
npm v6.4.1
macOS High Sierra 10.13.6 (17G2208)

**Logs:**

```
$ npm run lint         

> rsshub@0.0.1 lint ~/RSSHub
> eslint "**/*.js" && prettier-check "**/*.{js,json,md}"

Cannot find module 'eslint-config-cssnano'
Referenced from: ~/RSSHub/node_modules.nosync/@vue/component-compiler-utils/node_modules/postcss-selector-parser/package.json
Error: Cannot find module 'eslint-config-cssnano'
Referenced from: ~/RSSHub/node_modules.nosync/@vue/component-compiler-utils/node_modules/postcss-selector-parser/package.json
    at ModuleResolver.resolve (~/RSSHub/node_modules.nosync/eslint/lib/util/module-resolver.js:72:19)
    at resolve (~/RSSHub/node_modules.nosync/eslint/lib/config/config-file.js:484:28)
    at load (~/RSSHub/node_modules.nosync/eslint/lib/config/config-file.js:556:26)
    at configExtends.reduceRight ~/RSSHub/node_modules.nosync/eslint/lib/config/config-file.js:430:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends ~/RSSHub/node_modules.nosync/eslint/lib/config/config-file.js:408:26)
    at loadFromDisk (~/RSSHub/node_modules.nosync/eslint/lib/config/config-file.js:528:22)
    at Object.load (~/RSSHub/node_modules.nosync/eslint/lib/config/config-file.js:564:20)
    at Config.getLocalConfigHierarchy (~/RSSHub/node_modules.nosync/eslint/lib/config.js:227:44)
    at Config.getConfigHierarchy (~/RSSHub/node_modules.nosync/eslint/lib/config.js:179:43)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! rsshub@0.0.1 lint: `eslint "**/*.js" && prettier-check "**/*.{js,json,md}"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the rsshub@0.0.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-09-22T05_39_50_188Z-debug.log
```

**Comment by Maecenas** [comment]
问题解决。排查了一圈下来还是和 iCloud Drive 有关系，原因出在 npm / node_modules 的符号链接上。
`$ rm -rf node_modules*` 再  `$ npm install` 后问题解决。问题能稳定复现。

[Ways to exclude folder from iCloud Drive](https://apple.stackexchange.com/a/295929)
由于我不希望把 `node_modules` 上传到云端，在 `$ npm install` 或 `$ yarn` 前会先执行如下的命令：
```bash
$ mkdir -p node_modules \
  && mv node_modules node_modules.nosync \
  && ln -sf node_modules.nosync node_modules
```
