### ISSUE TITLE
Error: Cannot find module '@babel/runtime-corejs2/regenerator'

### ISSUE THREAD

**Issue by Lezcool** [DIYgod/RSSHub#7918]
按手动部署的步骤，$ npm start后出现如下错误。

Error: Cannot find module '@babel/runtime-corejs2/regenerator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._resolveFilename (/home/bitnami/RSSHub/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/bitnami/RSSHub/node_modules/@postlight/mercury-parser/dist/mercury.js:5:43)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

网上搜索到类似错误，https://stackoverflow.com/questions/54234778/cannot-find-module-babel-runtime-regenerator-import-locally-vs-import-from-npm
但是按回答的2个方法操作后并没有用。

**Comment by TonyRL** [comment]
Please provide your deployment information
https://github.com/DIYgod/RSSHub/blob/master/.github/ISSUE_TEMPLATE/bug_report_zh.yml

**Comment by Lezcool** [comment]
success using docker
