### ISSUE TITLE
https://rsshub.app/weibo/keyword/

### ISSUE THREAD

**Issue by roceys** [DIYgod/RSSHub#799]
RSSHub 发生了一些意外:
TypeError: weiboUtils.getTime is not a function
    at ctx.state.data.item.data.map (/app/routes/weibo/keyword.js:25:37)
    at Array.map ()
    at module.exports (/app/routes/weibo/keyword.js:20:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by DIYgod** [comment]
Fixed. a039e058fb9982a7e1218e3d32ab90c1f9c1b599
