### ISSUE TITLE
Latest Docker image throws MODULE_NOT_FOUND error

### ISSUE THREAD

**Issue by zoenglinghou** [DIYgod/RSSHub#7997]
- The involved route, with all required and optional parameters
N/A
- What is expected
Latest docker image `2021-08-12` runs without an error.
- What is actually happening
Throws error at start:
```
> rsshub@1.0.0 start /app
> node lib/index.js

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'module-alias'
Require stack:
- /app/lib/app.js
- /app/lib/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/app/lib/app.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/lib/app.js', '/app/lib/index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rsshub@1.0.0 start: `node lib/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rsshub@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-12T22_31_13_401Z-debug.log
```
- Self-deployment information

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |  Ubuntu 20.04 & 21.04             |
| Node version       |               |
| if Docker, version |  `podman` 3.2.3             |

- Additional info (logs errors etc)

I am using `podman` to run the container/compose file, but the same error does not appear in `2021-07-13` with the same set up. It seems to be a docker image issue. Feel free to test with "proper" docker setup.

**Comment by Colin-XKL** [comment]
+1, 顺便提一下，为什么CI没有检测出这个问题，环境压根就启动不了，破坏性的pr不应该被合并进来的，咱那么多自动化测试为什么没起作用？

**Comment by NeverBehave** [comment]
因为CI只是测试了安装，没有测试运行

**Comment by Quan666** [comment]
> 因为CI只是测试了安装，没有测试运行

这个问题解决了吗？最新的docker镜像还是有这个问题

**Comment by nekolr** [comment]
重新拉了一下 latest，还是有这个问题

**Comment by NeverBehave** [comment]
好了，测试给加上了
