### ISSUE TITLE
订阅用户回答时出现了TypeError: Cannot read property 'actor' of undefined

### ISSUE THREAD

**Issue by moving-hawk** [DIYgod/RSSHub#8090]
#### 路由地址（不包含参数）

```
/zhihu/people/answers/

```

#### rss订阅成功的结果
```
info: /zhihu/people/answers/Masaki.Ryuu, user IP: ::ffff:127.0.0.1
info: Proxy for https://api.zhihu.com/people/Masaki.Ryuu/answers?order_by=created&offset=0&limit=10
info: Proxy for https://api.zhihu.com/appview/api/v4/answers/2081992316?include=content&is_appview=true
info: Proxy for https://api.zhihu.com/appview/api/v4/answers/2080397128?include=content&is_appview=true
info: Proxy for https://api.zhihu.com/appview/api/v4/answers/2070413646?include=content&is_appview=true
```

#### 错误的结果
```
info: /zhihu/people/answers/amorromat, user IP: ::ffff:127.0.0.1
info: Proxy for https://api.zhihu.com/people/amorromat/answers?order_by=created&offset=0&limit=10
info: Proxy for https://www.zhihu.com/api/v4/members/amorromat/activities?limit=1
error: Error in /zhihu/people/answers/amorromat: TypeError: Cannot read property 'actor' of undefined
node[1010]:     at module.exports (/opt/rsshub/lib/routes/zhihu/answers.js:30:34)
node[1010]:     at runMicrotasks (<anonymous>)
node[1010]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
node[1010]:     at async cache (/opt/rsshub/lib/middleware/cache.js:174:9)
node[1010]:     at async module.exports (/opt/rsshub/lib/middleware/parameter.js:10:5)
node[1010]:     at async module.exports (/opt/rsshub/lib/middleware/anti-hotlink.js:33:5)
node[1010]:     at async module.exports (/opt/rsshub/lib/middleware/template.js:19:5)
node[1010]:     at async /opt/rsshub/lib/middleware/api-response-handler.js:143:9
node[1010]:     at async module.exports (/opt/rsshub/lib/middleware/api-template.js:2:5)
node[1010]:     at async module.exports (/opt/rsshub/lib/middleware/utf8.js:4:5)
```
#### 去除answers.js中的if代码段
```
 20 //    if (name === '知乎用户') {
 21 //        const info = await got({
 22 //            method: 'get',
 23 //            url: `https://www.zhihu.com/api/v4/members/${id}/activities?limit=1`,
 24 //            headers: {
 25 //                ...utils.header,
 26 //                Referer: `https://www.zhihu.com/people/${id}/activities`,
 27 //                Authorization: 'oauth c3cef7c66a1843f8b3a9e6a1e3160e20', // hard-cod    ed in js
 28 //            },
 29 //        });
 30 //        name = info.data.data[0].actor.name;
 31 //    }
```

我尝试去掉answers.js中涉及url `https://www.zhihu.com/api/v4/members/{}/activities?limit=1`的if代码段 (因为我并不了解js,所以就简单的注释掉了,看起来这个代码段对实际抓取信息没有直接影响), 然后可以成功订阅,不过缺少了用户名,变成了知乎用户的知乎回答. 跟用户的隐私设置不同有关, 这个小姐姐的专栏我也订阅不上...
```
info: /zhihu/people/answers/amorromat, user IP: ::ffff:127.0.0.1
info: Proxy for https://api.zhihu.com/people/amorromat/answers?order_by=created&offset=0&limit=10
info: Proxy for https://api.zhihu.com/appview/api/v4/answers/2031055974?include=content&is_appview=true
info: Proxy for https://api.zhihu.com/appview/api/v4/answers/2017288951?include=content&is_appview=true
info: Proxy for https://api.zhihu.com/appview/api/v4/answers/1999548244?include=content&is_appview=true
```
#### 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |  Archlinux  |
| Node version       | v.16.7   |
| if Docker, version |            |

#### Aur安装包信息

```
Name            : rsshub-git
Version         : r6362.dc8ed9739-1
Description     : Everything is RSSible
Architecture    : x86_64
URL             : https://rsshub.app/
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : nodejs
Optional Deps   : chromium: for routes using a headless browser
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 62.81 MiB
Packager        : Unknown Packager
Build Date      : Sat 21 Aug 2021 05:44:54 PM CST
Install Date    : Sat 21 Aug 2021 08:50:54 PM CST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

**Comment by xianshuli** [comment]
I met the same issue with RSS URL: https://rsshub.app/zhihu/people/answers/li-xing-he-90. Can anyone help with this issue?

**Comment by TonyRL** [comment]
https://www.zhihu.com/people/amorromat/answers
`amorromat` hides his/her answers but `Masaki.Ryuu` does not.
