### ISSUE TITLE
请求支持油价rss

### ISSUE THREAD

**Issue by nageshuizeii** [DIYgod/RSSHub#818]
http://oil.usd-cny.com/

**Comment by DIYgod** [comment]
Done.

**Comment by nageshuizeii** [comment]
实例报错
RSSHub 发生了一些意外:
Error: Request failed with status code 503
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)
    at IncomingMessage.wrappedResponseEmit (/app/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:198:24)
    at endReadableNT (_stream_readable.js:1094:12)
    at Shim.applySegment (/app/node_modules/newrelic/lib/shim/shim.js:1390:20)
    at wrapper (/app/node_modules/newrelic/lib/shim/shim.js:2014:17)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by xyqfer** [comment]
感觉是[数据源](http://oil.usd-cny.com/)出问题了，等明天看看怎么样。。
<img width="1091" alt="wx20181026-235353 2x" src="https://user-images.githubusercontent.com/5186792/47577877-8b3bf500-d97a-11e8-9be5-2022f09eb01a.png">

**Comment by xyqfer** [comment]
我本地测试也出现了几次网络报错的情况，摊手...
<img width="739" alt="wx20181026-235930 2x" src="https://user-images.githubusercontent.com/5186792/47578276-95aabe80-d97b-11e8-8a54-5597a975725c.png">

**Comment by nageshuizeii** [comment]
突然就正常了，可能是这个网站有毒吧

**Comment by nageshuizeii** [comment]
能否将油价信息的具体情况放到title中，这样可以通过telegram bot直接提醒，不用通过rss阅读器阅读
![image](https://user-images.githubusercontent.com/16527235/50637915-cc620e00-0f96-11e9-889f-7009d4fa38a9.png)

**Comment by tingmusic** [comment]
目前该网址已无法使用，请问哪位大神可以修复？
