### ISSUE TITLE
[BUG]懂球帝“新闻”板块出错

### ISSUE THREAD

**Issue by tanyuzhou** [DIYgod/RSSHub#8221]
- 完整路由地址，包含所有必选与可选参数
    `/dongqiudi/top_news/`
- 预期是什么
返回懂球帝头条新闻数据

- 实际发生了什么
请求执行中返回404错误
另外有30%左右机率会返回Route requested，此情况具体如下： 
```
Error message: TypeError: Cannot read property 'newData' of undefined
    at Object.ProcessFeedType2 (***\RSSHub\lib\routes\dongqiudi\utils.js:120:46)
    at module.exports (***\RSSHub\lib\routes\dongqiudi\top_news.js:38:15)
    at runMicrotasks ()
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async cache (***\RSSHub\lib\middleware\cache.js:172:9)
    at async module.exports (***\RSSHub\lib\middleware\parameter.js:9:5)
    at async module.exports (***\RSSHub\lib\middleware\anti-hotlink.js:33:5)
    at async module.exports (***\RSSHub\lib\middleware\template.js:19:5)
    at async ***\RSSHub\lib\middleware\api-response-handler.js:143:9
    at async module.exports (***\RSSHub\lib\middleware\api-template.js:2:5)
    at async module.exports (***\RSSHub\lib\middleware\utf8.js:4:5)
    at async module.exports (***\RSSHub\lib\middleware\header.js:21:5)
    at async module.exports (***\RSSHub\lib\middleware\debug.js:9:5)
    at async grant (***\RSSHub\lib\middleware\access-control.js:24:13)
    at async module.exports (***\RSSHub\lib\middleware\access-control.js:32:20)
    at async module.exports (***\RSSHub\lib\middleware\onerror.js:21:9)
```

- 部署相关信息

| Env                | Value         |
| ------------------ | ------------- |
| OS                 |Windows Server 2016  |
| Node version       |v14.17.4     |
| if Docker, version |No        |

- 额外信息（日志、报错等）
```
已确认非本地部署原因导致，`https://rsshub.app/dongqiudi/top_news/`同样存在此问题
    Response code 404 (Not Found)
```

**Comment by tanyuzhou** [comment]
@HendricksZheng 作者大大能帮忙看看吗QwQ

**Comment by tanyuzhou** [comment]
@NeverBehave

**Comment by tanyuzhou** [comment]
@HenryQW 大佬能来帮忙看看懂球帝“新闻”板块的这个故障吗？感觉可能和之前早报#7746 的问题相似，但我自己不太懂nodejs，不好修

**Comment by tanyuzhou** [comment]
已找到错误发生原因，当RSSHub尝试获取新闻的详情页HTML时，因部分文章状态异常（疑似被删除？），会导致直接返回404 Not Found，希望能够加上异常抛出
下附错误数据：
错误网页```https://www.dongqiudi.com/news/2290010.html```
错误数据（2021年09月20日）：
```
  | <title><![CDATA[苏州东吴  vs 江西北大门 比赛动态]]></title>
  | <description><![CDATA[苏州东吴  vs 江西北大门 比赛动态]]></description>
  | <guid isPermaLink="false">https://www.dongqiudi.com/news/2290010.html</guid>
  | <link>https://www.dongqiudi.com/news/2290010.html</link> 
  | </item>
```
