### ISSUE TITLE
推特失效

### ISSUE THREAD

**Issue by pipiepig** [DIYgod/RSSHub#831]

**Comment by Andiedie** [comment]
```
RSSHub 发生了一些意外:
Error: Invalid or expired token.
    at Object.exports.makeTwitError (/app/node_modules/twit/lib/helpers.js:74:13)
    at onRequestComplete (/app/node_modules/twit/lib/twitter.js:344:25)
    at Request. (/app/node_modules/twit/lib/twitter.js:364:7)
    at Request.emit (events.js:187:15)
    at Request.EventEmitter.emit (domain.js:442:20)
    at Gunzip. (/app/node_modules/twit/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:273:13)
    at Gunzip.emit (events.js:187:15)
    at Gunzip.EventEmitter.emit (domain.js:442:20)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by DIYgod** [comment]
Fixed.
