### ISSUE TITLE
部分雪球用户动态，type=2会报错

### ISSUE THREAD

**Issue by hillerliao** [DIYgod/RSSHub#859]
https://rsshub.app/xueqiu/user/1955602780/2?

```
RSSHub 发生了一些意外:
Error: Request failed with status code 400
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:187:15)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.wrapped (/app/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)
    at IncomingMessage.wrappedResponseEmit (/app/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:198:24)
    at endReadableNT (_stream_readable.js:1092:12)
    at Shim.applySegment (/app/node_modules/newrelic/lib/shim/shim.js:1390:20)
    at wrapper (/app/node_modules/newrelic/lib/shim/shim.js:2014:17)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by HenryQW** [comment]
部分用户这个接口会返回超时，是接口的问题。
