### ISSUE TITLE
构建文档时报错：User defined id attribute 'm-x' is NOT unique. Please fix it in your markdown to continue.

### ISSUE THREAD

**Issue by SylleoYr** [DIYgod/RSSHub#8845]
### 路由地址

none

### 完整路由地址

none

### 相关文档

https://docs.rsshub.app/

### 预期是什么？

执行 `npm run docs:dev` 或 `npm run docs:build` 时成功构建文档。

### 实际发生了什么？

无论是在线构建还是本地构建均发生如下报错（尝试升级至最新的 node 仍然报错）：

```
> rsshub@1.0.0 docs:dev /home/user/Git/RSSHub
> vuepress dev docs

wait Extracting site metadata...
tip Apply theme @vuepress/theme-default ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/active-header-links (i.e. "@vuepress/plugin-active-header-links") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin smooth-scroll (i.e. "vuepress-plugin-smooth-scroll") ...
tip Apply plugin @vuepress/google-analytics (i.e. "@vuepress/plugin-google-analytics") ...
tip Apply plugin @vuepress/pwa (i.e. "@vuepress/plugin-pwa") ...
tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...
Error: User defined id attribute 'm-x' is NOT unique. Please fix it in your markdown to continue.
    at uniqueSlug (/home/user/Git/RSSHub/docs/.format/md/hierarchySlug.js:39:15)
    at Array.<anonymous> (/home/user/Git/RSSHub/docs/.format/md/hierarchySlug.js:98:30)
    at Core.process (/home/user/Git/RSSHub/node_modules/@vuepress/markdown/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/home/user/Git/RSSHub/node_modules/@vuepress/markdown/node_modules/markdown-it/lib/index.js:523:13)
    at module.exports (/home/user/Git/RSSHub/node_modules/@vuepress/shared-utils/lib/extractHeaders.js:22:23)
    at Page.process (/home/user/Git/RSSHub/node_modules/@vuepress/core/lib/node/Page.js:117:25)
    at async App.addPage (/home/user/Git/RSSHub/node_modules/@vuepress/core/lib/node/App.js:354:5)
    at async /home/user/Git/RSSHub/node_modules/@vuepress/core/lib/node/App.js:339:7
    at async Promise.all (index 0)
    at async App.resolvePages (/home/user/Git/RSSHub/node_modules/@vuepress/core/lib/node/App.js:337:5)
    at async App.process (/home/user/Git/RSSHub/node_modules/@vuepress/core/lib/node/App.js:115:5)
    at async dev (/home/user/Git/RSSHub/node_modules/@vuepress/core/lib/index.js:17:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rsshub@1.0.0 docs:dev: `vuepress dev docs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rsshub@1.0.0 docs:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

### 部署

自建

### 部署相关信息

OS: Ubuntu 20.04  node: v12.18.4  克隆仓库本地构建

### 额外信息

```shell
相应的 log 文件：


0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/user/.nvm/versions/node/v12.18.4/bin/node',
1 verbose cli   '/home/user/.nvm/versions/node/v12.18.4/bin/npm',
1 verbose cli   'run',
1 verbose cli   'docs:dev'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.4
4 verbose run-script [ 'predocs:dev', 'docs:dev', 'postdocs:dev' ]
5 info lifecycle rsshub@1.0.0~predocs:dev: rsshub@1.0.0
6 info lifecycle rsshub@1.0.0~docs:dev: rsshub@1.0.0
7 verbose lifecycle rsshub@1.0.0~docs:dev: unsafe-perm in lifecycle true
8 verbose lifecycle rsshub@1.0.0~docs:dev: PATH: /home/user/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/Git/RSSHub/node_modules/.bin:/home/user/.nvm/versions/node/v12.18.4/bin:/home/user/.poetry/bin:/home/user/.pyenv/plugins/pyenv-virtualenv/shims:/home/user/.pyenv/shims:/home/user/.pyenv/bin:/home/user/.poetry/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle rsshub@1.0.0~docs:dev: CWD: /home/user/Git/RSSHub
10 silly lifecycle rsshub@1.0.0~docs:dev: Args: [ '-c', 'vuepress dev docs' ]
11 silly lifecycle rsshub@1.0.0~docs:dev: Returned: code: 1  signal: null
12 info lifecycle rsshub@1.0.0~docs:dev: Failed to exec docs:dev script
13 verbose stack Error: rsshub@1.0.0 docs:dev: `vuepress dev docs`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/user/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/user/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid rsshub@1.0.0
15 verbose cwd /home/user/Git/RSSHub
16 verbose Linux 5.11.0-44-generic
17 verbose argv "/home/user/.nvm/versions/node/v12.18.4/bin/node" "/home/user/.nvm/versions/node/v12.18.4/bin/npm" "run" "docs:dev"
18 verbose node v12.18.4
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error rsshub@1.0.0 docs:dev: `vuepress dev docs`
22 error Exit status 1
23 error Failed at the rsshub@1.0.0 docs:dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
```


### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by SylleoYr** [comment]
另外有个建议：不知是否可以将文档独立出来，单独一个仓库，方便文档的 review 和自建（you know the reason 😔）

**Comment by SylleoYr** [comment]
使用 `yarn install && yarn run docs:build` 正常，npm 依然存在。

**Comment by ret-1** [comment]
一样的问题，但是我开始可以正常构建文档，后来装了chrome并且加了一个路由之后就出现这个报错了

**Comment by TonyRL** [comment]
fixed in https://github.com/DIYgod/RSSHub/commit/b4ec4af7add0a7f9e135eda1526ca4e4b5c8b38e

**Comment by TonyRL** [comment]
Part of https://github.com/DIYgod/RSSHub/commit/b4ec4af7add0a7f9e135eda1526ca4e4b5c8b38e is reverted in https://github.com/DIYgod/RSSHub/pull/9084 which may re-introduce this issue. If that happens again, please ping me.
