### ISSUE TITLE
yarn启动闪退

### ISSUE THREAD

**Issue by wedcf120** [DIYgod/RSSHub#8957]
### 路由地址

rsshub/

### 完整路由地址

rsshub/

### 相关文档

https://docs.rsshub.app/install/#shou-dong-bu-shu

### 预期是什么？

安装后无法启动, 启动即闪退

### 实际发生了什么？

安装后无法启动, 启动即闪退

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
yarn install --production
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
error jsdom@18.1.1: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.




yarn start
yarn run v1.22.17
$ node lib/index.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'module-alias'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/RSSHub/lib/app.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Upgrade your Node.js version.
Node.js v10 is EOL on 30 Apr 2021, Node.js v12 will become EOL on 30 Apr 2022.
It's suggested to use v14 or above.

**Comment by wedcf120** [comment]
> Upgrade your Node.js version. Node.js v10 is EOL on 30 Apr 2021, Node.js v12 will become EOL on 30 Apr 2022. It's suggested to use v14 or above.

启动成功了，但是却无法打开调试页面?

[root@vultr RSSHub]# yarn start
yarn run v1.22.17
$ node lib/index.js
info: Listening Port 1200
info: 🎉 RSSHub start! Cheers!
info: 💖 Can you help keep this open source project alive? Please sponsor 👉 https://docs.rsshub.app/en/support

http://139.180.203.159:1200/

**Comment by TonyRL** [comment]
Please check your firewall setting.

**Comment by wedcf120** [comment]
> Please check your firewall setting.

升级了Node.js和关闭了防火墙 解决了 感谢提示！
