### ISSUE TITLE
javlibrary失效

### ISSUE THREAD

**Issue by wedcf120** [DIYgod/RSSHub#9167]
### 路由地址

rsshub/javlibrary

### 完整路由地址

https://rsshub.app/javlibrary/stars/aegeq

### 相关文档

https://rsshub.app/javlibrary/stars/aegeq

### 预期是什么？

无法抓取内容

### 实际发生了什么？

https://rsshub.app/javlibrary/newrelease/cn
https://rsshub.app/javlibrary/newentries/cn
另外两个路由 最新加入的影片和新发行的影片 也失效了

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Route requested: /stars/aegeq
Error message: Response code 404 (Not Found): target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue: 
Path: /stars/aegeq
Node version: v16.3.0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by nczitzk** [comment]
路由为 [/javlibrary/star/aegeq](https://rsshub.app/javlibrary/star/aegeq)，而非 [/javlibrary/stars/aegeq](https://rsshub.app/javlibrary/stars/aegeq)

**Comment by wedcf120** [comment]
我在我自己服务器部署的rsshub git pull更新了一下 发现还是 stars/****  star/****用不了，会有以下报错:

Route requested: /javlibrary/star/aegeq
Error message: Error: wrong path
    at module.exports (/root/RSSHub/lib/middleware/parameter.js:16:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/root/RSSHub/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/root/RSSHub/lib/middleware/template.js:14:5)
    at async /root/RSSHub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/root/RSSHub/lib/middleware/api-template.js:2:5)
    at async module.exports (/root/RSSHub/lib/middleware/utf8.js:4:5)
    at async module.exports (/root/RSSHub/lib/middleware/header.js:21:5)
    at async module.exports (/root/RSSHub/lib/middleware/debug.js:9:5)
    at async grant (/root/RSSHub/lib/middleware/access-control.js:24:13)
Helpful Information to provide when opening issue: 
Path: /javlibrary/star/aegeq
Node version: v17.4.0

https://docs.rsshub.app/multimedia.html#javlibrary
文档里写的排序方式用不了, 比如
/javlibrary/stars/aegeq/cn/1
或
/javlibrary/star/aegeq/cn/1

然后 最新加入的影片 和 最新发行的影片也是同样用不了
/javlibrary/videos/newentries
/javlibrary/videos/newrelease
我自己部署的是在用旧的 依然有效

**Comment by nczitzk** [comment]
> 然后 最新加入的影片 和 最新发行的影片也是同样用不了 /javlibrary/videos/newentries /javlibrary/videos/newrelease 我自己部署的是在用旧的 依然有效

请检查部署的 RSSHub 版本，目前 5324eef 本地部署测试路由正常。

**Comment by TonyRL** [comment]
Both https://rsshub.app/javlibrary/star/aegeq and https://rsshub.app/javlibrary/star/aegeq/cn/1 is working as of replying
