### ISSUE TITLE
ORCID

### ISSUE THREAD

**Issue by starsareintherose** [DIYgod/RSSHub#9170]
### 路由地址

/orcid

### 完整路由地址

/orcid/:id

### 相关文档

https://docs.rsshub.app/study.html#orcid

### 预期是什么？

Can get

### 实际发生了什么？

https://rsshub.app/orcid/0000-0002-4731-9700

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
My selfhost

Route requested: /orcid/0000-0002-4731-9700
Error message: Error: wrong path
    at module.exports (/opt/rsshub/lib/middleware/parameter.js:16:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/opt/rsshub/lib/middleware/anti-hotlink.js:33:5)
    at async module.exports (/opt/rsshub/lib/middleware/template.js:14:5)
    at async /opt/rsshub/lib/middleware/api-response-handler.js:143:9
    at async module.exports (/opt/rsshub/lib/middleware/api-template.js:2:5)
    at async module.exports (/opt/rsshub/lib/middleware/utf8.js:4:5)
    at async module.exports (/opt/rsshub/lib/middleware/header.js:21:5)
    at async module.exports (/opt/rsshub/lib/middleware/debug.js:9:5)
    at async grant (/opt/rsshub/lib/middleware/access-control.js:24:13)
Helpful Information to provide when opening issue: 
Path: /orcid/0000-0002-4731-9700
Node version: v17.5.0
        
```

Official
```
Route requested: /orcid/0000-0002-4731-9700
Error message: wrong path
Helpful Information to provide when opening issue: 
Path: /orcid/0000-0002-4731-9700
Node version: v16.3.0
        
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
Demo does not run the latest RSSHub.

**Comment by starsareintherose** [comment]
> Demo does not run the latest RSSHub.

I both use my selfhost and demo

**Comment by TonyRL** [comment]
> > Demo does not run the latest RSSHub.
> 
> I both use my selfhost and demo

https://rsshub.up.railway.app/orcid/0000-0002-4731-9700

**Comment by starsareintherose** [comment]
Maybe the problems by `systemctl restart rsshub` configure wrong

**Comment by starsareintherose** [comment]
But my selfhost still show that, and it works for 0000-0002-4731-9700 but not for others
```
Route requested: /0000-0002-3005-6246
Error message: TypeError: Cannot read properties of null (reading 'value')
    at /opt/rsshub/lib/v2/orcid/index.js:37:49
    at Array.map ()
    at module.exports (/opt/rsshub/lib/v2/orcid/index.js:21:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /opt/rsshub/node_modules/koa-mount/index.js:58:5
    at async /opt/rsshub/node_modules/koa-mount/index.js:52:26
    at async /opt/rsshub/lib/middleware/load-on-demand.js:29:9
    at async /opt/rsshub/lib/middleware/cache/index.js:119:13
    at async /opt/rsshub/node_modules/koa-mount/index.js:52:26
    at async module.exports (/opt/rsshub/lib/middleware/parameter.js:10:5)
Helpful Information to provide when opening issue: 
Path: /0000-0002-3005-6246
Node version: v17.5.0
```
I input `/orcid/0000-0002-3005-6246` but it shows that the path `/0000-0002-3005-6246`

**Comment by starsareintherose** [comment]
It can only recognize the path2/path3 in the rsshub.domain.net/path1/path2/path3

**Comment by NeverBehave** [comment]
Seems the link is working right now

**Comment by starsareintherose** [comment]
I don't know, for some reason
Route requested: /0000-0002-4731-9700
Error message: connect EHOSTUNREACH 2606:4700:10::6814:e546:443: target website might be blocking our access, you can host your own RSSHub instance for a better usability.
Helpful Information to provide when opening issue:
Path: /0000-0002-4731-9700
Node version: v18.2.0
Git Hash: unknown
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github

**Comment by starsareintherose** [comment]
It still have the path issue

**Comment by NeverBehave** [comment]
The link you posted in the issue is working

**Comment by TonyRL** [comment]
> Node version: v18.2.0
Could you test again against node 14 or node 16?

**Comment by starsareintherose** [comment]
with node 16, it works now. But for other web, `/oup/journals/sysbio` still shows `Route requested: /journals/sysbio`

```
Error message: TypeError: Cannot read properties of undefined (reading 'map')
    at module.exports (/opt/rsshub/lib/v2/oup/index.js:14:52)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /opt/rsshub/node_modules/koa-mount/index.js:58:5
    at async /opt/rsshub/node_modules/koa-mount/index.js:52:26
    at async /opt/rsshub/node_modules/koa-mount/index.js:52:26
    at async /opt/rsshub/node_modules/koa-mount/index.js:52:26
    at async /opt/rsshub/lib/middleware/load-on-demand.js:29:9
    at async /opt/rsshub/lib/middleware/cache/index.js:119:13
    at async /opt/rsshub/node_modules/koa-mount/index.js:52:26
    at async module.exports (/opt/rsshub/lib/middleware/parameter.js:10:5)
Helpful Information to provide when opening issue:
Path: /journals/sysbio
Node version: v16.15.0
Git Hash: unknown
        
```
I am not if it's totally related with the version

**Comment by starsareintherose** [comment]
sorry, I change to custom url, still shows
```
Route requested: /0000-0002-3005-6246/
Error message: TypeError: Cannot read properties of null (reading 'value')
    at /opt/rsshub/lib/v2/orcid/index.js:37:49
    at Array.map ()
    at module.exports (/opt/rsshub/lib/v2/orcid/index.js:21:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /opt/rsshub/node_modules/koa-mount/index.js:58:5
    at async /opt/rsshub/node_modules/koa-mount/index.js:52:26
    at async /opt/rsshub/node_modules/koa-mount/index.js:52:26
    at async /opt/rsshub/node_modules/koa-mount/index.js:52:26
    at async /opt/rsshub/node_modules/koa-mount/index.js:52:26
    at async /opt/rsshub/node_modules/koa-mount/index.js:52:26
Helpful Information to provide when opening issue:
Path: /0000-0002-3005-6246/
Node version: v16.15.0
Git Hash: unknown
        ```

**Comment by starsareintherose** [comment]
RSSHub shows similar issue
https://rsshub.app/orcid/0000-0002-3005-6246

**Comment by TonyRL** [comment]
/test
```routes
/orcid/0000-0002-3005-6246
```
