### ISSUE TITLE
微博个人时间线 SyntaxError: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by Orokapei** [DIYgod/RSSHub#9462]
### 路由地址

/weibo/timeline/

### 完整路由地址

/weibo/timeline/6132646930

### 相关文档

https://docs.rsshub.app/social-media.html#wei-bo-ge-ren-shi-jian-xian

### 预期是什么？

正常抓取

### 实际发生了什么？

```Error message: SyntaxError: Unexpected token o in JSON at position 1```

### 部署

自建

### 部署相关信息

OS: Linux 5.10.102.1-microsoft-standard-WSL2   Node: v17.8.0  Git Hash: 19608ab

### 额外信息

```shell
Error message: SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse ()
    at /home/orokapei/rsshub/lib/routes/weibo/timeline.js:73:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async module.exports (/home/orokapei/rsshub/lib/routes/weibo/timeline.js:66:28)
    at async /home/orokapei/rsshub/lib/middleware/load-on-demand.js:29:9
    at async /home/orokapei/rsshub/lib/middleware/cache/index.js:119:13
    at async /home/orokapei/rsshub/node_modules/koa-mount/index.js:52:26
    at async module.exports (/home/orokapei/rsshub/lib/middleware/parameter.js:10:5)
    at async module.exports (/home/orokapei/rsshub/lib/middleware/anti-hotlink.js:33:5)
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Orokapei** [comment]
再补一张图，搜了一下怎么获取的信息，同一环境手动能获取到内容 = = 这就应该不是网络、反爬的问题吧
![image](https://user-images.githubusercontent.com/23261300/161585553-1481760d-ebaa-498c-9ad7-7d0dbdacb1bc.png)
