### ISSUE TITLE
RSSHub 发生了一些意外: spawn wmic ENOENT

### ISSUE THREAD

**Issue by YoungSx** [DIYgod/RSSHub#979]
刚安装在一台Win主机上，远程访问IP:1200出现这个报错
RSSHub 发生了一些意外:
Error: Error: spawn wmic ENOENT
    at ChildProcess. (C:\Users\Administrator\RSSHub\node_modules\_pidusage@2.0.17@pidusage\lib\bin.js:33:10)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by YoungSx** [comment]
node-v10.12.0

**Comment by DIYgod** [comment]
windows 跑 node 经常出现奇奇怪怪的问题，建议使用 docker 或换 linux
