### ISSUE TITLE
【中国海关-拍卖信息】自建和官方均报错，报错信息不同

### ISSUE THREAD

**Issue by KwToPA** [DIYgod/RSSHub#9882]
### 路由地址

```routes
/gov/customs/list/paimai
```

### 完整路由地址

```fullroutes
https://rsshub.app/gov/customs/list/paimai
```

### 相关文档

https://docs.rsshub.app/government.html#zhong-hua-ren-min-gong-he-guo-hai-guan-zong-shu

### 预期是什么？

正常工作

### 实际发生了什么？

官方报错

```
Route requested: /customs/list/paimai
Error message: Navigation failed because browser has disconnected!
Helpful Information to provide when opening issue:
Path: /customs/list/paimai
Node version: v16.3.0
Git Hash: f38716c
```

自建报错
```
Route requested: /customs/list/paimai
Error message: Error: Failed to launch the browser process!
/RSSHub/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/RSSHub/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface. (/RSSHub/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Helpful Information to provide when opening issue:
Path: /customs/list/paimai
Node version: v14.18.1
Git Hash: f38716c
```

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
官方报错


Route requested: /customs/list/paimai
Error message: Navigation failed because browser has disconnected!
Helpful Information to provide when opening issue:
Path: /customs/list/paimai
Node version: v16.3.0
Git Hash: f38716c
```

自建报错
```
Route requested: /customs/list/paimai
Error message: Error: Failed to launch the browser process!
/RSSHub/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/RSSHub/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface. (/RSSHub/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Helpful Information to provide when opening issue:
Path: /customs/list/paimai
Node version: v14.18.1
Git Hash: f38716c
```
```


### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by KwToPA** [comment]
谢谢，已经成功抓取/

```
wget http://mirror.centos.org/centos/7/os/x86_64/Packages/at-spi2-atk-2.26.2-1.el7.x86_64.rpm;wget http://mirror.centos.org/centos/7/os/x86_64/Packages/libxkbcommon-x11-0.7.1-3.el7.x86_64.rpm; rpm -ivh at-spi2-atk-2.26.2-1.el7.x86_64.rpm; rpm -ivh libxkbcommon-x11-0.7.1-3.el7.x86_64.rpm;
```
再删掉rpm包即可。

**Comment by KwToPA** [comment]
我以为成功了，结果一直抓取中
```
This path is currently fetching, please come back later!
```

**Comment by KwToPA** [comment]
还是一直抓取中

**Comment by KwToPA** [comment]
用ttrss强制抓取反馈
```
 unable to fetch: ; 28 Operation timed out after 15001 milliseconds with 0 bytes received [0]
```

**Comment by KwToPA** [comment]
用feed43直接报错
```
http 412 Precondition Failed
```
